export { CDR_CONTEXT_NAME, CDR_WRITER_SETTING_NAME, cdrTenantContext } from "./cdr-context";
export {
	createCdrDatabaseClient,
	resolveCdrDatabaseUrl,
	type CdrDatabase,
	type CdrDatabaseClient,
	type CdrDatabaseTransaction,
} from "./client";
export {
	ANSWERED_HANGUP_CAUSES,
	EXTENDED_HANGUP_CAUSES,
	HANGUP_CAUSE_CODES,
	HANGUP_CAUSE_NAMES,
	HANGUP_CAUSES,
	hangupCauseCode,
	hangupCauseFromCode,
	isAnsweredCause,
	isHangupCause,
	isRetryableCause,
	Q850_HANGUP_CAUSES,
	RETRYABLE_HANGUP_CAUSES,
	type ExtendedHangupCause,
	type HangupCause,
	type Q850HangupCause,
} from "@optimiq-voice/telephony";
export {
	addMonths,
	assertPartitionedCdrTable,
	buildCreateDefaultPartitionSql,
	buildCreateMonthlyPartitionSql,
	CDR_DROP_PARTITIONS_FUNCTION,
	CDR_ENSURE_PARTITION_FUNCTION,
	CDR_PARTITION_KEYS,
	createMonthlyPartition,
	defaultPartitionName,
	dropPartitionsBeforeQuery,
	ensureMonthlyPartitionQuery,
	ensureMonthlyPartitions,
	monthlyPartitionName,
	monthlyPartitionRange,
	monthsInHorizon,
	monthStart,
	PARTITIONED_CDR_TABLES,
	PartitionedTableError,
	toDateLiteral,
	type MonthlyPartitionRange,
	type PartitionedCdrTable,
	type PartitionExecutor,
} from "./partitions";
export { createCdrTenantRlsIntrospector } from "./rls-introspector";
export { CDR_APPEND_ONLY_TABLES, cdrTenantRlsPreflightPlan } from "./rls-preflight-plan";
export {
	and,
	asc,
	between,
	count,
	desc,
	eq,
	getTableConfig,
	getTableName,
	gt,
	gte,
	ilike,
	inArray,
	isNotNull,
	isNull,
	lt,
	lte,
	ne,
	not,
	notInArray,
	or,
	sql,
	type AnyPgColumn,
	type PgColumn,
	type PgTable,
	type SQL,
} from "./sql";
export {
	DEFAULT_CDR_RETENTION_MONTHS,
	DEFAULT_RECORDING_TOMBSTONE_MONTHS,
	dropPartitionsBefore,
	expiredRecordingsSelectQuery,
	expiredRecordingsUpdateQuery,
	planCdrRetention,
	purgedRecordingSoftDeleteQuery,
	purgedRecordingTombstoneDeleteQuery,
	retentionCutoff,
	RetentionWindowError,
	runCdrRetention,
	type CdrRetentionOutcome,
	type CdrRetentionPlan,
} from "./retention";
export {
	buildCallLegEnrichmentQuery,
	CdrWriterScopeError,
	ENRICHABLE_CALL_LEG_COLUMNS,
	withCdrWriterScope,
	type CallLegEnrichment,
	type CallLegEnrichmentTarget,
	type CdrWriterDatabase,
	type CdrWriterTransactionHandle,
} from "./writer";
export {
	CALL_DESTINATION_TYPES,
	CALL_DIRECTIONS,
	CALL_DISPOSITIONS,
	CALL_EVENT_TYPES,
	CALL_LEG_SIDES,
	callEvents,
	callLegs,
	CDR_QUARANTINE_REASONS,
	cdrSchema,
	cdrWriteQuarantine,
	HANGUP_SIDES,
	RECORDING_KINDS,
	recordings,
	TRANSCRIPTION_STATUSES,
	type CallDestinationType,
	type CallDirection,
	type CallDisposition,
	type CallEventRow,
	type CallEventType,
	type CallLegRow,
	type CallLegSide,
	type CdrQuarantineReason,
	type CdrSchema,
	type CdrWriteQuarantineRow,
	type HangupSide,
	type NewCallEventRow,
	type NewCallLegRow,
	type NewCdrWriteQuarantineRow,
	type NewRecordingRow,
	type RecordingKind,
	type RecordingRow,
	type TranscriptionStatus,
} from "./schema/index";
