-- Identity-removal Step 5 item 2 — the tenant role and per-table isolation policies for the
-- telephony database. Generated by drizzle-kit from `src/core/db/schema.ts`; only the CREATE ROLE
-- is hand-edited, because PostgreSQL roles are CLUSTER-wide while migrations are per-database.
-- Two `apps/api` databases in one cluster (staging + a restore, say) would otherwise make the
-- second deploy fail on a role that already exists and is already correct.
DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'api_tenant_tls') THEN
		CREATE ROLE "api_tenant_tls" WITH NOINHERIT;
	END IF;
END
$$;--> statement-breakpoint
ALTER TABLE "applications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "intelligence_services" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "secrets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "stt_services" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tts_services" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "applications_tenant_isolation" ON "applications" AS PERMISSIVE FOR ALL TO "api_tenant_tls" USING (organization_id = nullif(current_setting('api_tenant_tls.organization_id', true), '')::uuid) WITH CHECK (organization_id = nullif(current_setting('api_tenant_tls.organization_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "intelligence_services_tenant_isolation" ON "intelligence_services" AS PERMISSIVE FOR ALL TO "api_tenant_tls" USING (organization_id = nullif(current_setting('api_tenant_tls.organization_id', true), '')::uuid) WITH CHECK (organization_id = nullif(current_setting('api_tenant_tls.organization_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "secrets_tenant_isolation" ON "secrets" AS PERMISSIVE FOR ALL TO "api_tenant_tls" USING (organization_id = nullif(current_setting('api_tenant_tls.organization_id', true), '')::uuid) WITH CHECK (organization_id = nullif(current_setting('api_tenant_tls.organization_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "stt_services_tenant_isolation" ON "stt_services" AS PERMISSIVE FOR ALL TO "api_tenant_tls" USING (organization_id = nullif(current_setting('api_tenant_tls.organization_id', true), '')::uuid) WITH CHECK (organization_id = nullif(current_setting('api_tenant_tls.organization_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "tts_services_tenant_isolation" ON "tts_services" AS PERMISSIVE FOR ALL TO "api_tenant_tls" USING (organization_id = nullif(current_setting('api_tenant_tls.organization_id', true), '')::uuid) WITH CHECK (organization_id = nullif(current_setting('api_tenant_tls.organization_id', true), '')::uuid);