/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Source: packages/auth/src/permissions.ts
 * Regenerate: pnpm --filter @optimiq-voice/web codegen
 *
 * Data only. The predicates that interpret it live in ./permissions.ts.
 */

export const PERMISSIONS = [
	"extensions.read",
	"extensions.read.own",
	"extensions.write",
	"extensions.write.own",
	"extensions.delete",
	"extensions.assign",
	"devices.read",
	"devices.read.own",
	"devices.write",
	"devices.delete",
	"numbers.read",
	"numbers.write",
	"numbers.order",
	"numbers.delete",
	"numbers.assign",
	"numbers.emergency",
	"trunks.read",
	"trunks.write",
	"trunks.delete",
	"routes.read",
	"routes.write",
	"routes.delete",
	"routes.publish",
	"routes.simulate",
	"time-conditions.read",
	"time-conditions.write",
	"time-conditions.delete",
	"feature-codes.read",
	"feature-codes.write",
	"feature-codes.delete",
	"call-block.read",
	"call-block.write",
	"call-block.delete",
	"ivr.read",
	"ivr.write",
	"ivr.delete",
	"ivr.publish",
	"ring-groups.read",
	"ring-groups.write",
	"ring-groups.delete",
	"paging-groups.read",
	"paging-groups.write",
	"paging-groups.delete",
	"shared-lines.read",
	"shared-lines.write",
	"shared-lines.delete",
	"queues.read",
	"queues.write",
	"queues.delete",
	"queues.manage-agents",
	"queues.monitor",
	"queues.join",
	"queues.join.own",
	"voicemail.read",
	"voicemail.read.own",
	"voicemail.write",
	"voicemail.delete",
	"voicemail.delete.own",
	"voicemail.listen",
	"voicemail.listen.own",
	"conferences.read",
	"conferences.write",
	"conferences.delete",
	"conferences.moderate",
	"park-lots.read",
	"park-lots.write",
	"park-lots.delete",
	"faxes.read",
	"faxes.write",
	"faxes.delete",
	"faxes.send",
	"call-flows.read",
	"call-flows.write",
	"call-flows.delete",
	"call-flows.toggle",
	"pin-sets.read",
	"pin-sets.write",
	"pin-sets.delete",
	"dial-plan.read",
	"dial-plan.write",
	"dial-plan.delete",
	"org-limits.read",
	"org-limits.write",
	"calls.originate",
	"calls.control",
	"calls.supervise",
	"recordings.read",
	"recordings.read.own",
	"recordings.download",
	"recordings.delete",
	"recordings.configure",
	"cdr.read",
	"cdr.read.own",
	"cdr.export",
	"audit.read",
	"security.read",
	"security.write",
	"webhooks.read",
	"webhooks.write",
	"branding.write",
	"settings.read",
	"settings.write",
	"settings.read.own",
	"settings.write.own",
	"settings.write.all",
	"members.read",
	"members.invite",
	"members.update-role",
	"members.remove",
	"api-keys.read",
	"api-keys.read.own",
	"api-keys.write",
	"api-keys.write.own",
	"api-keys.revoke",
	"provisioning.read",
	"provisioning.write",
	"provisioning.tokens",
	"reseller.read",
	"reseller.write",
	"sso.configure",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const PERMISSION_SCOPES = ["own", "team", "all"] as const;

export type PermissionScope = (typeof PERMISSION_SCOPES)[number];

export interface PermissionDescriptor {
	readonly permission: Permission;
	readonly label: string;
	readonly description: string;
}

export interface PermissionGroup {
	readonly resource: string;
	readonly label: string;
	readonly description: string;
	readonly permissions: readonly PermissionDescriptor[];
}

/** Grouped, human-labelled view of {@link PERMISSIONS}. Drives the role and API-key editors. */
export const PERMISSION_CATALOG: readonly PermissionGroup[] = [
	{
		resource: "extensions",
		label: "Extensions",
		description: "Internal endpoints, their dialling behaviour and their user assignment.",
		permissions: [
			{
				permission: "extensions.read",
				label: "View extensions",
				description: "List and inspect every extension in the organization.",
			},
			{
				permission: "extensions.read.own",
				label: "View own extension",
				description: "Inspect only the extensions assigned to the acting user.",
			},
			{
				permission: "extensions.write",
				label: "Manage extensions",
				description: "Create and edit any extension, including routing and voicemail options.",
			},
			{
				permission: "extensions.write.own",
				label: "Edit own extension",
				description: "Change forwarding, do-not-disturb and follow-me on own extensions.",
			},
			{
				permission: "extensions.delete",
				label: "Delete extensions",
				description: "Permanently remove an extension and detach its devices.",
			},
			{
				permission: "extensions.assign",
				label: "Assign extensions",
				description: "Bind an extension to a member or release it.",
			},
		],
	},
	{
		resource: "devices",
		label: "Devices",
		description: "Desk phones and softphones, their lines and their programmable keys.",
		permissions: [
			{
				permission: "devices.read",
				label: "View devices",
				description: "List every registered and provisioned device.",
			},
			{
				permission: "devices.read.own",
				label: "View own devices",
				description: "Inspect only devices bound to the acting user's extensions.",
			},
			{
				permission: "devices.write",
				label: "Manage devices",
				description: "Create and edit devices, lines and key layouts.",
			},
			{
				permission: "devices.delete",
				label: "Delete devices",
				description: "Remove a device and revoke its provisioning credentials.",
			},
		],
	},
	{
		resource: "numbers",
		label: "Numbers",
		description: "DIDs, their inbound treatment and their emergency dispatch location.",
		permissions: [
			{
				permission: "numbers.read",
				label: "View numbers",
				description: "List DIDs and their current routing.",
			},
			{
				permission: "numbers.write",
				label: "Manage numbers",
				description: "Create, edit and re-route DIDs, including caller-ID overrides.",
			},
			{
				permission: "numbers.order",
				label: "Order numbers",
				description: "Buy a new DID from the connected carrier. Creates a recurring charge on the organization's account.",
			},
			{
				permission: "numbers.delete",
				label: "Delete numbers",
				description: "Release a DID from the organization, and from the carrier when the platform ordered it.",
			},
			{
				permission: "numbers.assign",
				label: "Assign numbers",
				description: "Point a DID at an extension, ring group, IVR or queue.",
			},
			{
				permission: "numbers.emergency",
				label: "Manage emergency routing",
				description: "Set the dispatchable location and notification policy (Kari's Law / RAY BAUM'S).",
			},
		],
	},
	{
		resource: "trunks",
		label: "Trunks",
		description: "Carrier connections, registrations and their credentials.",
		permissions: [
			{
				permission: "trunks.read",
				label: "View trunks",
				description: "List carriers and their registration state.",
			},
			{
				permission: "trunks.write",
				label: "Manage trunks",
				description: "Create and edit carrier connections, codecs and channel caps.",
			},
			{
				permission: "trunks.delete",
				label: "Delete trunks",
				description: "Remove a carrier connection.",
			},
		],
	},
	{
		resource: "routes",
		label: "Routing",
		description: "Inbound and outbound routes, dial patterns, time conditions and feature codes.",
		permissions: [
			{
				permission: "routes.read",
				label: "View routing",
				description: "Inspect inbound and outbound routes and their conditions.",
			},
			{
				permission: "routes.write",
				label: "Manage routing",
				description: "Create and edit routes, dial patterns, toll classes and time conditions.",
			},
			{
				permission: "routes.delete",
				label: "Delete routes",
				description: "Remove a route from the routing model.",
			},
			{
				permission: "routes.publish",
				label: "Publish routing",
				description: "Compile the routing model and invalidate the runtime routing cache.",
			},
			{
				permission: "routes.simulate",
				label: "Simulate routing",
				description: "Trace how a number would be routed without placing a call.",
			},
		],
	},
	{
		resource: "time-conditions",
		label: "Time conditions",
		description: "Business-hours and holiday schedules, and the branches they gate.",
		permissions: [
			{
				permission: "time-conditions.read",
				label: "View time conditions",
				description: "Inspect schedules, their rules and where each branch goes.",
			},
			{
				permission: "time-conditions.write",
				label: "Manage time conditions",
				description: "Create and edit schedules, rules, timezones and no-match branches.",
			},
			{
				permission: "time-conditions.delete",
				label: "Delete time conditions",
				description: "Remove a schedule once no route gates on it.",
			},
		],
	},
	{
		resource: "feature-codes",
		label: "Feature codes",
		description: "The star-code catalogue dialled from a handset.",
		permissions: [
			{
				permission: "feature-codes.read",
				label: "View feature codes",
				description: "List the star codes and the action each one runs.",
			},
			{
				permission: "feature-codes.write",
				label: "Manage feature codes",
				description: "Create and edit star codes, their actions and their parameters.",
			},
			{
				permission: "feature-codes.delete",
				label: "Delete feature codes",
				description: "Remove a star code from the dial plan.",
			},
		],
	},
	{
		resource: "call-block",
		label: "Caller screening",
		description: "The allow and deny list every call is checked against before it is routed.",
		permissions: [
			{
				permission: "call-block.read",
				label: "View screening rules",
				description: "List the blocked and allowed numbers, and how often each rule has matched.",
			},
			{
				permission: "call-block.write",
				label: "Manage screening rules",
				description: "Block or allow a caller. An allow rule overrides a broader block, so this grant can also re-admit a number the organization had excluded.",
			},
			{
				permission: "call-block.delete",
				label: "Delete screening rules",
				description: "Remove a rule permanently, discarding its match history. Disabling a rule keeps both.",
			},
		],
	},
	{
		resource: "ivr",
		label: "IVR menus",
		description: "Auto-attendant menus, prompts and their nested options.",
		permissions: [
			{
				permission: "ivr.read",
				label: "View IVR menus",
				description: "Inspect menus, options and prompts.",
			},
			{
				permission: "ivr.write",
				label: "Manage IVR menus",
				description: "Create and edit menus, digit options and greetings.",
			},
			{
				permission: "ivr.delete",
				label: "Delete IVR menus",
				description: "Remove a menu and detach it from routes.",
			},
			{
				permission: "ivr.publish",
				label: "Publish IVR menus",
				description: "Compile menu changes into the runtime routing model.",
			},
		],
	},
	{
		resource: "ring-groups",
		label: "Ring groups",
		description: "Simultaneous, sequential and rollover hunt groups.",
		permissions: [
			{
				permission: "ring-groups.read",
				label: "View ring groups",
				description: "Inspect groups, members and strategies.",
			},
			{
				permission: "ring-groups.write",
				label: "Manage ring groups",
				description: "Create and edit groups, destinations, delays and timeout actions.",
			},
			{
				permission: "ring-groups.delete",
				label: "Delete ring groups",
				description: "Remove a ring group.",
			},
		],
	},
	{
		resource: "paging-groups",
		label: "Paging groups",
		description: "Overhead announcements and talkback intercom, and the handsets each group auto-answers on.",
		permissions: [
			{
				permission: "paging-groups.read",
				label: "View paging groups",
				description: "Inspect groups, their members and the fan-out order.",
			},
			{
				permission: "paging-groups.write",
				label: "Manage paging groups",
				description: "Create and edit groups, add and remove handsets, and switch a group between one-way announcement and talkback.",
			},
			{
				permission: "paging-groups.delete",
				label: "Delete paging groups",
				description: "Remove a paging group.",
			},
		],
	},
	{
		resource: "shared-lines",
		label: "Shared lines",
		description: "Shared line appearances: one line that appears on several handsets at once, each on a button of its own, seized and held as a single resource.",
		permissions: [
			{
				permission: "shared-lines.read",
				label: "View shared lines",
				description: "Inspect shared lines, their appearances and the button order.",
			},
			{
				permission: "shared-lines.write",
				label: "Manage shared lines",
				description: "Create and edit shared lines, add and remove appearances, and set the ring, hold-recall and barge-in behaviour.",
			},
			{
				permission: "shared-lines.delete",
				label: "Delete shared lines",
				description: "Remove a shared line.",
			},
		],
	},
	{
		resource: "queues",
		label: "Queues",
		description: "Call queues, agents, tiers and live queue state.",
		permissions: [
			{
				permission: "queues.read",
				label: "View queues",
				description: "Inspect queues, strategies and tier configuration.",
			},
			{
				permission: "queues.write",
				label: "Manage queues",
				description: "Create and edit queues, announcements and overflow behaviour.",
			},
			{
				permission: "queues.delete",
				label: "Delete queues",
				description: "Remove a queue.",
			},
			{
				permission: "queues.manage-agents",
				label: "Manage agents",
				description: "Assign agents to tiers and force agent state changes.",
			},
			{
				permission: "queues.monitor",
				label: "Monitor queues",
				description: "Watch live queue and agent state on the wallboard.",
			},
			{
				permission: "queues.join",
				label: "Set agent availability",
				description: "Log any agent into or out of a queue.",
			},
			{
				permission: "queues.join.own",
				label: "Join and leave queues",
				description: "Set own agent availability in queues the user belongs to.",
			},
		],
	},
	{
		resource: "voicemail",
		label: "Voicemail",
		description: "Mailboxes, greetings, messages and message-waiting indication.",
		permissions: [
			{
				permission: "voicemail.read",
				label: "View mailboxes",
				description: "Inspect every mailbox and its configuration.",
			},
			{
				permission: "voicemail.read.own",
				label: "View own mailbox",
				description: "Inspect only mailboxes belonging to the acting user.",
			},
			{
				permission: "voicemail.write",
				label: "Manage mailboxes",
				description: "Create and edit mailboxes, greetings and delivery options.",
			},
			{
				permission: "voicemail.delete",
				label: "Delete messages",
				description: "Delete messages from any mailbox in the organization.",
			},
			{
				permission: "voicemail.delete.own",
				label: "Delete own messages",
				description: "Delete messages from own mailboxes.",
			},
			{
				permission: "voicemail.listen",
				label: "Listen to messages",
				description: "Play or download messages from any mailbox.",
			},
			{
				permission: "voicemail.listen.own",
				label: "Listen to own messages",
				description: "Play or download messages from own mailboxes.",
			},
		],
	},
	{
		resource: "conferences",
		label: "Conferences",
		description: "Conference rooms, PINs and in-conference moderation.",
		permissions: [
			{
				permission: "conferences.read",
				label: "View conferences",
				description: "Inspect rooms and their participants.",
			},
			{
				permission: "conferences.write",
				label: "Manage conferences",
				description: "Create and edit rooms, PINs and profiles.",
			},
			{
				permission: "conferences.delete",
				label: "Delete conferences",
				description: "Remove a conference room.",
			},
			{
				permission: "conferences.moderate",
				label: "Moderate live conferences",
				description: "Mute, deafen, remove or re-level a participant in a running meeting, and lock the room.",
			},
		],
	},
	{
		resource: "park-lots",
		label: "Park lots",
		description: "Call-park orbits, their slot ranges and their retrieval timeout.",
		permissions: [
			{
				permission: "park-lots.read",
				label: "View park lots",
				description: "Inspect park orbits and the slots they occupy.",
			},
			{
				permission: "park-lots.write",
				label: "Manage park lots",
				description: "Create and edit park orbits, slot ranges and timeout behaviour.",
			},
			{
				permission: "park-lots.delete",
				label: "Delete park lots",
				description: "Remove a park orbit.",
			},
		],
	},
	{
		resource: "faxes",
		label: "Fax",
		description: "Fax servers bound to a DID, their inbox and outbox, and the act of sending a fax out through the carrier.",
		permissions: [
			{
				permission: "faxes.read",
				label: "View faxes",
				description: "List fax servers and the received/sent faxes in their inbox and outbox.",
			},
			{
				permission: "faxes.write",
				label: "Manage fax servers",
				description: "Create and edit fax servers: the DID they use, the header, fax-to-email and the retry policy.",
			},
			{
				permission: "faxes.delete",
				label: "Delete faxes",
				description: "Remove a fax server, or delete a fax from its inbox or outbox.",
			},
			{
				permission: "faxes.send",
				label: "Send faxes",
				description: "Queue an outbound fax for delivery through the carrier.",
			},
		],
	},
	{
		resource: "call-flows",
		label: "Call flows",
		description: "The day/night switch: where calls go in each mode, and who may move the switch. Also gates the manual override on a time condition, which is the same act on a different table.",
		permissions: [
			{
				permission: "call-flows.read",
				label: "View call flows",
				description: "Inspect flows, their two destinations and which mode each is in.",
			},
			{
				permission: "call-flows.write",
				label: "Manage call flows",
				description: "Create and edit flows, their destinations, their number and their toggle code.",
			},
			{
				permission: "call-flows.delete",
				label: "Delete call flows",
				description: "Remove a call flow.",
			},
			{
				permission: "call-flows.toggle",
				label: "Switch between day and night",
				description: "Move a call flow between its day and night destinations, and force a time condition open or closed. The receptionist's grant: it changes where calls go right now and changes no configuration.",
			},
		],
	},
	{
		resource: "pin-sets",
		label: "Authorisation codes",
		description: "The PIN lists that gate expensive outbound routes. Codes are stored as digests and are never readable; a call detail record names which code authorised a call, never the code.",
		permissions: [
			{
				permission: "pin-sets.read",
				label: "View authorisation codes",
				description: "Inspect PIN sets, their labels and which routes they gate. The codes themselves are never returned.",
			},
			{
				permission: "pin-sets.write",
				label: "Manage authorisation codes",
				description: "Create and edit PIN sets, add and remove codes, and attach a set to an outbound route. A holder can make an expensive route dialable by everybody in the building.",
			},
			{
				permission: "pin-sets.delete",
				label: "Delete authorisation codes",
				description: "Remove a PIN set, which removes the gate from every route that named it.",
			},
		],
	},
	{
		resource: "dial-plan",
		label: "Dial-plan building blocks",
		description: "Destination aliases, audio streams, organization speed dials and the dial-by-name directory — the named things other routing points at.",
		permissions: [
			{
				permission: "dial-plan.read",
				label: "View dial-plan building blocks",
				description: "Inspect aliases, streams, speed dials and the directory.",
			},
			{
				permission: "dial-plan.write",
				label: "Manage dial-plan building blocks",
				description: "Create and edit aliases, streams, speed dials and directories. None of them reaches a carrier except through the outbound routes every destination goes through.",
			},
			{
				permission: "dial-plan.delete",
				label: "Delete dial-plan building blocks",
				description: "Remove an alias, a stream, a speed dial or a directory.",
			},
		],
	},
	{
		resource: "org-limits",
		label: "Organization limits",
		description: "Per-organization quotas on extensions, trunks, simultaneous calls and stored audio, and the usage measured against them.",
		permissions: [
			{
				permission: "org-limits.read",
				label: "View limits and usage",
				description: "See the organization's quotas and what it is using. A support tool: it is the answer to \"why did creating an extension fail\".",
			},
			{
				permission: "org-limits.write",
				label: "Change limits",
				description: "Raise or lower the organization's own quotas. Held by the owner alone until the reseller hierarchy gives this a platform-operator home.",
			},
		],
	},
	{
		resource: "calls",
		label: "Calls",
		description: "Placing calls from the platform, controlling them from an external application, and listening in on calls already in progress.",
		permissions: [
			{
				permission: "calls.originate",
				label: "Place calls",
				description: "Ring an extension and connect it to a destination — the click-to-dial button. Off-net destinations are billed to the organization.",
			},
			{
				permission: "calls.control",
				label: "Control calls programmatically",
				description: "Connect an external application to the session protocol and take control of every call the dial plan routes to it — answering, playing audio, collecting digits, recording, dialling and hanging up.",
			},
			{
				permission: "calls.supervise",
				label: "Monitor live calls",
				description: "Listen to a colleague's call in progress, whisper to them, or join the conversation. Neither party is notified. Recorded on the audit trail every time it is used.",
			},
		],
	},
	{
		resource: "recordings",
		label: "Recordings",
		description: "Call recordings, their retention policy and their media.",
		permissions: [
			{
				permission: "recordings.read",
				label: "View recordings",
				description: "List recordings across the organization.",
			},
			{
				permission: "recordings.read.own",
				label: "View own recordings",
				description: "List only recordings of calls the acting user took part in.",
			},
			{
				permission: "recordings.download",
				label: "Download recordings",
				description: "Obtain a signed URL for recorded media.",
			},
			{
				permission: "recordings.delete",
				label: "Delete recordings",
				description: "Permanently remove recorded media.",
			},
			{
				permission: "recordings.configure",
				label: "Configure recording policy",
				description: "Set always-on, on-demand, pause-and-mask and retention rules.",
			},
		],
	},
	{
		resource: "cdr",
		label: "Call detail records",
		description: "Per-leg call history and reporting exports.",
		permissions: [
			{
				permission: "cdr.read",
				label: "View call history",
				description: "Search every call detail record in the organization.",
			},
			{
				permission: "cdr.read.own",
				label: "View own call history",
				description: "Search only records for calls the acting user took part in.",
			},
			{
				permission: "cdr.export",
				label: "Export call history",
				description: "Generate CSV or scheduled reporting exports.",
			},
		],
	},
	{
		resource: "audit",
		label: "Audit log",
		description: "The append-only record of who changed the phone system, and what they changed.",
		permissions: [
			{
				permission: "audit.read",
				label: "View the audit log",
				description: "Search the organization's change history and read the before/after of each change.",
			},
		],
	},
	{
		resource: "security",
		label: "Security",
		description: "Network access control for the SIP edge, and the record of failed authentication attempts.",
		permissions: [
			{
				permission: "security.read",
				label: "View network security",
				description: "Inspect the CIDR allow and deny entries that guard registration and trunks, and read the log of refused authentication attempts.",
			},
			{
				permission: "security.write",
				label: "Manage network ACLs",
				description: "Create and edit CIDR rules. Opening a network here lets it reach the SIP authenticator.",
			},
		],
	},
	{
		resource: "webhooks",
		label: "Webhooks",
		description: "Where this organization's call events are delivered, and with what signing key.",
		permissions: [
			{
				permission: "webhooks.read",
				label: "View webhooks",
				description: "Inspect webhook endpoints, the events each one receives, and its delivery health. Signing secrets are never returned.",
			},
			{
				permission: "webhooks.write",
				label: "Manage webhooks",
				description: "Create, edit and remove webhook endpoints, and rotate their signing secrets. An endpoint receives a copy of every event it subscribes to.",
			},
		],
	},
	{
		resource: "branding",
		label: "Branding",
		description: "White-label appearance: product name, logo, colours, support address and custom domain.",
		permissions: [
			{
				permission: "branding.write",
				label: "Manage branding",
				description: "Set the organization's product name, logo, colours, support email and custom domain. A reseller's own branding is the default its child organizations inherit.",
			},
		],
	},
	{
		resource: "reseller",
		label: "Reseller",
		description: "Administering the child organizations under a reseller: listing, provisioning, suspending and aggregate usage. Active only for organizations the platform has flagged as resellers.",
		permissions: [
			{
				permission: "reseller.read",
				label: "View child organizations",
				description: "List the organizations under this reseller and their aggregate usage.",
			},
			{
				permission: "reseller.write",
				label: "Manage child organizations",
				description: "Create a child organization, suspend or reinstate one, and set the reseller relationship.",
			},
		],
	},
	{
		resource: "sso",
		label: "Single sign-on",
		description: "The organization's SSO identity providers and how members sign in through them.",
		permissions: [
			{
				permission: "sso.configure",
				label: "Configure SSO",
				description: "Add, edit and remove the organization's OIDC identity providers. Client secrets are never returned.",
			},
		],
	},
	{
		resource: "settings",
		label: "Settings",
		description: "The organization settings cascade and platform defaults.",
		permissions: [
			{
				permission: "settings.read",
				label: "View settings",
				description: "Read organization settings and their effective values.",
			},
			{
				permission: "settings.write",
				label: "Manage settings",
				description: "Override organization-level settings.",
			},
			{
				permission: "settings.read.own",
				label: "View own preferences",
				description: "Read the acting user's own overrides of the organization's settings.",
			},
			{
				permission: "settings.write.own",
				label: "Edit own preferences",
				description: "Set or clear the acting user's own overrides. Only settings the catalogue marks user-scoped can be overridden, and only for the acting user.",
			},
			{
				permission: "settings.write.all",
				label: "Manage platform defaults",
				description: "Change defaults that apply to every organization. Platform operators only.",
			},
		],
	},
	{
		resource: "members",
		label: "Members",
		description: "Organization membership, invitations and role assignment.",
		permissions: [
			{
				permission: "members.read",
				label: "View members",
				description: "List members and pending invitations.",
			},
			{
				permission: "members.invite",
				label: "Invite members",
				description: "Send and resend organization invitations.",
			},
			{
				permission: "members.update-role",
				label: "Change member roles",
				description: "Move a member between roles.",
			},
			{
				permission: "members.remove",
				label: "Remove members",
				description: "Revoke a member's access to the organization.",
			},
		],
	},
	{
		resource: "api-keys",
		label: "API keys",
		description: "Programmatic credentials scoped to the organization.",
		permissions: [
			{
				permission: "api-keys.read",
				label: "View API keys",
				description: "List every API key issued for the organization.",
			},
			{
				permission: "api-keys.read.own",
				label: "View own API keys",
				description: "List only keys the acting user created.",
			},
			{
				permission: "api-keys.write",
				label: "Create API keys",
				description: "Issue keys with any permission subset the issuer holds.",
			},
			{
				permission: "api-keys.write.own",
				label: "Create own API keys",
				description: "Issue personal keys limited to the acting user's own permissions.",
			},
			{
				permission: "api-keys.revoke",
				label: "Revoke API keys",
				description: "Disable or delete an issued key.",
			},
		],
	},
	{
		resource: "provisioning",
		label: "Provisioning",
		description: "Device configuration templates and the authenticated provisioning endpoint.",
		permissions: [
			{
				permission: "provisioning.read",
				label: "View provisioning",
				description: "Inspect vendor catalogues and rendered device configuration.",
			},
			{
				permission: "provisioning.write",
				label: "Manage provisioning",
				description: "Edit provisioning settings and device profiles.",
			},
			{
				permission: "provisioning.tokens",
				label: "Manage provisioning tokens",
				description: "Issue and revoke the per-device tokens that authenticate config pulls.",
			},
		],
	},
];

export const SYSTEM_ROLE_IDS = [
	"owner",
	"admin",
	"manager",
	"user",
	"agent",
] as const;

export type SystemRoleId = (typeof SYSTEM_ROLE_IDS)[number];

/** The better-auth organization membership roles a template can be stored as. */
export type OrganizationMembershipRole = "owner" | "admin" | "member";

export interface SystemRoleTemplate {
	readonly id: SystemRoleId;
	readonly label: string;
	readonly description: string;
	readonly membershipRole: OrganizationMembershipRole;
	readonly permissions: readonly Permission[];
}

export const SYSTEM_ROLE_TEMPLATES: readonly SystemRoleTemplate[] = [
	{
		id: "owner",
		label: "Owner",
		description: "Full control of the organization, including billing-adjacent settings and secrets. Cannot be removed by other members.",
		membershipRole: "owner",
		permissions: [
			"extensions.read",
			"extensions.read.own",
			"extensions.write",
			"extensions.write.own",
			"extensions.delete",
			"extensions.assign",
			"devices.read",
			"devices.read.own",
			"devices.write",
			"devices.delete",
			"numbers.read",
			"numbers.write",
			"numbers.order",
			"numbers.delete",
			"numbers.assign",
			"numbers.emergency",
			"trunks.read",
			"trunks.write",
			"trunks.delete",
			"routes.read",
			"routes.write",
			"routes.delete",
			"routes.publish",
			"routes.simulate",
			"time-conditions.read",
			"time-conditions.write",
			"time-conditions.delete",
			"feature-codes.read",
			"feature-codes.write",
			"feature-codes.delete",
			"call-block.read",
			"call-block.write",
			"call-block.delete",
			"ivr.read",
			"ivr.write",
			"ivr.delete",
			"ivr.publish",
			"ring-groups.read",
			"ring-groups.write",
			"ring-groups.delete",
			"paging-groups.read",
			"paging-groups.write",
			"paging-groups.delete",
			"shared-lines.read",
			"shared-lines.write",
			"shared-lines.delete",
			"queues.read",
			"queues.write",
			"queues.delete",
			"queues.manage-agents",
			"queues.monitor",
			"queues.join",
			"queues.join.own",
			"voicemail.read",
			"voicemail.read.own",
			"voicemail.write",
			"voicemail.delete",
			"voicemail.delete.own",
			"voicemail.listen",
			"voicemail.listen.own",
			"conferences.read",
			"conferences.write",
			"conferences.delete",
			"conferences.moderate",
			"park-lots.read",
			"park-lots.write",
			"park-lots.delete",
			"faxes.read",
			"faxes.write",
			"faxes.delete",
			"faxes.send",
			"call-flows.read",
			"call-flows.write",
			"call-flows.delete",
			"call-flows.toggle",
			"pin-sets.read",
			"pin-sets.write",
			"pin-sets.delete",
			"dial-plan.read",
			"dial-plan.write",
			"dial-plan.delete",
			"org-limits.read",
			"org-limits.write",
			"calls.originate",
			"calls.control",
			"calls.supervise",
			"recordings.read",
			"recordings.read.own",
			"recordings.download",
			"recordings.delete",
			"recordings.configure",
			"cdr.read",
			"cdr.read.own",
			"cdr.export",
			"audit.read",
			"security.read",
			"security.write",
			"webhooks.read",
			"webhooks.write",
			"branding.write",
			"settings.read",
			"settings.write",
			"settings.read.own",
			"settings.write.own",
			"settings.write.all",
			"members.read",
			"members.invite",
			"members.update-role",
			"members.remove",
			"api-keys.read",
			"api-keys.read.own",
			"api-keys.write",
			"api-keys.write.own",
			"api-keys.revoke",
			"provisioning.read",
			"provisioning.write",
			"provisioning.tokens",
			"reseller.read",
			"reseller.write",
			"sso.configure",
		],
	},
	{
		id: "admin",
		label: "Administrator",
		description: "Full control of the organization's telephony, members and credentials. Cannot change platform-wide defaults.",
		membershipRole: "admin",
		permissions: [
			"extensions.read",
			"extensions.read.own",
			"extensions.write",
			"extensions.write.own",
			"extensions.delete",
			"extensions.assign",
			"devices.read",
			"devices.read.own",
			"devices.write",
			"devices.delete",
			"numbers.read",
			"numbers.write",
			"numbers.order",
			"numbers.delete",
			"numbers.assign",
			"numbers.emergency",
			"trunks.read",
			"trunks.write",
			"trunks.delete",
			"routes.read",
			"routes.write",
			"routes.delete",
			"routes.publish",
			"routes.simulate",
			"time-conditions.read",
			"time-conditions.write",
			"time-conditions.delete",
			"feature-codes.read",
			"feature-codes.write",
			"feature-codes.delete",
			"call-block.read",
			"call-block.write",
			"call-block.delete",
			"ivr.read",
			"ivr.write",
			"ivr.delete",
			"ivr.publish",
			"ring-groups.read",
			"ring-groups.write",
			"ring-groups.delete",
			"paging-groups.read",
			"paging-groups.write",
			"paging-groups.delete",
			"shared-lines.read",
			"shared-lines.write",
			"shared-lines.delete",
			"queues.read",
			"queues.write",
			"queues.delete",
			"queues.manage-agents",
			"queues.monitor",
			"queues.join",
			"queues.join.own",
			"voicemail.read",
			"voicemail.read.own",
			"voicemail.write",
			"voicemail.delete",
			"voicemail.delete.own",
			"voicemail.listen",
			"voicemail.listen.own",
			"conferences.read",
			"conferences.write",
			"conferences.delete",
			"conferences.moderate",
			"park-lots.read",
			"park-lots.write",
			"park-lots.delete",
			"faxes.read",
			"faxes.write",
			"faxes.delete",
			"faxes.send",
			"call-flows.read",
			"call-flows.write",
			"call-flows.delete",
			"call-flows.toggle",
			"pin-sets.read",
			"pin-sets.write",
			"pin-sets.delete",
			"dial-plan.read",
			"dial-plan.write",
			"dial-plan.delete",
			"org-limits.read",
			"calls.originate",
			"calls.control",
			"calls.supervise",
			"recordings.read",
			"recordings.read.own",
			"recordings.download",
			"recordings.delete",
			"recordings.configure",
			"cdr.read",
			"cdr.read.own",
			"cdr.export",
			"audit.read",
			"security.read",
			"security.write",
			"webhooks.read",
			"webhooks.write",
			"branding.write",
			"settings.read",
			"settings.write",
			"settings.read.own",
			"settings.write.own",
			"members.read",
			"members.invite",
			"members.update-role",
			"members.remove",
			"api-keys.read",
			"api-keys.read.own",
			"api-keys.write",
			"api-keys.write.own",
			"api-keys.revoke",
			"provisioning.read",
			"provisioning.write",
			"provisioning.tokens",
			"reseller.read",
			"reseller.write",
			"sso.configure",
		],
	},
	{
		id: "manager",
		label: "Manager",
		description: "Runs the day-to-day phone system: extensions, devices, menus, groups, queues and reporting. No carrier, secret or provisioning-credential access.",
		membershipRole: "member",
		permissions: [
			"extensions.read.own",
			"extensions.write.own",
			"devices.read.own",
			"voicemail.read.own",
			"voicemail.delete.own",
			"voicemail.listen.own",
			"recordings.read.own",
			"cdr.read.own",
			"api-keys.read.own",
			"api-keys.write.own",
			"settings.read",
			"settings.read.own",
			"settings.write.own",
			"queues.read",
			"queues.join.own",
			"queues.monitor",
			"conferences.read",
			"park-lots.read",
			"paging-groups.read",
			"call-flows.read",
			"extensions.read",
			"extensions.write",
			"extensions.assign",
			"devices.read",
			"devices.write",
			"numbers.read",
			"numbers.assign",
			"routes.read",
			"routes.simulate",
			"time-conditions.read",
			"time-conditions.write",
			"feature-codes.read",
			"feature-codes.write",
			"call-block.read",
			"call-block.write",
			"ivr.read",
			"ivr.write",
			"ivr.publish",
			"ring-groups.read",
			"ring-groups.write",
			"paging-groups.write",
			"call-flows.toggle",
			"call-flows.write",
			"dial-plan.read",
			"dial-plan.write",
			"pin-sets.read",
			"org-limits.read",
			"queues.write",
			"queues.manage-agents",
			"voicemail.read",
			"voicemail.write",
			"voicemail.listen",
			"conferences.write",
			"conferences.moderate",
			"park-lots.write",
			"faxes.read",
			"faxes.write",
			"faxes.send",
			"recordings.read",
			"recordings.download",
			"cdr.read",
			"cdr.export",
			"calls.originate",
			"calls.supervise",
			"members.read",
			"provisioning.read",
			"provisioning.write",
		],
	},
	{
		id: "agent",
		label: "Agent",
		description: "A queue agent: manages their own extension and voicemail and controls their own queue availability.",
		membershipRole: "member",
		permissions: [
			"extensions.read.own",
			"extensions.write.own",
			"devices.read.own",
			"voicemail.read.own",
			"voicemail.delete.own",
			"voicemail.listen.own",
			"recordings.read.own",
			"cdr.read.own",
			"api-keys.read.own",
			"api-keys.write.own",
			"settings.read",
			"settings.read.own",
			"settings.write.own",
			"queues.read",
			"queues.join.own",
			"queues.monitor",
			"conferences.read",
			"park-lots.read",
			"paging-groups.read",
			"call-flows.read",
		],
	},
	{
		id: "user",
		label: "User",
		description: "An end user with access to their own extension, voicemail, devices and calls.",
		membershipRole: "member",
		permissions: [
			"extensions.read.own",
			"extensions.write.own",
			"devices.read.own",
			"voicemail.read.own",
			"voicemail.delete.own",
			"voicemail.listen.own",
			"recordings.read.own",
			"cdr.read.own",
			"api-keys.read.own",
			"api-keys.write.own",
			"settings.read",
			"settings.read.own",
			"settings.write.own",
		],
	},
];
