import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";

/**
 * Zod validation schema for the Create/Edit ACL form.
 *
 * This schema defines the expected structure and validation rules for creating or
 * updating an ACL (Access Control List) record. It ensures that:
 * - Each ACL has an optional reference ID.
 * - A human-friendly name is required.
 * - The allow and deny lists are arrays of permission objects (with a required name).
 * - Each permission list can contain a maximum of 10 entries.
 */
export const schema = z.object({
	/**
	 * Unique identifier for the ACL.
	 *
	 * Optional; this is typically generated by the system or provided during updates.
	 */
	ref: z.string().nullish(),

	/**
	 * Human-friendly name for the ACL.
	 *
	 * Required; must not be empty.
	 */
	name: z.string().nonempty("Friendly Name is required"),

	/**
	 * Array of permissions that allow actions.
	 *
	 * Each permission must have a name and a type (allow).
	 * The array can contain up to 10 permissions.
	 */
	rules: z
		.array(
			z.object({
				name: z.string().nonempty("Permission name is required"),
				type: z.enum(["allow", "deny"]),
			}),
		)
		.nonempty("At least one permission is required")
		.max(20, "You can only add up to 20 permissions"),
});

/**
 * Type representing the validated data structure returned by the schema.
 *
 * This type is useful for typing the form state, handlers, and submissions.
 */
export type Schema = z.infer<typeof schema>;
