#!/usr/bin/env bash
#
# Generates a DEVELOPMENT-ONLY certificate authority and the two server certificates issued under
# it: the NATS broker's, and the media server's SIP-TLS leaf.
#
#   ./config/certs/generate-dev-certs.sh
#
# Output (all gitignored — see config/certs/.gitignore):
#
#   config/certs/ca.pem            the CA certificate; what CLIENTS trust (NATS_TLS_CA)
#   config/certs/ca-key.pem        the CA private key; only this script needs it
#   config/certs/server.pem        the broker's leaf certificate (config/nats-tls.conf)
#   config/certs/server-key.pem    the broker's private key
#   config/certs/asterisk.pem      the SIP-TLS leaf (apps/asterisk/config/pjsip_tls.conf)
#   config/certs/asterisk-key.pem  the SIP-TLS private key
#
# WHY TWO LEAVES AND NOT ONE
# --------------------------
# Because the SAN lists genuinely differ, and a SAN list is the whole content of a leaf. A NATS
# client reaches the broker as `nats` / `localhost` / `127.0.0.1`; a SIP phone reaches the media
# server as `asterisk` from inside the compose network and as the host's LAN address from a
# handset on the desk, and a softphone that cannot match the name it dialled against the SAN
# refuses the registration with no useful diagnostic. One certificate carrying both sets would work
# and would teach the wrong shape: in production these are two hosts with two certificates, often
# from two issuers (the SIP leaf is frequently a public one, because phones ship a public trust
# store and cannot be given a private CA without a provisioning step).
#
# WHY A PRIVATE CA AND NOT A SELF-SIGNED LEAF
# -------------------------------------------
# A client that pins a self-signed leaf has to be reissued every time the leaf is. With a CA the
# leaf can be regenerated (new SANs, new expiry) and every client keeps working, because what they
# trust is `ca.pem`. That is also how a real deployment is shaped, so the client wiring exercised
# here — `NATS_TLS_CA` pointing at a CA bundle — is the wiring production uses.
#
# WHY THE SANs ARE WHAT THEY ARE
# ------------------------------
# Go's and Node's TLS stacks both verify the hostname against the SUBJECT ALTERNATIVE NAME, never
# the CN. The broker is reached under three different names depending on who is calling:
#
#   nats          from inside the compose network (the service name)
#   localhost     from a host-side process — `pnpm start:api`, the engine in watch mode, a script
#   127.0.0.1     the same, when something resolves the literal instead
#
# plus whatever `DOCKER_HOST_ADDRESS` is set to, because the asterisk service reaches back to the
# host by LAN IP and a developer may point a service at the same address. All four go in, so one
# certificate serves every path and nobody has to disable verification to get a connection.
#
# NOT FOR PRODUCTION. The key has no passphrase, the CA is trusted by nothing outside this
# checkout, and the material is regenerated by anybody who runs this script.

set -euo pipefail

CERT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Long enough that a developer is not regenerating certificates during a feature, short enough that
# a leaked development key is not useful for a decade.
DAYS="${NATS_DEV_CERT_DAYS:-825}"

# The extra name a developer can add without editing this file: the host's LAN address, which is
# what compose.dev.yaml already passes to the asterisk service as DOCKER_HOST_ADDRESS.
EXTRA_IP="${DOCKER_HOST_ADDRESS:-}"

command -v openssl >/dev/null 2>&1 || {
	echo "openssl not found on PATH" >&2
	exit 1
}

cd "$CERT_DIR"

echo "==> generating development CA (${DAYS} days)"
openssl req -x509 -newkey rsa:2048 -sha256 -days "$DAYS" -nodes \
	-keyout ca-key.pem -out ca.pem \
	-subj "/O=Optimiq Voice/OU=Development/CN=Optimiq Voice Development CA" \
	-addext "basicConstraints=critical,CA:TRUE,pathlen:0" \
	-addext "keyUsage=critical,keyCertSign,cRLSign" \
	2>/dev/null

# The leaf's SAN list, assembled here rather than in a static openssl.cnf so DOCKER_HOST_ADDRESS
# can join it without a second template file.
SAN="DNS:nats,DNS:localhost,DNS:nats.optimiq.local,IP:127.0.0.1,IP:0.0.0.0"
if [ -n "$EXTRA_IP" ]; then
	SAN="${SAN},IP:${EXTRA_IP}"
	echo "==> including DOCKER_HOST_ADDRESS=${EXTRA_IP} in the SAN list"
fi

echo "==> generating broker key and CSR"
openssl req -newkey rsa:2048 -sha256 -nodes \
	-keyout server-key.pem -out server.csr \
	-subj "/O=Optimiq Voice/OU=Development/CN=nats" \
	2>/dev/null

echo "==> signing broker certificate for ${SAN}"
openssl x509 -req -in server.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial \
	-out server.pem -days "$DAYS" -sha256 \
	-extfile <(printf 'subjectAltName=%s\nextendedKeyUsage=serverAuth,clientAuth\nbasicConstraints=critical,CA:FALSE\n' "$SAN") \
	2>/dev/null

rm -f server.csr ca.srl

# The media server's SIP-TLS leaf.
#
# `asterisk` is the compose service name and the host part of every in-network SIP URI; the LAN
# address matters more here than it does for the broker, because the thing that dials it is a
# physical handset or a softphone on the developer's machine, and neither resolves compose service
# names. `localhost` is in for a host-side `openssl s_client` handshake check.
SIP_SAN="DNS:asterisk,DNS:localhost,DNS:asterisk.optimiq.local,IP:127.0.0.1"
if [ -n "$EXTRA_IP" ]; then
	SIP_SAN="${SIP_SAN},IP:${EXTRA_IP}"
fi

echo "==> generating media-server key and CSR"
openssl req -newkey rsa:2048 -sha256 -nodes \
	-keyout asterisk-key.pem -out asterisk.csr \
	-subj "/O=Optimiq Voice/OU=Development/CN=asterisk" \
	2>/dev/null

echo "==> signing media-server certificate for ${SIP_SAN}"
openssl x509 -req -in asterisk.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial \
	-out asterisk.pem -days "$DAYS" -sha256 \
	-extfile <(printf 'subjectAltName=%s\nextendedKeyUsage=serverAuth,clientAuth\nbasicConstraints=critical,CA:FALSE\n' "$SIP_SAN") \
	2>/dev/null

rm -f asterisk.csr ca.srl

# The broker runs as a non-root user inside the nats image and only ever READS these.
chmod 644 ca.pem server.pem
chmod 600 ca-key.pem server-key.pem

# The SIP key is 644, and that is a deliberate exception rather than an oversight.
#
# The asterisk container runs as the unprivileged `asterisk` user (see apps/asterisk/Dockerfile),
# and this directory reaches it as a read-only bind mount whose ownership is the HOST's. A 600 key
# owned by the developer is therefore unreadable inside the container, and the symptom is a
# transport that fails to load with a pjproject error rather than anything that names a permission.
# The broker's key stays 600 because the nats image's uid mapping does not have that problem.
#
# What makes this acceptable is what the header already says about every file here: this is
# development material, the key has no passphrase, it is trusted by nothing outside this checkout,
# and it is regenerated by anybody who runs this script. Production SIP-TLS material is an operator
# mount of files this script never touches.
chmod 644 asterisk.pem asterisk-key.pem

echo
echo "==> done. Written to ${CERT_DIR}:"
openssl x509 -in server.pem -noout -subject -issuer -enddate -ext subjectAltName |
	sed 's/^/    /'
openssl x509 -in asterisk.pem -noout -subject -issuer -enddate -ext subjectAltName |
	sed 's/^/    /'
echo
echo "Bring the broker up with TLS:"
echo
echo "    docker compose -f compose.yaml -f compose.dev.yaml -f compose.tls.yaml up nats -d"
echo
echo "and point clients at it:"
echo
echo "    NATS_URL=tls://localhost:4222"
echo "    NATS_TLS_CA=$(pwd)/ca.pem"
echo
echo "The same overlay turns on SIP-TLS and SDES-SRTP on the media server:"
echo
echo "    docker compose -f compose.yaml -f compose.dev.yaml -f compose.tls.yaml up asterisk -d"
echo "    openssl s_client -connect localhost:5061 -servername asterisk -CAfile $(pwd)/ca.pem"
