import { z } from "zod";
import { subjectFor } from "../subjects";
import { defineEvent, makeEvent, type EventInput } from "./envelope";
import {
	callDirectionSchema,
	destinationTypeSchema,
	dialStringSchema,
	dispositionSchema,
	hangupCauseCodeSchema,
	hangupCauseSchema,
	hangupSideSchema,
	legSideSchema,
} from "./telephony";

/**
 * CDR leg writes — `cdr.leg.v1.<orgId>`.
 *
 * One message per finished channel leg, consumed durably by the CDR writer, which inserts into
 * `cdr-db` `call_legs`. "Replay = rebuild": the whole CDR table can be reconstructed from this
 * stream, which is why `CDR` is the one event stream that refuses writes rather than discarding
 * old ones (see `streams.ts`).
 *
 * ## Why the payload is LOOSE
 *
 * `call_legs` has ~40 columns and grows with every PBX feature (queue refs, conference refs,
 * media stats). If this schema were strict, every new column would need an `events` release
 * ordered before the `cdr-db` release, and a producer running ahead would have its rows silently
 * truncated. Instead the contract pins the CORE — the columns the reporting API, billing and
 * retention actually key off — and passes everything else through untouched with
 * `z.looseObject`. `cdr-db` remains the authority on the column list and on the value domains
 * (`hangupCause`, `destinationType`, `disposition`); see `telephony.ts` for that split.
 *
 * `organizationId` is intentionally NOT in the payload: it is the subject token and the envelope
 * `orgId`, and a third copy is a third thing that can disagree.
 */

/** The `cdr.leg.write` payload: pinned core plus passthrough. */
export const cdrLegWriteDataSchema = z.looseObject({
	// --- identity -----------------------------------------------------------------------------
	/** `call_legs.id`, UUID v7, generated by the engine — the idempotency key for the insert. */
	id: z.uuidv7(),
	/** Correlates every leg of one logical call. */
	callId: z.uuid(),
	leg: legSideSchema,
	originatingLegId: z.uuid().nullish(),
	bridgeLegId: z.uuid().nullish(),

	// --- who / where --------------------------------------------------------------------------
	direction: callDirectionSchema,
	fromNumber: dialStringSchema,
	fromName: z.string().max(128).nullish(),
	toNumber: dialStringSchema,
	destinationType: destinationTypeSchema,
	destinationRef: z.uuid().nullish(),

	// --- timing (partition key + billing) -------------------------------------------------------
	/** `call_legs.started_at` — the partition key. Never null, never updated. */
	startedAt: z.iso.datetime(),
	answeredAt: z.iso.datetime().nullish(),
	endedAt: z.iso.datetime().nullish(),
	durationMs: z.int().min(0),
	/** Answer → hangup. Zero on an unanswered leg. */
	billsecMs: z.int().min(0),

	// --- outcome ------------------------------------------------------------------------------
	hangupCause: hangupCauseSchema,
	hangupCauseCode: hangupCauseCodeSchema,
	hangupSide: hangupSideSchema.nullish(),
	disposition: dispositionSchema,

	// --- the queue leg ---------------------------------------------------------------------------
	/**
	 * What happened to this caller in the queue they reached, when they reached one.
	 *
	 * ## Why the ledger and not the event stream
	 *
	 * `queue.evt.v1.*` already carries every one of these facts, durably and replayably, and a
	 * wallboard reads them live. What it cannot answer is the question a supervisor asks on Monday
	 * morning: "what was our service level last week, by queue, by hour". That is an aggregate over a
	 * time window on rows that are already partitioned by time and already scoped by RLS — which is a
	 * SQL query over `call_legs`, and rebuilding one from a stream on every request would be a scan
	 * of a log with no index on any of the columns being asked about.
	 *
	 * So the queue outcome is written where every other per-call fact is written, beside the numbers,
	 * the timestamps and the disposition it will be reported alongside.
	 *
	 * ## Why all four are optional
	 *
	 * A leg that never touched a queue carries none of them, which is most legs. Optionality here is
	 * not a rollout affordance — it is the domain: `queueWaitMs` on a direct extension call would be
	 * a zero that an average would then include, and an average hold time computed over every call in
	 * the tenant is a number that is wrong in a direction nobody notices.
	 */
	queueRef: z.uuid().nullish(),
	/**
	 * How long the caller held before the queue let them go, one way or another.
	 *
	 * The SLA numerator's input, and the same value `queue.caller.answered` / `caller.abandoned`
	 * publish — deliberately, so a live wallboard and a historical report cannot disagree about what
	 * "wait" means. It is the time between joining the line and leaving it, and it excludes the
	 * agent's ring time, because a caller who was already talking to somebody was not waiting.
	 */
	queueWaitMs: z.int().min(0).nullish(),
	/**
	 * How the caller's stay ended. The DISCRIMINATOR every queue report groups by.
	 *
	 * The same vocabulary as `queue.caller.abandoned`'s `reason` plus `answered`, which is what makes
	 * the two surfaces comparable. `exit-key` stays distinct from `overflow` for the reason it does
	 * there: one caller chose to stop waiting and the other had the choice made for them, and only
	 * one of those tells a supervisor their exit key is working.
	 */
	queueOutcome: z
		.enum(["answered", "caller-hangup", "timeout", "overflow", "no-agents", "exit-key"])
		.nullish(),
	/**
	 * The `queue_agent` who took the call. Absent on every outcome except `answered`.
	 *
	 * A queue-agent row id, not a user id: `cdr-db` holds no user ids at all and this does not change
	 * that. An agent's identity is resolvable through `queue_agent` in `pbx-db` by whoever is allowed
	 * to see it, which keeps the ledger free of the one kind of identifier its access model has never
	 * had to reason about.
	 */
	queueAgentRef: z.uuid().nullish(),

	// --- the authorisation code that paid for an outbound call -----------------------------------
	/**
	 * Which code opened the gated outbound route this leg took, when it took one.
	 *
	 * ## The ordinal and the label, never the digits
	 *
	 * A PIN on an outbound route is a spending control, so the question the ledger exists to answer
	 * is "who authorised this call to Paraguay". The answer a tenant recognises is the ordinal and
	 * the label they typed into a form — "code 3, the night desk" — and that is deliberately ALL that
	 * travels: `pin_set_entry` stores a scrypt digest and never the plaintext upstream kept, and
	 * putting the code on the event stream would undo that in one field. The engine's walker is where
	 * the digits stop; everything downstream of it sees an identity.
	 *
	 * ## Why the label as well as the ordinal
	 *
	 * `cdr-db` holds no `pin_set` rows to join against — that is `pbx-db`, a different database with
	 * a different access model — so a report that had only the ordinal could say "code 3" and nothing
	 * more. Carrying the label denormalises on purpose, and the denormalisation is the point: a label
	 * that is renamed in `pbx-db` six months later must not retroactively rewrite what a call record
	 * says happened.
	 *
	 * Both absent on every call that took no gated route, which is nearly all of them. A refused code
	 * produces no leg-level field at all — the call ends `CALL_REJECTED` and the attempts are in the
	 * engine's log, because a refusal spent nothing and has no authorisation to record.
	 */
	authPinOrdinal: z.int().min(0).nullish(),
	authPinLabel: z.string().max(128).nullish(),
});

export const CDR_LEG_WRITE = defineEvent("cdr", "cdr.leg.write", cdrLegWriteDataSchema);

export const CDR_EVENT_DEFINITIONS = {
	"cdr.leg.write": CDR_LEG_WRITE,
} as const;

export type CdrLegWriteData = z.infer<typeof cdrLegWriteDataSchema>;

/** Every CDR event. A union of one today; kept as a union so adding a second is not a breaking change. */
export const cdrEventSchema = z.discriminatedUnion("type", [CDR_LEG_WRITE.envelope]);

export type CdrEventEnvelope = z.infer<typeof cdrEventSchema>;
export type CdrLegWriteEnvelope = z.infer<typeof CDR_LEG_WRITE.envelope>;

/** Builds and validates a `cdr.leg.write`, deriving `cdr.leg.v1.<orgId>`. */
export function makeCdrLegWriteEvent(
	input: Omit<EventInput<CdrLegWriteData>, "subject">,
): CdrLegWriteEnvelope {
	return makeEvent(CDR_LEG_WRITE, { ...input, subject: subjectFor.cdrLeg(input.orgId) });
}
