import { z } from "zod";
import { subjectFor } from "../subjects";
import { defineEvent, makeEvent, type EventInput } from "./envelope";
import {
	callDirectionSchema,
	destinationTypeSchema,
	dialStringSchema,
	dispositionSchema,
	hangupCauseCodeSchema,
	hangupCauseSchema,
	hangupSideSchema,
	legSideSchema,
} from "./telephony";

/**
 * CDR leg writes — `cdr.leg.v1.<orgId>`.
 *
 * One message per finished channel leg, consumed durably by the CDR writer, which inserts into
 * `cdr-db` `call_legs`. "Replay = rebuild": the whole CDR table can be reconstructed from this
 * stream, which is why `CDR` is the one event stream that refuses writes rather than discarding
 * old ones (see `streams.ts`).
 *
 * ## Why the payload is LOOSE
 *
 * `call_legs` has ~40 columns and grows with every PBX feature (queue refs, conference refs,
 * media stats). If this schema were strict, every new column would need an `events` release
 * ordered before the `cdr-db` release, and a producer running ahead would have its rows silently
 * truncated. Instead the contract pins the CORE — the columns the reporting API, billing and
 * retention actually key off — and passes everything else through untouched with
 * `z.looseObject`. `cdr-db` remains the authority on the column list and on the value domains
 * (`hangupCause`, `destinationType`, `disposition`); see `telephony.ts` for that split.
 *
 * `organizationId` is intentionally NOT in the payload: it is the subject token and the envelope
 * `orgId`, and a third copy is a third thing that can disagree.
 */

/** The `cdr.leg.write` payload: pinned core plus passthrough. */
export const cdrLegWriteDataSchema = z.looseObject({
	// --- identity -----------------------------------------------------------------------------
	/** `call_legs.id`, UUID v7, generated by the engine — the idempotency key for the insert. */
	id: z.uuidv7(),
	/** Correlates every leg of one logical call. */
	callId: z.uuid(),
	leg: legSideSchema,
	originatingLegId: z.uuid().nullish(),
	bridgeLegId: z.uuid().nullish(),

	// --- who / where --------------------------------------------------------------------------
	direction: callDirectionSchema,
	fromNumber: dialStringSchema,
	fromName: z.string().max(128).nullish(),
	toNumber: dialStringSchema,
	destinationType: destinationTypeSchema,
	destinationRef: z.uuid().nullish(),

	// --- timing (partition key + billing) -------------------------------------------------------
	/** `call_legs.started_at` — the partition key. Never null, never updated. */
	startedAt: z.iso.datetime(),
	answeredAt: z.iso.datetime().nullish(),
	endedAt: z.iso.datetime().nullish(),
	durationMs: z.int().min(0),
	/** Answer → hangup. Zero on an unanswered leg. */
	billsecMs: z.int().min(0),

	// --- outcome ------------------------------------------------------------------------------
	hangupCause: hangupCauseSchema,
	hangupCauseCode: hangupCauseCodeSchema,
	hangupSide: hangupSideSchema.nullish(),
	disposition: dispositionSchema,
});

export const CDR_LEG_WRITE = defineEvent("cdr", "cdr.leg.write", cdrLegWriteDataSchema);

export const CDR_EVENT_DEFINITIONS = {
	"cdr.leg.write": CDR_LEG_WRITE,
} as const;

export type CdrLegWriteData = z.infer<typeof cdrLegWriteDataSchema>;

/** Every CDR event. A union of one today; kept as a union so adding a second is not a breaking change. */
export const cdrEventSchema = z.discriminatedUnion("type", [CDR_LEG_WRITE.envelope]);

export type CdrEventEnvelope = z.infer<typeof cdrEventSchema>;
export type CdrLegWriteEnvelope = z.infer<typeof CDR_LEG_WRITE.envelope>;

/** Builds and validates a `cdr.leg.write`, deriving `cdr.leg.v1.<orgId>`. */
export function makeCdrLegWriteEvent(
	input: Omit<EventInput<CdrLegWriteData>, "subject">,
): CdrLegWriteEnvelope {
	return makeEvent(CDR_LEG_WRITE, { ...input, subject: subjectFor.cdrLeg(input.orgId) });
}
