/**
 * Zod contracts for every subject on the NATS backbone.
 *
 * These schemas are the SINGLE SOURCE OF TRUTH for the wire format. The inferred TypeScript types
 * are derived from them, and the Go structs in `packages/events-go` are generated from them.
 *
 * ## Cross-language codegen (live — see `scripts/generate-go.ts`)
 *
 * `pnpm --filter @optimiq-voice/events codegen` walks the explicit registry in
 * `scripts/registry.ts`, emits JSON Schema (draft-2020-12, zod 4 `z.toJSONSchema`) into
 * `schema/`, and generates `packages/events-go/*_gen.go` plus the parity golden
 * (`testdata/parity.json`) that the Go tests byte-compare against the live TS implementation.
 * `pnpm --filter @optimiq-voice/events codegen:check` is the CI drift gate: a schema change that
 * forgets codegen fails the build, which is the whole point of "no untyped publishes".
 *
 * Adding or changing a schema therefore means: edit here, register it in `scripts/registry.ts`
 * if new, run `codegen`, and commit the regenerated `schema/` + `packages/events-go` output.
 *
 * The emitted JSON Schema stays in the repo: it is the artifact the drift check compares, and it
 * documents the contract for anyone who cannot run TypeScript.
 */

export {
	ABSENT_AGENT_STATUS,
	AGENT_SESSION_ACTION_SOURCES,
	AGENT_SESSION_ACTION_TARGET,
	AGENT_SESSION_ACTIONS,
	AGENT_STATUS_VALUES,
	AGENT_TRANSITION_REFUSALS,
	API_DRIVEN_TRANSITIONS,
	assertApiAgentTransition,
	assertEngineAgentTransition,
	canAgentTransition,
	ENGINE_DRIVEN_TRANSITIONS,
	InvalidAgentTransitionError,
	isApiDrivenTransition,
	isEngineDrivenTransition,
	planAgentSessionAction,
	VALID_AGENT_TRANSITIONS,
	type AgentSessionAction,
	type AgentSessionPlan,
	type AgentTransition,
	type AgentTransitionRefusal,
} from "./agent-state-machine";
export {
	auditActorSchema,
	auditChangeSchema,
	AUDIT_EVENT_DEFINITIONS,
	AUDIT_RECORDED,
	auditEventSchema,
	auditRecordedDataSchema,
	auditResourceSchema,
	makeAuditEvent,
	type AuditEventEnvelope,
	type AuditRecordedData,
	type AuditRecordedEnvelope,
} from "./audit-events";
export {
	CALL_EVENT_DEFINITIONS,
	callEventSchema,
	callParkedDataSchema,
	callPickedUpDataSchema,
	callTransferredDataSchema,
	callUnparkedDataSchema,
	channelAnsweredDataSchema,
	channelBridgedDataSchema,
	channelCreatedDataSchema,
	channelDestroyedDataSchema,
	channelDtmfDataSchema,
	channelEarlyMediaDataSchema,
	channelHangupDataSchema,
	channelHeldDataSchema,
	channelRecordStartedDataSchema,
	channelRecordStoppedDataSchema,
	channelRingingDataSchema,
	channelUnbridgedDataSchema,
	channelUnheldDataSchema,
	makeCallEvent,
	type CallEventDataOf,
	type CallEventDefinitions,
	type CallEventEnvelope,
	type CallEventInput,
	type CallEventOf,
} from "./call-events";
export {
	CDR_EVENT_DEFINITIONS,
	CDR_LEG_WRITE,
	cdrEventSchema,
	cdrLegWriteDataSchema,
	makeCdrLegWriteEvent,
	type CdrEventEnvelope,
	type CdrLegWriteData,
	type CdrLegWriteEnvelope,
} from "./cdr-events";
export {
	baseEventEnvelopeSchema,
	defineEvent,
	entityIdSchema,
	EVENT_ENVELOPE_MAJOR,
	eventInstantSchema,
	eventSourceSchema,
	makeEvent,
	type AnyEventDefinition,
	type BaseEventEnvelope,
	type DataOf,
	type EventDefinition,
	type EventInput,
	type EventOf,
} from "./envelope";
export {
	deviceRejectedDataSchema,
	deviceRenderedDataSchema,
	deviceRequestedDataSchema,
	makeProvisionEvent,
	PROVISION_EVENT_DEFINITIONS,
	PROVISION_EVENTS,
	provisionEventSchema,
	type ProvisionEvent,
	type ProvisionEventDataOf,
	type ProvisionEventDefinitions,
	type ProvisionEventEnvelope,
	type ProvisionEventInput,
	type ProvisionEventOf,
} from "./provision-events";
export {
	claimBaseSchema,
	conferenceClaimSchema,
	isClaimExpired,
	isClaimOwnedBy,
	parkClaimSchema,
	type ConferenceClaim,
	type ParkClaim,
} from "./claims";
export {
	makeMediaEvent,
	MEDIA_EVENT_DEFINITIONS,
	MEDIA_SESSION_END_REASONS,
	mediaEventSchema,
	mediaSessionEndedDataSchema,
	mediaSessionEndReasonSchema,
	mediaSessionRtpTimeoutDataSchema,
	type MediaEventDataOf,
	type MediaEventDefinitions,
	type MediaEventEnvelope,
	type MediaEventInput,
	type MediaEventOf,
	type MediaSessionEndedData,
	type MediaSessionEndReason,
	type MediaSessionRtpTimeoutData,
} from "./media-events";
export {
	isLiveChannel,
	isRegistrationLapsed,
	LIVE_CHANNEL_DIRECTIONS,
	LIVE_CHANNEL_TEARDOWN_STATES,
	liveChannelSchema,
	mediaSessionDirectoryEntrySchema,
	registrationBindingSchema,
	type LiveChannel,
	type LiveChannelDirection,
	type LiveChannelTeardownState,
	type MediaSessionDirectoryEntry,
	type RegistrationBinding,
} from "./live-state";
export {
	makeQueueEvent,
	QUEUE_EVENT_DEFINITIONS,
	queueAgentStateDataSchema,
	queueCallerAbandonedDataSchema,
	queueCallerAnsweredDataSchema,
	queueCallerJoinedDataSchema,
	queueEventSchema,
	type QueueEventDataOf,
	type QueueEventDefinitions,
	type QueueEventEnvelope,
	type QueueEventInput,
	type QueueEventOf,
} from "./queue-events";
export {
	agentStateEntrySchema,
	QUEUE_AGENT_CONTACT_KINDS,
	queueAgentContactKindSchema,
	queueMembershipAgentSchema,
	queueMembershipSchema,
	type AgentStateEntry,
	type QueueAgentContactKind,
	type QueueMembership,
	type QueueMembershipAgent,
} from "./queue-state";
export {
	aorSchema,
	contactSchema,
	makeRegistrationEvent,
	REGISTRATION_EVENT_DEFINITIONS,
	registrationEventSchema,
	registrationExpiredDataSchema,
	registrationRegisteredDataSchema,
	registrationUnregisteredDataSchema,
	type RegistrationEventDataOf,
	type RegistrationEventDefinitions,
	type RegistrationEventEnvelope,
	type RegistrationEventInput,
	type RegistrationEventOf,
} from "./registration-events";
export {
	AUTHZ_CHECK_RPC,
	authzCheckRequestSchema,
	authzCheckResponseSchema,
	MEDIA_ALLOCATE_SESSION_RPC,
	MEDIA_BRIDGE_SESSIONS_RPC,
	MEDIA_REFUSAL_REASONS,
	MEDIA_RELEASE_SESSION_RPC,
	MEDIA_UNBRIDGE_SESSIONS_RPC,
	mediaAllocateSessionRequestSchema,
	mediaAllocateSessionResponseSchema,
	mediaBridgeSessionsRequestSchema,
	mediaBridgeSessionsResponseSchema,
	mediaCodecSchema,
	mediaRefusalReasonSchema,
	mediaReleaseSessionRequestSchema,
	mediaReleaseSessionResponseSchema,
	mediaUnbridgeSessionsRequestSchema,
	mediaUnbridgeSessionsResponseSchema,
	PARK_HANDOFF_REFUSAL_REASONS,
	PARK_HANDOFF_RPC,
	parkHandoffRefusalReasonSchema,
	parkHandoffRequestSchema,
	parkHandoffResponseSchema,
	ROUTING_RESOLVE_RPC,
	routingResolveRequestSchema,
	routingResolveResponseSchema,
	RPC_CONTRACTS,
	SIP_CREDENTIAL_RPC,
	SIP_TRANSFER_REFUSAL_REASONS,
	SIP_TRANSFER_RPC,
	sipCredentialRequestSchema,
	sipCredentialResponseSchema,
	sipTransferKindSchema,
	sipTransferRefusalReasonSchema,
	sipTransferRequestSchema,
	sipTransferResponseSchema,
	VOICEMAIL_LIST_RPC,
	voicemailListRequestSchema,
	voicemailListResponseSchema,
	voicemailMessageSummarySchema,
	type AuthzCheckRequest,
	type AuthzCheckResponse,
	type MediaAllocateSessionRequest,
	type MediaAllocateSessionResponse,
	type MediaBridgeSessionsRequest,
	type MediaBridgeSessionsResponse,
	type MediaCodec,
	type MediaRefusalReason,
	type MediaReleaseSessionRequest,
	type MediaReleaseSessionResponse,
	type MediaUnbridgeSessionsRequest,
	type MediaUnbridgeSessionsResponse,
	type ParkHandoffRefusalReason,
	type ParkHandoffRequest,
	type ParkHandoffResponse,
	type RoutingResolveRequest,
	type RoutingResolveResponse,
	type RpcContract,
	type SipCredentialRequest,
	type SipCredentialResponse,
	type SipTransferKind,
	type SipTransferRefusalReason,
	type SipTransferRequest,
	type SipTransferResponse,
	type VoicemailListRequest,
	type VoicemailListResponse,
	type VoicemailMessageSummary,
} from "./rpc";
export {
	AGENT_STATUSES,
	agentStatusSchema,
	BRIDGE_MODES,
	bridgeModeSchema,
	CALL_DIRECTIONS,
	callDirectionSchema,
	destinationTypeSchema,
	dialStringSchema,
	dispositionSchema,
	DTMF_SOURCES,
	dtmfDigitSchema,
	dtmfSourceSchema,
	HANGUP_SIDES,
	hangupCauseCodeSchema,
	hangupCauseSchema,
	hangupSideSchema,
	LEG_SIDES,
	legSideSchema,
	macAddressSchema,
	PARK_END_REASONS,
	parkEndReasonSchema,
	PICKUP_KINDS,
	pickupKindSchema,
	RECORDING_KINDS,
	RECORDING_STOP_REASONS,
	recordingKindSchema,
	recordingStopReasonSchema,
	SIP_TRANSPORTS,
	sipTransportSchema,
	TRANSFER_KINDS,
	transferKindSchema,
	type AgentStatus,
	type BridgeMode,
	type CallDirection,
	type DtmfSource,
	type HangupSide,
	type LegSide,
	type ParkEndReason,
	type PickupKind,
	type RecordingKind,
	type RecordingStopReason,
	type SipTransport,
	type TransferKind,
} from "./telephony";
export {
	makeVoicemailEvent,
	VOICEMAIL_EVENT_DEFINITIONS,
	voicemailEventSchema,
	voicemailMessageLeftDataSchema,
	voicemailMwiUpdatedDataSchema,
	type VoicemailEventDataOf,
	type VoicemailEventDefinitions,
	type VoicemailEventEnvelope,
	type VoicemailEventInput,
	type VoicemailEventOf,
	type VoicemailMessageLeftData,
	type VoicemailMwiUpdatedData,
} from "./voicemail-events";
