/**
 * Zod contracts for every subject on the NATS backbone.
 *
 * These schemas are the SINGLE SOURCE OF TRUTH for the wire format. The inferred TypeScript types
 * are derived from them, and the Go structs in `packages/events-go` are generated from them.
 *
 * ## Cross-language codegen (live — see `scripts/generate-go.ts`)
 *
 * `pnpm --filter @optimiq-voice/events codegen` walks the explicit registry in
 * `scripts/registry.ts`, emits JSON Schema (draft-2020-12, zod 4 `z.toJSONSchema`) into
 * `schema/`, and generates `packages/events-go/*_gen.go` plus the parity golden
 * (`testdata/parity.json`) that the Go tests byte-compare against the live TS implementation.
 * `pnpm --filter @optimiq-voice/events codegen:check` is the CI drift gate: a schema change that
 * forgets codegen fails the build, which is the whole point of "no untyped publishes".
 *
 * Adding or changing a schema therefore means: edit here, register it in `scripts/registry.ts`
 * if new, run `codegen`, and commit the regenerated `schema/` + `packages/events-go` output.
 *
 * The emitted JSON Schema stays in the repo: it is the artifact the drift check compares, and it
 * documents the contract for anyone who cannot run TypeScript.
 */

export {
	ABSENT_AGENT_STATUS,
	AGENT_SESSION_ACTION_SOURCES,
	AGENT_SESSION_ACTION_TARGET,
	AGENT_SESSION_ACTIONS,
	AGENT_STATUS_VALUES,
	AGENT_TRANSITION_REFUSALS,
	API_DRIVEN_TRANSITIONS,
	assertApiAgentTransition,
	assertEngineAgentTransition,
	canAgentTransition,
	ENGINE_DRIVEN_TRANSITIONS,
	InvalidAgentTransitionError,
	isApiDrivenTransition,
	isEngineDrivenTransition,
	planAgentSessionAction,
	VALID_AGENT_TRANSITIONS,
	type AgentSessionAction,
	type AgentSessionPlan,
	type AgentTransition,
	type AgentTransitionRefusal,
} from "./agent-state-machine";
export {
	auditActorSchema,
	auditChangeSchema,
	AUDIT_EVENT_DEFINITIONS,
	AUDIT_RECORDED,
	auditEventSchema,
	auditRecordedDataSchema,
	auditResourceSchema,
	makeAuditEvent,
	type AuditEventEnvelope,
	type AuditRecordedData,
	type AuditRecordedEnvelope,
} from "./audit-events";
export {
	CALL_EVENT_DEFINITIONS,
	callEventSchema,
	callPagingEndedDataSchema,
	callPagingStartedDataSchema,
	callParkedDataSchema,
	callPickedUpDataSchema,
	callTapEndedDataSchema,
	callTapStartedDataSchema,
	callTransferredDataSchema,
	callUnparkedDataSchema,
	channelAnsweredDataSchema,
	channelBridgedDataSchema,
	channelCreatedDataSchema,
	channelDestroyedDataSchema,
	channelDtmfDataSchema,
	channelEarlyMediaDataSchema,
	channelHangupDataSchema,
	channelHeldDataSchema,
	channelRecordStartedDataSchema,
	channelRecordStoppedDataSchema,
	channelRingingDataSchema,
	channelUnbridgedDataSchema,
	channelUnheldDataSchema,
	CONFERENCE_LEAVE_REASONS,
	conferenceJoinedDataSchema,
	conferenceLeaveReasonSchema,
	conferenceLeftDataSchema,
	conferenceLockChangedDataSchema,
	conferenceParticipantUpdatedDataSchema,
	makeCallEvent,
	type CallEventDataOf,
	type CallEventDefinitions,
	type CallEventEnvelope,
	type CallEventInput,
	type CallEventOf,
	type ConferenceLeaveReason,
} from "./call-events";
export {
	CDR_EVENT_DEFINITIONS,
	CDR_LEG_WRITE,
	cdrEventSchema,
	cdrLegWriteDataSchema,
	makeCdrLegWriteEvent,
	type CdrEventEnvelope,
	type CdrLegWriteData,
	type CdrLegWriteEnvelope,
} from "./cdr-events";
export {
	baseEventEnvelopeSchema,
	defineEvent,
	entityIdSchema,
	EVENT_ENVELOPE_MAJOR,
	eventInstantSchema,
	eventSourceSchema,
	makeEvent,
	type AnyEventDefinition,
	type BaseEventEnvelope,
	type DataOf,
	type EventDefinition,
	type EventInput,
	type EventOf,
} from "./envelope";
export {
	deviceRejectedDataSchema,
	deviceRenderedDataSchema,
	deviceRequestedDataSchema,
	makeProvisionEvent,
	PROVISION_EVENT_DEFINITIONS,
	PROVISION_EVENTS,
	provisionEventSchema,
	type ProvisionEvent,
	type ProvisionEventDataOf,
	type ProvisionEventDefinitions,
	type ProvisionEventEnvelope,
	type ProvisionEventInput,
	type ProvisionEventOf,
} from "./provision-events";
export {
	claimBaseSchema,
	conferenceClaimSchema,
	conferenceContributionSchema,
	isClaimExpired,
	isClaimOwnedBy,
	parkClaimSchema,
	type ConferenceClaim,
	type ConferenceContribution,
	type ParkClaim,
} from "./claims";
export {
	makeMediaEvent,
	MEDIA_EVENT_DEFINITIONS,
	MEDIA_PLAYBACK_END_REASONS,
	MEDIA_RECORDING_END_REASONS,
	MEDIA_SESSION_END_REASONS,
	mediaEventSchema,
	mediaPlaybackEndReasonSchema,
	mediaPlaybackFinishedDataSchema,
	mediaRecordingEndReasonSchema,
	mediaRecordingFinishedDataSchema,
	mediaSessionEndedDataSchema,
	mediaQualityStatsSchema,
	mediaSessionEndReasonSchema,
	mediaSessionRtpTimeoutDataSchema,
	type MediaEventDataOf,
	type MediaEventDefinitions,
	type MediaEventEnvelope,
	type MediaEventInput,
	type MediaEventOf,
	type MediaPlaybackEndReason,
	type MediaPlaybackFinishedData,
	type MediaQualityStats,
	type MediaRecordingEndReason,
	type MediaRecordingFinishedData,
	type MediaSessionEndedData,
	type MediaSessionEndReason,
	type MediaSessionRtpTimeoutData,
} from "./media-events";
export {
	contactsOf,
	extensionPresenceSchema,
	isLiveChannel,
	isRegistrationLapsed,
	isSipDialogClaimExpired,
	LIVE_CHANNEL_DIRECTIONS,
	LIVE_CHANNEL_TEARDOWN_STATES,
	liveChannelSchema,
	mediaSessionDirectoryEntrySchema,
	orphanedSipDialogClaims,
	PRESENCE_DEVICE_STATES,
	registrationBindingSchema,
	SIP_ACL_SCOPES,
	sipAclEntrySchema,
	sipDialogClaimSchema,
	trunkDirectoryEntrySchema,
	type ExtensionPresence,
	type LiveChannel,
	type LiveChannelDirection,
	type LiveChannelTeardownState,
	type MediaSessionDirectoryEntry,
	type PresenceDeviceState,
	type RegistrationBinding,
	type SipAclEntry,
	type SipAclScope,
	type SipDialogClaim,
	type TrunkDirectoryEntry,
} from "./live-state";
export {
	makeSipDialogEvent,
	SIP_DIALOG_EVENT_DEFINITIONS,
	SIP_TERMINATION_REASONS,
	sipCallIdSchema,
	sipDialogAnsweredDataSchema,
	sipDialogDtmfDataSchema,
	sipDialogEventSchema,
	sipDialogHeldDataSchema,
	sipDialogIdentitySchema,
	sipDialogProgressedDataSchema,
	sipDialogResumedDataSchema,
	sipDialogTerminatedDataSchema,
	sipTagSchema,
	sipTerminationReasonSchema,
	type SipDialogEventDataOf,
	type SipDialogEventDefinitions,
	type SipDialogEventEnvelope,
	type SipDialogEventInput,
	type SipDialogEventOf,
	type SipTerminationReason,
} from "./sip-dialog-events";
export {
	makeQueueEvent,
	QUEUE_EVENT_DEFINITIONS,
	queueAgentStateDataSchema,
	queueCallerAbandonedDataSchema,
	queueCallerAnsweredDataSchema,
	queueCallerJoinedDataSchema,
	queueEventSchema,
	type QueueEventDataOf,
	type QueueEventDefinitions,
	type QueueEventEnvelope,
	type QueueEventInput,
	type QueueEventOf,
} from "./queue-events";
export {
	agentStateEntrySchema,
	QUEUE_AGENT_CONTACT_KINDS,
	queueAgentContactKindSchema,
	queueMembershipAgentSchema,
	queueMembershipSchema,
	QUEUE_WAITING_MAX_ENTRIES,
	QUEUE_WAITING_MAX_TOMBSTONES,
	queueResumeTombstoneSchema,
	queueWaitingEntrySchema,
	queueWaitingRecordSchema,
	type AgentStateEntry,
	type QueueAgentContactKind,
	type QueueMembership,
	type QueueMembershipAgent,
	type QueueResumeTombstone,
	type QueueWaitingEntry,
	type QueueWaitingRecord,
} from "./queue-state";
export {
	aorSchema,
	contactSchema,
	makeRegistrationEvent,
	REGISTRATION_EVENT_DEFINITIONS,
	registrationEventSchema,
	registrationExpiredDataSchema,
	registrationRegisteredDataSchema,
	registrationUnregisteredDataSchema,
	type RegistrationEventDataOf,
	type RegistrationEventDefinitions,
	type RegistrationEventEnvelope,
	type RegistrationEventInput,
	type RegistrationEventOf,
} from "./registration-events";
export {
	AUTHZ_CHECK_RPC,
	authzCheckRequestSchema,
	authzCheckResponseSchema,
	EXTENSION_FEATURE_RPC,
	extensionFeatureRequestSchema,
	extensionFeatureResponseSchema,
	extensionFeatureSchema,
	FILE_GREETING_RPC,
	fileGreetingRequestSchema,
	fileGreetingResponseSchema,
	LAST_CALLER_RPC,
	lastCallerRequestSchema,
	lastCallerResponseSchema,
	CONFERENCE_CONTROL_ACTIONS,
	CONFERENCE_CONTROL_REFUSAL_REASONS,
	CONFERENCE_CONTROL_RPC,
	CONFERENCE_ROOM_ACTIONS,
	conferenceControlActionSchema,
	conferenceControlRefusalReasonSchema,
	conferenceControlRequestSchema,
	conferenceControlResponseSchema,
	MEDIA_ALLOCATE_SESSION_RPC,
	MEDIA_BRIDGE_MAX_SESSIONS,
	MEDIA_BRIDGE_SESSIONS_RPC,
	MEDIA_DIRECTIONS,
	MEDIA_HOLD_SESSION_RPC,
	MEDIA_MUTE_SESSION_RPC,
	MEDIA_RECORDING_DIRECTIONS,
	MEDIA_REFUSAL_REASONS,
	MEDIA_RELEASE_SESSION_RPC,
	MEDIA_SEND_DTMF_RPC,
	MEDIA_START_PLAYBACK_RPC,
	MEDIA_START_RECORDING_RPC,
	MEDIA_STOP_PLAYBACK_RPC,
	MEDIA_STOP_RECORDING_RPC,
	MEDIA_TAP_SESSION_RPC,
	MEDIA_TAP_SIDES,
	MEDIA_UNBRIDGE_SESSIONS_RPC,
	MEDIA_UNTAP_SESSION_RPC,
	mediaAllocateSessionRequestSchema,
	mediaAllocateSessionResponseSchema,
	mediaBridgeSessionsRequestSchema,
	mediaBridgeSessionsResponseSchema,
	mediaCodecSchema,
	mediaDirectionSchema,
	mediaHoldSessionRequestSchema,
	mediaHoldSessionResponseSchema,
	mediaMuteSessionRequestSchema,
	mediaMuteSessionResponseSchema,
	mediaRecordingDirectionSchema,
	mediaRefusalReasonSchema,
	mediaReleaseSessionRequestSchema,
	mediaReleaseSessionResponseSchema,
	mediaSendDtmfRequestSchema,
	mediaSendDtmfResponseSchema,
	mediaStartPlaybackRequestSchema,
	mediaStartPlaybackResponseSchema,
	mediaStartRecordingRequestSchema,
	mediaStartRecordingResponseSchema,
	mediaStopPlaybackRequestSchema,
	mediaStopPlaybackResponseSchema,
	mediaStopRecordingRequestSchema,
	mediaStopRecordingResponseSchema,
	mediaTapSessionRequestSchema,
	mediaTapSessionResponseSchema,
	mediaTapSideSchema,
	mediaUnbridgeSessionsRequestSchema,
	mediaUnbridgeSessionsResponseSchema,
	mediaUntapSessionRequestSchema,
	mediaUntapSessionResponseSchema,
	ORIGINATE_REFUSAL_REASONS,
	ORIGINATE_RPC,
	originateRefusalReasonSchema,
	originateRequestSchema,
	originateResponseSchema,
	PARK_HANDOFF_REFUSAL_REASONS,
	PARK_HANDOFF_RPC,
	parkHandoffRefusalReasonSchema,
	parkHandoffRequestSchema,
	parkHandoffResponseSchema,
	ROUTING_RESOLVE_RPC,
	routingResolveRequestSchema,
	routingResolveResponseSchema,
	RPC_CONTRACTS,
	SIP_ANSWER_RPC,
	SIP_CREDENTIAL_RPC,
	SIP_DIALOG_REFUSAL_REASONS,
	SIP_HANGUP_RPC,
	SIP_INVITE_REFUSAL_REASONS,
	SIP_INVITE_RPC,
	SIP_ORIGINATE_RPC,
	SIP_REINVITE_RPC,
	SIP_RING_RPC,
	SIP_TRANSFER_REFUSAL_REASONS,
	SIP_TRANSFER_RPC,
	sipAnswerRequestSchema,
	sipAnswerResponseSchema,
	sipAuthenticationSchema,
	sipCredentialRequestSchema,
	sipCredentialResponseSchema,
	sipDialTargetSchema,
	sipDialogRefusalReasonSchema,
	sipHangupRequestSchema,
	sipHangupResponseSchema,
	sipInviteRefusalReasonSchema,
	sipInviteRequestSchema,
	sipInviteResponseSchema,
	sipMediaHintSchema,
	sipOriginateRequestSchema,
	sipOriginateResponseSchema,
	sipPartySchema,
	sipReinviteRequestSchema,
	sipReinviteResponseSchema,
	sipReplacesSchema,
	sipRingRequestSchema,
	sipRingResponseSchema,
	sipTransferKindSchema,
	sipTransferRefusalReasonSchema,
	SESSION_ANNOUNCE_REFUSAL_REASONS,
	SESSION_ANNOUNCE_RPC,
	SESSION_VERB_REFUSAL_REASONS,
	SESSION_VERB_RPC,
	SESSION_VERBS,
	sessionAnnounceRefusalReasonSchema,
	sessionAnnounceRequestSchema,
	sessionAnnounceResponseSchema,
	sessionDialTargetSchema,
	sessionVerbArgumentsSchema,
	sessionVerbNameSchema,
	sessionVerbRefusalReasonSchema,
	sessionVerbRequestSchema,
	sessionVerbResponseSchema,
	sipTransferRequestSchema,
	sipTransferResponseSchema,
	VOICEMAIL_GREETING_KINDS,
	VOICEMAIL_LIST_RPC,
	voicemailGreetingKindSchema,
	voicemailListRequestSchema,
	voicemailListResponseSchema,
	voicemailMessageSummarySchema,
	type AuthzCheckRequest,
	type AuthzCheckResponse,
	type ConferenceControlAction,
	type ConferenceControlRefusalReason,
	type ConferenceControlRequest,
	type ConferenceControlResponse,
	type ExtensionFeature,
	type ExtensionFeatureRequest,
	type ExtensionFeatureResponse,
	type FileGreetingRequest,
	type FileGreetingResponse,
	type LastCallerRequest,
	type LastCallerResponse,
	type MediaAllocateSessionRequest,
	type MediaAllocateSessionResponse,
	type MediaBridgeSessionsRequest,
	type MediaBridgeSessionsResponse,
	type MediaCodec,
	type MediaDirection,
	type MediaHoldSessionRequest,
	type MediaHoldSessionResponse,
	type MediaMuteSessionRequest,
	type MediaMuteSessionResponse,
	type MediaRecordingDirection,
	type MediaRefusalReason,
	type MediaReleaseSessionRequest,
	type MediaReleaseSessionResponse,
	type MediaSendDtmfRequest,
	type MediaSendDtmfResponse,
	type MediaStartPlaybackRequest,
	type MediaStartPlaybackResponse,
	type MediaStartRecordingRequest,
	type MediaStartRecordingResponse,
	type MediaStopPlaybackRequest,
	type MediaStopPlaybackResponse,
	type MediaStopRecordingRequest,
	type MediaStopRecordingResponse,
	type MediaTapSessionRequest,
	type MediaTapSessionResponse,
	type MediaTapSide,
	type MediaUnbridgeSessionsRequest,
	type MediaUnbridgeSessionsResponse,
	type MediaUntapSessionRequest,
	type MediaUntapSessionResponse,
	type OriginateRefusalReason,
	type OriginateRequest,
	type OriginateResponse,
	type ParkHandoffRefusalReason,
	type ParkHandoffRequest,
	type ParkHandoffResponse,
	type RoutingResolveRequest,
	type RoutingResolveResponse,
	type RpcContract,
	type SessionAnnounceRefusalReason,
	type SessionAnnounceRequest,
	type SessionAnnounceResponse,
	type SessionDialTarget,
	type SessionVerbArguments,
	type SessionVerbName,
	type SessionVerbRefusalReason,
	type SessionVerbRequest,
	type SessionVerbResponse,
	type SipAnswerRequest,
	type SipAnswerResponse,
	type SipAuthentication,
	type SipCredentialRequest,
	type SipCredentialResponse,
	type SipDialTarget,
	type SipDialogRefusalReason,
	type SipHangupRequest,
	type SipHangupResponse,
	type SipInviteRefusalReason,
	type SipInviteRequest,
	type SipInviteResponse,
	type SipOriginateRequest,
	type SipOriginateResponse,
	type SipReinviteRequest,
	type SipReinviteResponse,
	type SipRingRequest,
	type SipRingResponse,
	type SipTransferKind,
	type SipTransferRefusalReason,
	type SipTransferRequest,
	type SipTransferResponse,
	type VoicemailGreetingKind,
	type VoicemailListRequest,
	type VoicemailListResponse,
	type VoicemailMessageSummary,
} from "./rpc";
export {
	AGENT_STATUSES,
	agentStatusSchema,
	BRIDGE_MODES,
	bridgeModeSchema,
	CALL_DIRECTIONS,
	callDirectionSchema,
	destinationTypeSchema,
	dialStringSchema,
	dispositionSchema,
	DTMF_SOURCES,
	dtmfDigitSchema,
	dtmfSourceSchema,
	HANGUP_SIDES,
	hangupCauseCodeSchema,
	hangupCauseSchema,
	hangupSideSchema,
	LEG_SIDES,
	legSideSchema,
	macAddressSchema,
	PARK_END_REASONS,
	parkEndReasonSchema,
	PICKUP_KINDS,
	pickupKindSchema,
	RECORDING_KINDS,
	RECORDING_STOP_REASONS,
	recordingKindSchema,
	recordingStopReasonSchema,
	SIP_TRANSPORTS,
	sipTransportSchema,
	TAP_END_REASONS,
	TAP_MODES,
	tapEndReasonSchema,
	tapModeSchema,
	TRANSFER_KINDS,
	transferKindSchema,
	type AgentStatus,
	type BridgeMode,
	type CallDirection,
	type DtmfSource,
	type HangupSide,
	type LegSide,
	type ParkEndReason,
	type PickupKind,
	type RecordingKind,
	type RecordingStopReason,
	type SipTransport,
	type TapEndReason,
	type TapMode,
	type TransferKind,
} from "./telephony";
export {
	makeTrunkEvent,
	TRUNK_EVENT_DEFINITIONS,
	TRUNK_STATUS_VALUES,
	trunkEventSchema,
	trunkStatusChangedDataSchema,
	trunkStatusSchema,
	type TrunkEventDataOf,
	type TrunkEventDefinitions,
	type TrunkEventEnvelope,
	type TrunkEventInput,
	type TrunkEventOf,
	type TrunkStatusChangedData,
	type TrunkStatusValue,
} from "./trunk-events";
export {
	makeVoicemailEvent,
	VOICEMAIL_EVENT_DEFINITIONS,
	voicemailEventSchema,
	voicemailMessageLeftDataSchema,
	voicemailMwiUpdatedDataSchema,
	type VoicemailEventDataOf,
	type VoicemailEventDefinitions,
	type VoicemailEventEnvelope,
	type VoicemailEventInput,
	type VoicemailEventOf,
	type VoicemailMessageLeftData,
	type VoicemailMwiUpdatedData,
} from "./voicemail-events";
