/**
 * `@optimiq-voice/routing` — the routing compiler.
 *
 * One organization's PBX configuration in, one deterministic, cacheable artifact out, plus the
 * three resolvers that turn that artifact into the plan the engine executes for a given call.
 *
 * The only runtime dependency is `@optimiq-voice/telephony`, itself dependency-free: the hangup
 * causes a failover chain keys off and the vocabulary a terminal action speaks must be the same
 * ones the engine and the CDR writer use, and a second copy of that taxonomy would be a silent
 * divergence waiting to happen.
 *
 * Derived from `plans/optimiq-voice-master-plan.md` §4.1/§4.2/§5 and
 * `plans/reference/fusionpbx-inventory.md` §2/§5; no upstream code is reproduced.
 */

export {
	contextReachesTrunks,
	isRoutingArtifact,
	isRoutingContext,
	parseRoutingArtifact,
	ROUTING_ARTIFACT_VERSION,
	ROUTING_CONTEXTS,
	type CompiledCallBlockRule,
	type CompiledRoutingSettings,
	type ExtensionIndexEntry,
	type InboundDidDefault,
	type InboundMatchTable,
	type InboundRule,
	type InternalMatchTable,
	type InternalNumberEntry,
	type MailboxEntry,
	type OutboundMatchTable,
	type OutboundRule,
	type ParkSlotRange,
	type RouteTimeGate,
	type RoutingArtifact,
	type RoutingContext,
	type VoicemailPrefixEntry,
} from "./artifact";
export {
	affectsRouting,
	canonicalizeSnapshot,
	invalidationKeysFor,
	invalidationKeysForBatch,
	isArtifactFresh,
	isRoutingEntityKind,
	ROUTING_CACHE_ARTIFACT_NAME,
	ROUTING_CACHE_BUCKET,
	ROUTING_CHANGE_OPERATIONS,
	ROUTING_ENTITY_KINDS,
	ROUTING_TABLE_TO_ENTITY,
	routingCacheKey,
	snapshotHash,
	type RoutingChangeOperation,
	type RoutingEntityKind,
	type RoutingSnapshotChange,
} from "./cache";
export { canonicalEquals, canonicalJson, type CanonicalValue } from "./canonical-json";
export {
	callBlockHangupCause,
	compileRoutingArtifact,
	tryCompileRoutingArtifact,
	type CompileOptions,
	type CompileResult,
} from "./compile";
export {
	DESTINATION_TARGET_COLLECTIONS,
	DESTINATION_TYPE_KINDS,
	DESTINATION_TYPES,
	destinationKey,
	destinationKind,
	destinationShapeIssues,
	destinationTargetCollection,
	isDestinationType,
	isEntityDestination,
	readDestination,
	readNamedDestination,
	type Destination,
	type DestinationData,
	type DestinationInput,
	type DestinationKind,
	type DestinationShapeIssue,
	type DestinationType,
} from "./destinations";
export {
	DIAGNOSTIC_CODES,
	DIAGNOSTIC_SEVERITIES,
	DiagnosticBag,
	formatDiagnostics,
	isDiagnosticCode,
	type Diagnostic,
	type DiagnosticCode,
	type DiagnosticSeverity,
	type DiagnosticSubject,
} from "./diagnostics";
export {
	PlanNodeNotFoundError,
	RoutingArtifactShapeError,
	RoutingArtifactVersionError,
	RoutingCompileError,
	RoutingError,
	RoutingSnapshotError,
} from "./errors";
export {
	DEFAULT_FEATURE_CODES,
	FEATURE_CODE_ARGUMENT_MODE,
	FEATURE_CODE_ARGUMENT_MODES,
	featureCodeIssues,
	isWellFormedFeatureCode,
	matchFeatureCode,
	type CompiledFeatureCode,
	type FeatureCodeArgumentMode,
	type FeatureCodeIssue,
	type FeatureCodeMatch,
	type FeatureCodeSeed,
} from "./feature-codes";
export {
	applyDigitManipulation,
	clearPatternCache,
	compilePattern,
	InvalidPatternError,
	MAX_PATTERN_LENGTH,
	MAX_STRIP_DIGITS,
	matchPattern,
	patternSpecificity,
	patternsOverlap,
	patternSubsumes,
	validateDigitManipulation,
	type CompiledPattern,
	type DigitManipulation,
	type DigitManipulationIssue,
	type PatternIssue,
	type PatternMatch,
} from "./patterns";
export {
	PLAN_NODE_KINDS,
	planNodeIds,
	planNodeReferences,
	reachableNodeIds,
	VOICEMAIL_MODES,
	type ApplicationPlanNode,
	type ConferencePlanNode,
	type ExecutionPlan,
	type ExtensionPlanNode,
	type ExternalPlanNode,
	type FeatureCodePlanNode,
	type HangupPlanNode,
	type IvrMenuPlanNode,
	type IvrOption,
	type ParkPlanNode,
	type PlanNode,
	type PlanNodeId,
	type PlanNodeKind,
	type PlanNodeOf,
	type PlanNodeTable,
	type PlaybackPlanNode,
	type QueuePlanNode,
	type RingGroupMember,
	type RingGroupPlanNode,
	type TimeConditionPlanNode,
	type TrunkAttempt,
	type TrunkDialPlanNode,
	type VoicemailMode,
	type VoicemailPlanNode,
} from "./plan";
export {
	checkCallBlock,
	MAX_GATE_DEPTH,
	planFrom,
	planNode,
	resolveInbound,
	resolveInternal,
	resolveOutbound,
	type BlockOutcome,
	type ResolvedRoute,
	type ResolveInboundInput,
	type ResolveInternalInput,
	type ResolveOutboundInput,
} from "./resolve";
export { sha256, sha256Bytes, utf8Bytes } from "./sha256";
export {
	CALL_BLOCK_ACTIONS,
	CALL_BLOCK_DIRECTIONS,
	CALL_BLOCK_MATCH_KINDS,
	emptySnapshot,
	FEATURE_CODE_ACTIONS,
	isOptionalSnapshotCollection,
	IVR_OPTION_MATCH_KINDS,
	OPTIONAL_SNAPSHOT_COLLECTIONS,
	QUEUE_STRATEGIES,
	RECORD_POLICIES,
	RING_GROUP_STRATEGIES,
	ROUTE_MATCH_KINDS,
	SIP_TRANSPORTS,
	SNAPSHOT_COLLECTIONS,
	snapshotCollection,
	TOLL_CLASS_RANK,
	TOLL_CLASSES,
	tollClassCovers,
	TRUNK_KINDS,
	VOICEMAIL_GREETING_KINDS,
	VOICEMAIL_LEAVE_GREETING_PRECEDENCE,
	type CallBlockAction,
	type CallBlockDirection,
	type CallBlockMatchKind,
	type CallBlockRuleInput,
	type ConferenceInput,
	type ExtensionInput,
	type FeatureCodeAction,
	type FeatureCodeInput,
	type FeatureCodeParams,
	type InboundRouteInput,
	type IvrMenuInput,
	type IvrMenuOptionInput,
	type IvrOptionMatchKind,
	type MohClassInput,
	type OptionalSnapshotCollection,
	type OrgRoutingSnapshot,
	type OutboundRouteInput,
	type ParkLotInput,
	type PhoneNumberInput,
	type QueueInput,
	type QueueStrategy,
	type RecordPolicy,
	type RingGroupDestinationInput,
	type RingGroupInput,
	type RingGroupStrategy,
	type RouteMatchKind,
	type RoutingEntityInput,
	type RoutingSettingsInput,
	type SipTransport,
	type SnapshotCollection,
	type TimeConditionInput,
	type TimeConditionRuleInput,
	type TimeRulePredicateInput,
	type TollClass,
	type TrunkInput,
	type TrunkKind,
	type TrunkPriorityInput,
	type VoicemailBoxInput,
	type VoicemailGreetingInput,
	type VoicemailGreetingKind,
} from "./snapshot";
export {
	clearTimezoneCache,
	compileTimePredicate,
	evaluateTimeCondition,
	isKnownTimezone,
	predicateMatches,
	ruleMatches,
	timeOfDayMatches,
	validateTimePredicate,
	zonedInstant,
	type CompiledTimeCondition,
	type CompiledTimePredicate,
	type CompiledTimeRule,
	type TimeConditionEvaluation,
	type TimePredicateIssue,
	type ZonedInstant,
} from "./time-conditions";
export {
	DEFAULT_VOICEMAIL_PIN_SCRYPT_PARAMS,
	DERIVED_KEY_BYTES,
	formatVoicemailPinHash,
	isVoicemailPinHash,
	MAX_BLOCK_SIZE,
	MAX_COST,
	MAX_MEMORY_BYTES,
	MAX_PARALLELISM,
	MIN_SALT_BYTES,
	parseVoicemailPinHash,
	readVoicemailPinHash,
	scryptMemoryBytes,
	VOICEMAIL_PIN_HASH_SCHEME,
	voicemailPinHashIssue,
	type ParsedVoicemailPinHash,
	type VoicemailPinHashIssue,
	type VoicemailPinScryptParams,
} from "./voicemail-pin";
