// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Payloads for the audit event family.

package events

import "encoding/json"

// Event types carried on the audit family's subjects. The value is the envelope's
// `type` discriminator, which is unique WITHIN the family only.
const (
	EventTypeAuditRecorded = "audit.recorded"
)

// AuditRecordedData is the payload of the "audit.recorded" event.
//
// Subject: audit.evt.v1.<orgId>
// Envelope: Envelope[AuditRecordedData]
type AuditRecordedData struct {
	Actor     AuditRecordedActor                   `json:"actor"`
	Action    string                               `json:"action"`
	Resource  AuditRecordedResource                `json:"resource"`
	Outcome   AuditRecordedOutcome                 `json:"outcome"`
	RequestID *string                              `json:"requestId,omitempty"`
	Changes   map[string]AuditRecordedChangesEntry `json:"changes,omitempty"`
	Reason    *string                              `json:"reason,omitempty"`
}

// AuditRecordedActor is a payload fragment of the contract.
type AuditRecordedActor struct {
	Type      AuditRecordedActorType `json:"type"`
	ID        *string                `json:"id,omitempty"`
	Label     *string                `json:"label,omitempty"`
	IP        *string                `json:"ip,omitempty"`
	UserAgent *string                `json:"userAgent,omitempty"`
}

// AuditRecordedActorType is the closed vocabulary of AuditRecordedActor.type.
type AuditRecordedActorType string

const (
	AuditRecordedActorTypeUser    AuditRecordedActorType = "user"
	AuditRecordedActorTypeAPIKey  AuditRecordedActorType = "api-key"
	AuditRecordedActorTypeService AuditRecordedActorType = "service"
	AuditRecordedActorTypeSystem  AuditRecordedActorType = "system"
)

// AuditRecordedActorTypeValues lists every member of the vocabulary, in contract order.
var AuditRecordedActorTypeValues = []AuditRecordedActorType{
	AuditRecordedActorTypeUser,
	AuditRecordedActorTypeAPIKey,
	AuditRecordedActorTypeService,
	AuditRecordedActorTypeSystem,
}

// Valid reports whether v is a member of the AuditRecordedActorType vocabulary.
func (v AuditRecordedActorType) Valid() bool {
	for _, candidate := range AuditRecordedActorTypeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v AuditRecordedActorType) String() string { return string(v) }

// AuditRecordedResource is a payload fragment of the contract.
type AuditRecordedResource struct {
	Type  string  `json:"type"`
	ID    *string `json:"id,omitempty"`
	Label *string `json:"label,omitempty"`
}

// AuditRecordedOutcome is the closed vocabulary of AuditRecordedData.outcome.
type AuditRecordedOutcome string

const (
	AuditRecordedOutcomeAllowed AuditRecordedOutcome = "allowed"
	AuditRecordedOutcomeDenied  AuditRecordedOutcome = "denied"
	AuditRecordedOutcomeFailed  AuditRecordedOutcome = "failed"
)

// AuditRecordedOutcomeValues lists every member of the vocabulary, in contract order.
var AuditRecordedOutcomeValues = []AuditRecordedOutcome{
	AuditRecordedOutcomeAllowed,
	AuditRecordedOutcomeDenied,
	AuditRecordedOutcomeFailed,
}

// Valid reports whether v is a member of the AuditRecordedOutcome vocabulary.
func (v AuditRecordedOutcome) Valid() bool {
	for _, candidate := range AuditRecordedOutcomeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v AuditRecordedOutcome) String() string { return string(v) }

// AuditRecordedChangesEntry is a payload fragment of the contract.
type AuditRecordedChangesEntry struct {
	From json.RawMessage `json:"from,omitempty"`
	To   json.RawMessage `json:"to,omitempty"`
}
