// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Payloads for the call event family.

package events

// Event types carried on the call family's subjects. The value is the envelope's
// `type` discriminator, which is unique WITHIN the family only.
const (
	EventTypeChannelCreated       = "channel.created"
	EventTypeChannelRinging       = "channel.ringing"
	EventTypeChannelEarlyMedia    = "channel.early-media"
	EventTypeChannelAnswered      = "channel.answered"
	EventTypeChannelBridged       = "channel.bridged"
	EventTypeChannelUnbridged     = "channel.unbridged"
	EventTypeChannelHeld          = "channel.held"
	EventTypeChannelUnheld        = "channel.unheld"
	EventTypeChannelDTMF          = "channel.dtmf"
	EventTypeChannelRecordStarted = "channel.record.started"
	EventTypeChannelRecordStopped = "channel.record.stopped"
	EventTypeChannelHangup        = "channel.hangup"
	EventTypeChannelDestroyed     = "channel.destroyed"
	EventTypeConferenceJoined     = "conference.joined"
	EventTypeConferenceLeft       = "conference.left"
	EventTypeCallParked           = "call.parked"
	EventTypeCallUnparked         = "call.unparked"
	EventTypeCallTransferred      = "call.transferred"
	EventTypeCallPickedUp         = "call.picked-up"
	EventTypeCallEmergencyDialed  = "call.emergency.dialed"
	EventTypeCallTapStarted       = "call.tap.started"
	EventTypeCallTapEnded         = "call.tap.ended"
	EventTypeCallPagingStarted    = "call.paging.started"
	EventTypeCallPagingEnded      = "call.paging.ended"
)

// ChannelCreatedData is the payload of the "channel.created" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.created
// Envelope: Envelope[ChannelCreatedData]
type ChannelCreatedData struct {
	LegID            string             `json:"legId"`
	Leg              LegSide            `json:"leg"`
	Direction        CallDirection      `json:"direction"`
	From             ChannelCreatedFrom `json:"from"`
	To               ChannelCreatedTo   `json:"to"`
	OriginatingLegID *string            `json:"originatingLegId,omitempty"`
	SIPCallID        *string            `json:"sipCallId,omitempty"`
	RoutingContext   *string            `json:"routingContext,omitempty"`
	RemoteAddress    *string            `json:"remoteAddress,omitempty"`
}

// ChannelCreatedFrom is a payload fragment of the contract.
type ChannelCreatedFrom struct {
	Number string  `json:"number"`
	Name   *string `json:"name,omitempty"`
}

// ChannelCreatedTo is a payload fragment of the contract.
type ChannelCreatedTo struct {
	Number string `json:"number"`
}

// ChannelRingingData is the payload of the "channel.ringing" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.ringing
// Envelope: Envelope[ChannelRingingData]
type ChannelRingingData struct {
	LegID string `json:"legId"`
}

// ChannelEarlyMediaData is the payload of the "channel.early-media" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.early-media
// Envelope: Envelope[ChannelEarlyMediaData]
type ChannelEarlyMediaData struct {
	LegID string `json:"legId"`
}

// ChannelAnsweredData is the payload of the "channel.answered" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.answered
// Envelope: Envelope[ChannelAnsweredData]
type ChannelAnsweredData struct {
	LegID string `json:"legId"`
}

// ChannelBridgedData is the payload of the "channel.bridged" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.bridged
// Envelope: Envelope[ChannelBridgedData]
type ChannelBridgedData struct {
	LegID     string     `json:"legId"`
	PeerLegID string     `json:"peerLegId"`
	BridgeID  string     `json:"bridgeId"`
	Mode      BridgeMode `json:"mode"`
}

// ChannelUnbridgedData is the payload of the "channel.unbridged" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.unbridged
// Envelope: Envelope[ChannelUnbridgedData]
type ChannelUnbridgedData struct {
	LegID     string  `json:"legId"`
	PeerLegID string  `json:"peerLegId"`
	BridgeID  string  `json:"bridgeId"`
	Reason    *string `json:"reason,omitempty"`
}

// ChannelHeldData is the payload of the "channel.held" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.held
// Envelope: Envelope[ChannelHeldData]
type ChannelHeldData struct {
	LegID    string  `json:"legId"`
	MOHClass *string `json:"mohClass,omitempty"`
}

// ChannelUnheldData is the payload of the "channel.unheld" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.unheld
// Envelope: Envelope[ChannelUnheldData]
type ChannelUnheldData struct {
	LegID string `json:"legId"`
}

// ChannelDTMFData is the payload of the "channel.dtmf" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.dtmf
// Envelope: Envelope[ChannelDTMFData]
type ChannelDTMFData struct {
	LegID      string     `json:"legId"`
	Digit      string     `json:"digit"`
	DurationMs int        `json:"durationMs"`
	Source     DTMFSource `json:"source"`
}

// ChannelRecordStartedData is the payload of the "channel.record.started" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.record.started
// Envelope: Envelope[ChannelRecordStartedData]
type ChannelRecordStartedData struct {
	LegID       string        `json:"legId"`
	RecordingID string        `json:"recordingId"`
	ObjectKey   string        `json:"objectKey"`
	Kind        RecordingKind `json:"kind"`
	Stereo      *bool         `json:"stereo,omitempty"`
}

// ChannelRecordStoppedData is the payload of the "channel.record.stopped" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.record.stopped
// Envelope: Envelope[ChannelRecordStoppedData]
type ChannelRecordStoppedData struct {
	LegID       string              `json:"legId"`
	RecordingID string              `json:"recordingId"`
	ObjectKey   string              `json:"objectKey"`
	DurationMs  int                 `json:"durationMs"`
	Reason      RecordingStopReason `json:"reason"`
	Bytes       *int                `json:"bytes,omitempty"`
}

// ChannelHangupData is the payload of the "channel.hangup" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.hangup
// Envelope: Envelope[ChannelHangupData]
type ChannelHangupData struct {
	LegID     string     `json:"legId"`
	Cause     string     `json:"cause"`
	CauseCode int        `json:"causeCode"`
	Side      HangupSide `json:"side"`
}

// ChannelDestroyedData is the payload of the "channel.destroyed" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.destroyed
// Envelope: Envelope[ChannelDestroyedData]
type ChannelDestroyedData struct {
	LegID      string `json:"legId"`
	DurationMs *int   `json:"durationMs,omitempty"`
}

// ConferenceJoinedData is the payload of the "conference.joined" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.conference.joined
// Envelope: Envelope[ConferenceJoinedData]
type ConferenceJoinedData struct {
	LegID        string `json:"legId"`
	ConferenceID string `json:"conferenceId"`
	RoomNumber   string `json:"roomNumber"`
	BridgeID     string `json:"bridgeId"`
	Moderator    bool   `json:"moderator"`
	MemberCount  int    `json:"memberCount"`
}

// ConferenceLeftData is the payload of the "conference.left" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.conference.left
// Envelope: Envelope[ConferenceLeftData]
type ConferenceLeftData struct {
	LegID        string `json:"legId"`
	ConferenceID string `json:"conferenceId"`
	RoomNumber   string `json:"roomNumber"`
	BridgeID     string `json:"bridgeId"`
	Moderator    bool   `json:"moderator"`
	MemberCount  int    `json:"memberCount"`
	DurationMs   *int   `json:"durationMs,omitempty"`
}

// CallParkedData is the payload of the "call.parked" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.call.parked
// Envelope: Envelope[CallParkedData]
type CallParkedData struct {
	LegID         string  `json:"legId"`
	ParkLotID     string  `json:"parkLotId"`
	Slot          string  `json:"slot"`
	TimeoutMs     *int    `json:"timeoutMs,omitempty"`
	ParkedByLegID *string `json:"parkedByLegId,omitempty"`
	MOHClass      *string `json:"mohClass,omitempty"`
}

// CallUnparkedData is the payload of the "call.unparked" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.call.unparked
// Envelope: Envelope[CallUnparkedData]
type CallUnparkedData struct {
	LegID            string             `json:"legId"`
	ParkLotID        string             `json:"parkLotId"`
	Slot             string             `json:"slot"`
	Reason           CallUnparkedReason `json:"reason"`
	RetrievedByLegID *string            `json:"retrievedByLegId,omitempty"`
	DurationMs       *int               `json:"durationMs,omitempty"`
}

// CallUnparkedReason is the closed vocabulary of CallUnparkedData.reason.
type CallUnparkedReason string

const (
	CallUnparkedReasonRetrieved CallUnparkedReason = "retrieved"
	CallUnparkedReasonTimeout   CallUnparkedReason = "timeout"
	CallUnparkedReasonAbandoned CallUnparkedReason = "abandoned"
)

// CallUnparkedReasonValues lists every member of the vocabulary, in contract order.
var CallUnparkedReasonValues = []CallUnparkedReason{
	CallUnparkedReasonRetrieved,
	CallUnparkedReasonTimeout,
	CallUnparkedReasonAbandoned,
}

// Valid reports whether v is a member of the CallUnparkedReason vocabulary.
func (v CallUnparkedReason) Valid() bool {
	for _, candidate := range CallUnparkedReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v CallUnparkedReason) String() string { return string(v) }

// CallTransferredData is the payload of the "call.transferred" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.call.transferred
// Envelope: Envelope[CallTransferredData]
type CallTransferredData struct {
	LegID           string              `json:"legId"`
	Kind            CallTransferredKind `json:"kind"`
	Destination     string              `json:"destination"`
	RoutingContext  *string             `json:"routingContext,omitempty"`
	TransferorLegID *string             `json:"transferorLegId,omitempty"`
	TargetLegID     *string             `json:"targetLegId,omitempty"`
}

// CallTransferredKind is the closed vocabulary of CallTransferredData.kind.
type CallTransferredKind string

const (
	CallTransferredKindBlind    CallTransferredKind = "blind"
	CallTransferredKindAttended CallTransferredKind = "attended"
)

// CallTransferredKindValues lists every member of the vocabulary, in contract order.
var CallTransferredKindValues = []CallTransferredKind{
	CallTransferredKindBlind,
	CallTransferredKindAttended,
}

// Valid reports whether v is a member of the CallTransferredKind vocabulary.
func (v CallTransferredKind) Valid() bool {
	for _, candidate := range CallTransferredKindValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v CallTransferredKind) String() string { return string(v) }

// CallPickedUpData is the payload of the "call.picked-up" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.call.picked-up
// Envelope: Envelope[CallPickedUpData]
type CallPickedUpData struct {
	LegID          string           `json:"legId"`
	PickedUpLegID  string           `json:"pickedUpLegId"`
	Kind           CallPickedUpKind `json:"kind"`
	Extension      string           `json:"extension"`
	AbandonedLegID *string          `json:"abandonedLegId,omitempty"`
}

// CallPickedUpKind is the closed vocabulary of CallPickedUpData.kind.
type CallPickedUpKind string

const (
	CallPickedUpKindDirected CallPickedUpKind = "directed"
	CallPickedUpKindGroup    CallPickedUpKind = "group"
)

// CallPickedUpKindValues lists every member of the vocabulary, in contract order.
var CallPickedUpKindValues = []CallPickedUpKind{
	CallPickedUpKindDirected,
	CallPickedUpKindGroup,
}

// Valid reports whether v is a member of the CallPickedUpKind vocabulary.
func (v CallPickedUpKind) Valid() bool {
	for _, candidate := range CallPickedUpKindValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v CallPickedUpKind) String() string { return string(v) }

// CallEmergencyDialedData is the payload of the "call.emergency.dialed" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.call.emergency.dialed
// Envelope: Envelope[CallEmergencyDialedData]
type CallEmergencyDialedData struct {
	LegID              string  `json:"legId"`
	Dialed             string  `json:"dialed"`
	Number             string  `json:"number"`
	CallerNumber       *string `json:"callerNumber,omitempty"`
	CallerName         *string `json:"callerName,omitempty"`
	Elin               *string `json:"elin,omitempty"`
	EmergencyAddressID *string `json:"emergencyAddressId,omitempty"`
	TrunkName          *string `json:"trunkName,omitempty"`
}

// CallTapStartedData is the payload of the "call.tap.started" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.call.tap.started
// Envelope: Envelope[CallTapStartedData]
type CallTapStartedData struct {
	LegID               string   `json:"legId"`
	Mode                TapMode  `json:"mode"`
	SupervisorExtension string   `json:"supervisorExtension"`
	TargetExtension     string   `json:"targetExtension"`
	TargetLegID         *string  `json:"targetLegId,omitempty"`
	PreviousMode        *TapMode `json:"previousMode,omitempty"`
	SupervisorCallID    *string  `json:"supervisorCallId,omitempty"`
}

// CallTapEndedData is the payload of the "call.tap.ended" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.call.tap.ended
// Envelope: Envelope[CallTapEndedData]
type CallTapEndedData struct {
	LegID               string       `json:"legId"`
	Mode                TapMode      `json:"mode"`
	SupervisorExtension string       `json:"supervisorExtension"`
	TargetExtension     string       `json:"targetExtension"`
	Reason              TapEndReason `json:"reason"`
	DurationMs          *int         `json:"durationMs,omitempty"`
}

// CallPagingStartedData is the payload of the "call.paging.started" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.call.paging.started
// Envelope: Envelope[CallPagingStartedData]
type CallPagingStartedData struct {
	LegID           string  `json:"legId"`
	PagingGroupID   string  `json:"pagingGroupId"`
	PagingGroupName string  `json:"pagingGroupName"`
	Dialed          *string `json:"dialed,omitempty"`
	PagerExtension  *string `json:"pagerExtension,omitempty"`
	MemberCount     int     `json:"memberCount"`
	AnsweredCount   int     `json:"answeredCount"`
	OneWay          bool    `json:"oneWay"`
}

// CallPagingEndedData is the payload of the "call.paging.ended" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.call.paging.ended
// Envelope: Envelope[CallPagingEndedData]
type CallPagingEndedData struct {
	LegID           string `json:"legId"`
	PagingGroupID   string `json:"pagingGroupId"`
	PagingGroupName string `json:"pagingGroupName"`
	DurationMs      *int   `json:"durationMs,omitempty"`
	AnsweredCount   *int   `json:"answeredCount,omitempty"`
}
