// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Payloads for the call event family.

package events

// Event types carried on the call family's subjects. The value is the envelope's
// `type` discriminator, which is unique WITHIN the family only.
const (
	EventTypeChannelCreated       = "channel.created"
	EventTypeChannelRinging       = "channel.ringing"
	EventTypeChannelEarlyMedia    = "channel.early-media"
	EventTypeChannelAnswered      = "channel.answered"
	EventTypeChannelBridged       = "channel.bridged"
	EventTypeChannelUnbridged     = "channel.unbridged"
	EventTypeChannelHeld          = "channel.held"
	EventTypeChannelUnheld        = "channel.unheld"
	EventTypeChannelDTMF          = "channel.dtmf"
	EventTypeChannelRecordStarted = "channel.record.started"
	EventTypeChannelRecordStopped = "channel.record.stopped"
	EventTypeChannelHangup        = "channel.hangup"
	EventTypeChannelDestroyed     = "channel.destroyed"
	EventTypeConferenceJoined     = "conference.joined"
	EventTypeConferenceLeft       = "conference.left"
	EventTypeCallEmergencyDialed  = "call.emergency.dialed"
)

// ChannelCreatedData is the payload of the "channel.created" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.created
// Envelope: Envelope[ChannelCreatedData]
type ChannelCreatedData struct {
	LegID            string             `json:"legId"`
	Leg              LegSide            `json:"leg"`
	Direction        CallDirection      `json:"direction"`
	From             ChannelCreatedFrom `json:"from"`
	To               ChannelCreatedTo   `json:"to"`
	OriginatingLegID *string            `json:"originatingLegId,omitempty"`
	SIPCallID        *string            `json:"sipCallId,omitempty"`
	RoutingContext   *string            `json:"routingContext,omitempty"`
	RemoteAddress    *string            `json:"remoteAddress,omitempty"`
}

// ChannelCreatedFrom is a payload fragment of the contract.
type ChannelCreatedFrom struct {
	Number string  `json:"number"`
	Name   *string `json:"name,omitempty"`
}

// ChannelCreatedTo is a payload fragment of the contract.
type ChannelCreatedTo struct {
	Number string `json:"number"`
}

// ChannelRingingData is the payload of the "channel.ringing" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.ringing
// Envelope: Envelope[ChannelRingingData]
type ChannelRingingData struct {
	LegID string `json:"legId"`
}

// ChannelEarlyMediaData is the payload of the "channel.early-media" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.early-media
// Envelope: Envelope[ChannelEarlyMediaData]
type ChannelEarlyMediaData struct {
	LegID string `json:"legId"`
}

// ChannelAnsweredData is the payload of the "channel.answered" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.answered
// Envelope: Envelope[ChannelAnsweredData]
type ChannelAnsweredData struct {
	LegID string `json:"legId"`
}

// ChannelBridgedData is the payload of the "channel.bridged" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.bridged
// Envelope: Envelope[ChannelBridgedData]
type ChannelBridgedData struct {
	LegID     string     `json:"legId"`
	PeerLegID string     `json:"peerLegId"`
	BridgeID  string     `json:"bridgeId"`
	Mode      BridgeMode `json:"mode"`
}

// ChannelUnbridgedData is the payload of the "channel.unbridged" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.unbridged
// Envelope: Envelope[ChannelUnbridgedData]
type ChannelUnbridgedData struct {
	LegID     string  `json:"legId"`
	PeerLegID string  `json:"peerLegId"`
	BridgeID  string  `json:"bridgeId"`
	Reason    *string `json:"reason,omitempty"`
}

// ChannelHeldData is the payload of the "channel.held" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.held
// Envelope: Envelope[ChannelHeldData]
type ChannelHeldData struct {
	LegID    string  `json:"legId"`
	MOHClass *string `json:"mohClass,omitempty"`
}

// ChannelUnheldData is the payload of the "channel.unheld" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.unheld
// Envelope: Envelope[ChannelUnheldData]
type ChannelUnheldData struct {
	LegID string `json:"legId"`
}

// ChannelDTMFData is the payload of the "channel.dtmf" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.dtmf
// Envelope: Envelope[ChannelDTMFData]
type ChannelDTMFData struct {
	LegID      string     `json:"legId"`
	Digit      string     `json:"digit"`
	DurationMs int        `json:"durationMs"`
	Source     DTMFSource `json:"source"`
}

// ChannelRecordStartedData is the payload of the "channel.record.started" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.record.started
// Envelope: Envelope[ChannelRecordStartedData]
type ChannelRecordStartedData struct {
	LegID       string        `json:"legId"`
	RecordingID string        `json:"recordingId"`
	ObjectKey   string        `json:"objectKey"`
	Kind        RecordingKind `json:"kind"`
	Stereo      *bool         `json:"stereo,omitempty"`
}

// ChannelRecordStoppedData is the payload of the "channel.record.stopped" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.record.stopped
// Envelope: Envelope[ChannelRecordStoppedData]
type ChannelRecordStoppedData struct {
	LegID       string              `json:"legId"`
	RecordingID string              `json:"recordingId"`
	ObjectKey   string              `json:"objectKey"`
	DurationMs  int                 `json:"durationMs"`
	Reason      RecordingStopReason `json:"reason"`
	Bytes       *int                `json:"bytes,omitempty"`
}

// ChannelHangupData is the payload of the "channel.hangup" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.hangup
// Envelope: Envelope[ChannelHangupData]
type ChannelHangupData struct {
	LegID     string     `json:"legId"`
	Cause     string     `json:"cause"`
	CauseCode int        `json:"causeCode"`
	Side      HangupSide `json:"side"`
}

// ChannelDestroyedData is the payload of the "channel.destroyed" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.channel.destroyed
// Envelope: Envelope[ChannelDestroyedData]
type ChannelDestroyedData struct {
	LegID      string `json:"legId"`
	DurationMs *int   `json:"durationMs,omitempty"`
}

// ConferenceJoinedData is the payload of the "conference.joined" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.conference.joined
// Envelope: Envelope[ConferenceJoinedData]
type ConferenceJoinedData struct {
	LegID        string `json:"legId"`
	ConferenceID string `json:"conferenceId"`
	RoomNumber   string `json:"roomNumber"`
	BridgeID     string `json:"bridgeId"`
	Moderator    bool   `json:"moderator"`
	MemberCount  int    `json:"memberCount"`
}

// ConferenceLeftData is the payload of the "conference.left" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.conference.left
// Envelope: Envelope[ConferenceLeftData]
type ConferenceLeftData struct {
	LegID        string `json:"legId"`
	ConferenceID string `json:"conferenceId"`
	RoomNumber   string `json:"roomNumber"`
	BridgeID     string `json:"bridgeId"`
	Moderator    bool   `json:"moderator"`
	MemberCount  int    `json:"memberCount"`
	DurationMs   *int   `json:"durationMs,omitempty"`
}

// CallEmergencyDialedData is the payload of the "call.emergency.dialed" event.
//
// Subject: calls.evt.v1.<orgId>.<callId>.call.emergency.dialed
// Envelope: Envelope[CallEmergencyDialedData]
type CallEmergencyDialedData struct {
	LegID              string  `json:"legId"`
	Dialed             string  `json:"dialed"`
	Number             string  `json:"number"`
	CallerNumber       *string `json:"callerNumber,omitempty"`
	CallerName         *string `json:"callerName,omitempty"`
	Elin               *string `json:"elin,omitempty"`
	EmergencyAddressID *string `json:"emergencyAddressId,omitempty"`
	TrunkName          *string `json:"trunkName,omitempty"`
}
