// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Payloads for the cdr event family.

package events

import "encoding/json"

// Event types carried on the cdr family's subjects. The value is the envelope's
// `type` discriminator, which is unique WITHIN the family only.
const (
	EventTypeCDRLegWrite = "cdr.leg.write"
)

// CDRLegWriteData is the payload of the "cdr.leg.write" event.
//
// Subject: cdr.leg.v1.<orgId>
// Envelope: Envelope[CDRLegWriteData]
type CDRLegWriteData struct {
	ID               string                   `json:"id"`
	CallID           string                   `json:"callId"`
	Leg              LegSide                  `json:"leg"`
	OriginatingLegID *string                  `json:"originatingLegId,omitempty"`
	BridgeLegID      *string                  `json:"bridgeLegId,omitempty"`
	Direction        CallDirection            `json:"direction"`
	FromNumber       string                   `json:"fromNumber"`
	FromName         *string                  `json:"fromName,omitempty"`
	ToNumber         string                   `json:"toNumber"`
	DestinationType  string                   `json:"destinationType"`
	DestinationRef   *string                  `json:"destinationRef,omitempty"`
	StartedAt        EventTime                `json:"startedAt"`
	AnsweredAt       *EventTime               `json:"answeredAt,omitempty"`
	EndedAt          *EventTime               `json:"endedAt,omitempty"`
	DurationMs       int                      `json:"durationMs"`
	BillsecMs        int                      `json:"billsecMs"`
	HangupCause      string                   `json:"hangupCause"`
	HangupCauseCode  int                      `json:"hangupCauseCode"`
	HangupSide       *HangupSide              `json:"hangupSide,omitempty"`
	Disposition      string                   `json:"disposition"`
	QueueRef         *string                  `json:"queueRef,omitempty"`
	QueueWaitMs      *int                     `json:"queueWaitMs,omitempty"`
	QueueOutcome     *CDRLegWriteQueueOutcome `json:"queueOutcome,omitempty"`
	QueueAgentRef    *string                  `json:"queueAgentRef,omitempty"`
	AuthPinOrdinal   *int                     `json:"authPinOrdinal,omitempty"`
	AuthPinLabel     *string                  `json:"authPinLabel,omitempty"`

	// Extra carries every key outside the pinned contract, verbatim. The TS schema is a
	// z.looseObject (see cdr-events.ts) precisely so a producer running ahead of the
	// consumer is not silently truncated; dropping these on the Go side would reintroduce
	// the loss the loose schema exists to prevent.
	Extra map[string]json.RawMessage `json:"-"`
}

// MarshalJSON merges Extra back into the object, pinned fields winning on conflict.
func (v CDRLegWriteData) MarshalJSON() ([]byte, error) {
	type alias CDRLegWriteData
	return marshalWithExtras(alias(v), v.Extra)
}

// UnmarshalJSON captures unknown keys into Extra instead of discarding them.
func (v *CDRLegWriteData) UnmarshalJSON(data []byte) error {
	type alias CDRLegWriteData
	var inner alias
	extra, err := unmarshalWithExtras(data, &inner, knownKeysCDRLegWriteData)
	if err != nil {
		return err
	}
	*v = CDRLegWriteData(inner)
	v.Extra = extra
	return nil
}

var knownKeysCDRLegWriteData = map[string]struct{}{
	"id":               {},
	"callId":           {},
	"leg":              {},
	"originatingLegId": {},
	"bridgeLegId":      {},
	"direction":        {},
	"fromNumber":       {},
	"fromName":         {},
	"toNumber":         {},
	"destinationType":  {},
	"destinationRef":   {},
	"startedAt":        {},
	"answeredAt":       {},
	"endedAt":          {},
	"durationMs":       {},
	"billsecMs":        {},
	"hangupCause":      {},
	"hangupCauseCode":  {},
	"hangupSide":       {},
	"disposition":      {},
	"queueRef":         {},
	"queueWaitMs":      {},
	"queueOutcome":     {},
	"queueAgentRef":    {},
	"authPinOrdinal":   {},
	"authPinLabel":     {},
}

// CDRLegWriteQueueOutcome is the closed vocabulary of CDRLegWriteData.queueOutcome.
type CDRLegWriteQueueOutcome string

const (
	CDRLegWriteQueueOutcomeAnswered     CDRLegWriteQueueOutcome = "answered"
	CDRLegWriteQueueOutcomeCallerHangup CDRLegWriteQueueOutcome = "caller-hangup"
	CDRLegWriteQueueOutcomeTimeout      CDRLegWriteQueueOutcome = "timeout"
	CDRLegWriteQueueOutcomeOverflow     CDRLegWriteQueueOutcome = "overflow"
	CDRLegWriteQueueOutcomeNoAgents     CDRLegWriteQueueOutcome = "no-agents"
	CDRLegWriteQueueOutcomeExitKey      CDRLegWriteQueueOutcome = "exit-key"
)

// CDRLegWriteQueueOutcomeValues lists every member of the vocabulary, in contract order.
var CDRLegWriteQueueOutcomeValues = []CDRLegWriteQueueOutcome{
	CDRLegWriteQueueOutcomeAnswered,
	CDRLegWriteQueueOutcomeCallerHangup,
	CDRLegWriteQueueOutcomeTimeout,
	CDRLegWriteQueueOutcomeOverflow,
	CDRLegWriteQueueOutcomeNoAgents,
	CDRLegWriteQueueOutcomeExitKey,
}

// Valid reports whether v is a member of the CDRLegWriteQueueOutcome vocabulary.
func (v CDRLegWriteQueueOutcome) Valid() bool {
	for _, candidate := range CDRLegWriteQueueOutcomeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v CDRLegWriteQueueOutcome) String() string { return string(v) }
