// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// The Q.850 hangup-cause taxonomy, plus the FreeSWITCH extensions.
//
// Authority: packages/telephony/src/hangup-causes.ts, itself pinned against the frozen
// reference §6 by its own spec. This is a GENERATED COPY so that Go and TypeScript read one
// table: renaming a member is a breaking change for every stored CDR row, and re-coding one
// silently changes outbound failover, so neither may be decided twice.
//
// apps/sipd/internal/dialog/cause.go defines its Cause* constants in terms of the HangupCode*
// constants here. The SIP status -> Q.850 mapping stays in sipd: that one IS the edge's own
// knowledge (RFC 3398), and nothing outside the SIP stack has an opinion about it.

package events

// HangupCause is a hangup-cause NAME — the value stored on `call_legs.hangup_cause` and
// carried by `cdr.leg.v1` and the `dialog.terminated` event.
//
// A plain string type rather than a closed enum, deliberately: a cause this build does not
// know must still reach the CDR writer, which stores the numeric code verbatim and falls back
// to NORMAL_UNSPECIFIED.
type HangupCause string

// The named causes. Q.850 1-127 first, then the FreeSWITCH extensions.
const (
	HangupCauseNone                        HangupCause = "NONE"
	HangupCauseUnallocatedNumber           HangupCause = "UNALLOCATED_NUMBER"
	HangupCauseNoRouteTransitNet           HangupCause = "NO_ROUTE_TRANSIT_NET"
	HangupCauseNoRouteDestination          HangupCause = "NO_ROUTE_DESTINATION"
	HangupCauseChannelUnacceptable         HangupCause = "CHANNEL_UNACCEPTABLE"
	HangupCauseCallAwardedDelivered        HangupCause = "CALL_AWARDED_DELIVERED"
	HangupCauseNormalClearing              HangupCause = "NORMAL_CLEARING"
	HangupCauseUserBusy                    HangupCause = "USER_BUSY"
	HangupCauseNoUserResponse              HangupCause = "NO_USER_RESPONSE"
	HangupCauseNoAnswer                    HangupCause = "NO_ANSWER"
	HangupCauseSubscriberAbsent            HangupCause = "SUBSCRIBER_ABSENT"
	HangupCauseCallRejected                HangupCause = "CALL_REJECTED"
	HangupCauseNumberChanged               HangupCause = "NUMBER_CHANGED"
	HangupCauseRedirectionToNewDestination HangupCause = "REDIRECTION_TO_NEW_DESTINATION"
	HangupCauseExchangeRoutingError        HangupCause = "EXCHANGE_ROUTING_ERROR"
	HangupCauseDestinationOutOfOrder       HangupCause = "DESTINATION_OUT_OF_ORDER"
	HangupCauseInvalidNumberFormat         HangupCause = "INVALID_NUMBER_FORMAT"
	HangupCauseFacilityRejected            HangupCause = "FACILITY_REJECTED"
	HangupCauseResponseToStatusEnquiry     HangupCause = "RESPONSE_TO_STATUS_ENQUIRY"
	HangupCauseNormalUnspecified           HangupCause = "NORMAL_UNSPECIFIED"
	HangupCauseNormalCircuitCongestion     HangupCause = "NORMAL_CIRCUIT_CONGESTION"
	HangupCauseNetworkOutOfOrder           HangupCause = "NETWORK_OUT_OF_ORDER"
	HangupCauseNormalTemporaryFailure      HangupCause = "NORMAL_TEMPORARY_FAILURE"
	HangupCauseSwitchCongestion            HangupCause = "SWITCH_CONGESTION"
	HangupCauseAccessInfoDiscarded         HangupCause = "ACCESS_INFO_DISCARDED"
	HangupCauseRequestedChanUnavail        HangupCause = "REQUESTED_CHAN_UNAVAIL"
	HangupCausePreEmpted                   HangupCause = "PRE_EMPTED"
	HangupCauseFacilityNotSubscribed       HangupCause = "FACILITY_NOT_SUBSCRIBED"
	HangupCauseOutgoingCallBarred          HangupCause = "OUTGOING_CALL_BARRED"
	HangupCauseIncomingCallBarred          HangupCause = "INCOMING_CALL_BARRED"
	HangupCauseBearercapabilityNotauth     HangupCause = "BEARERCAPABILITY_NOTAUTH"
	HangupCauseBearercapabilityNotavail    HangupCause = "BEARERCAPABILITY_NOTAVAIL"
	HangupCauseServiceUnavailable          HangupCause = "SERVICE_UNAVAILABLE"
	HangupCauseBearercapabilityNotimpl     HangupCause = "BEARERCAPABILITY_NOTIMPL"
	HangupCauseChanNotImplemented          HangupCause = "CHAN_NOT_IMPLEMENTED"
	HangupCauseFacilityNotImplemented      HangupCause = "FACILITY_NOT_IMPLEMENTED"
	HangupCauseServiceNotImplemented       HangupCause = "SERVICE_NOT_IMPLEMENTED"
	HangupCauseInvalidCallReference        HangupCause = "INVALID_CALL_REFERENCE"
	HangupCauseIncompatibleDestination     HangupCause = "INCOMPATIBLE_DESTINATION"
	HangupCauseInvalidMsgUnspecified       HangupCause = "INVALID_MSG_UNSPECIFIED"
	HangupCauseMandatoryIeMissing          HangupCause = "MANDATORY_IE_MISSING"
	HangupCauseMessageTypeNonexist         HangupCause = "MESSAGE_TYPE_NONEXIST"
	HangupCauseWrongMessage                HangupCause = "WRONG_MESSAGE"
	HangupCauseIeNonexist                  HangupCause = "IE_NONEXIST"
	HangupCauseInvalidIeContents           HangupCause = "INVALID_IE_CONTENTS"
	HangupCauseWrongCallState              HangupCause = "WRONG_CALL_STATE"
	HangupCauseRecoveryOnTimerExpire       HangupCause = "RECOVERY_ON_TIMER_EXPIRE"
	HangupCauseMandatoryIeLengthError      HangupCause = "MANDATORY_IE_LENGTH_ERROR"
	HangupCauseProtocolError               HangupCause = "PROTOCOL_ERROR"
	HangupCauseInterworking                HangupCause = "INTERWORKING"
	HangupCauseOriginatorCancel            HangupCause = "ORIGINATOR_CANCEL"
	HangupCauseLoseRace                    HangupCause = "LOSE_RACE"
	HangupCauseBlindTransfer               HangupCause = "BLIND_TRANSFER"
	HangupCauseAttendedTransfer            HangupCause = "ATTENDED_TRANSFER"
	HangupCauseAllottedTimeout             HangupCause = "ALLOTTED_TIMEOUT"
	HangupCauseUserChallenge               HangupCause = "USER_CHALLENGE"
	HangupCauseMediaTimeout                HangupCause = "MEDIA_TIMEOUT"
	HangupCausePickedOff                   HangupCause = "PICKED_OFF"
	HangupCauseUserNotRegistered           HangupCause = "USER_NOT_REGISTERED"
	HangupCauseProgressTimeout             HangupCause = "PROGRESS_TIMEOUT"
	HangupCauseInvalidGateway              HangupCause = "INVALID_GATEWAY"
	HangupCauseGatewayDown                 HangupCause = "GATEWAY_DOWN"
	HangupCauseInvalidUrl                  HangupCause = "INVALID_URL"
	HangupCauseInvalidProfile              HangupCause = "INVALID_PROFILE"
	HangupCauseNoPickup                    HangupCause = "NO_PICKUP"
	HangupCauseSrtpReadError               HangupCause = "SRTP_READ_ERROR"
)

// The numeric code for each named cause, as untyped constants.
//
// Constants rather than only the map below, because a Go caller that wants a compile-time
// constant cannot get one out of a map — `apps/sipd/internal/dialog/cause.go` defines its
// whole Cause* set in terms of these.
const (
	HangupCodeNone                        = 0
	HangupCodeUnallocatedNumber           = 1
	HangupCodeNoRouteTransitNet           = 2
	HangupCodeNoRouteDestination          = 3
	HangupCodeChannelUnacceptable         = 6
	HangupCodeCallAwardedDelivered        = 7
	HangupCodeNormalClearing              = 16
	HangupCodeUserBusy                    = 17
	HangupCodeNoUserResponse              = 18
	HangupCodeNoAnswer                    = 19
	HangupCodeSubscriberAbsent            = 20
	HangupCodeCallRejected                = 21
	HangupCodeNumberChanged               = 22
	HangupCodeRedirectionToNewDestination = 23
	HangupCodeExchangeRoutingError        = 25
	HangupCodeDestinationOutOfOrder       = 27
	HangupCodeInvalidNumberFormat         = 28
	HangupCodeFacilityRejected            = 29
	HangupCodeResponseToStatusEnquiry     = 30
	HangupCodeNormalUnspecified           = 31
	HangupCodeNormalCircuitCongestion     = 34
	HangupCodeNetworkOutOfOrder           = 38
	HangupCodeNormalTemporaryFailure      = 41
	HangupCodeSwitchCongestion            = 42
	HangupCodeAccessInfoDiscarded         = 43
	HangupCodeRequestedChanUnavail        = 44
	HangupCodePreEmpted                   = 45
	HangupCodeFacilityNotSubscribed       = 50
	HangupCodeOutgoingCallBarred          = 52
	HangupCodeIncomingCallBarred          = 54
	HangupCodeBearercapabilityNotauth     = 57
	HangupCodeBearercapabilityNotavail    = 58
	HangupCodeServiceUnavailable          = 63
	HangupCodeBearercapabilityNotimpl     = 65
	HangupCodeChanNotImplemented          = 66
	HangupCodeFacilityNotImplemented      = 69
	HangupCodeServiceNotImplemented       = 79
	HangupCodeInvalidCallReference        = 81
	HangupCodeIncompatibleDestination     = 88
	HangupCodeInvalidMsgUnspecified       = 95
	HangupCodeMandatoryIeMissing          = 96
	HangupCodeMessageTypeNonexist         = 97
	HangupCodeWrongMessage                = 98
	HangupCodeIeNonexist                  = 99
	HangupCodeInvalidIeContents           = 100
	HangupCodeWrongCallState              = 101
	HangupCodeRecoveryOnTimerExpire       = 102
	HangupCodeMandatoryIeLengthError      = 103
	HangupCodeProtocolError               = 111
	HangupCodeInterworking                = 127
	HangupCodeOriginatorCancel            = 487
	HangupCodeLoseRace                    = 702
	HangupCodeBlindTransfer               = 800
	HangupCodeAttendedTransfer            = 801
	HangupCodeAllottedTimeout             = 802
	HangupCodeUserChallenge               = 803
	HangupCodeMediaTimeout                = 804
	HangupCodePickedOff                   = 805
	HangupCodeUserNotRegistered           = 806
	HangupCodeProgressTimeout             = 807
	HangupCodeInvalidGateway              = 808
	HangupCodeGatewayDown                 = 809
	HangupCodeInvalidUrl                  = 810
	HangupCodeInvalidProfile              = 811
	HangupCodeNoPickup                    = 812
	HangupCodeSrtpReadError               = 813
)

// Q850HangupCauses lists the Q.850 members, in contract order.
var Q850HangupCauses = []HangupCause{
	HangupCauseNone,
	HangupCauseUnallocatedNumber,
	HangupCauseNoRouteTransitNet,
	HangupCauseNoRouteDestination,
	HangupCauseChannelUnacceptable,
	HangupCauseCallAwardedDelivered,
	HangupCauseNormalClearing,
	HangupCauseUserBusy,
	HangupCauseNoUserResponse,
	HangupCauseNoAnswer,
	HangupCauseSubscriberAbsent,
	HangupCauseCallRejected,
	HangupCauseNumberChanged,
	HangupCauseRedirectionToNewDestination,
	HangupCauseExchangeRoutingError,
	HangupCauseDestinationOutOfOrder,
	HangupCauseInvalidNumberFormat,
	HangupCauseFacilityRejected,
	HangupCauseResponseToStatusEnquiry,
	HangupCauseNormalUnspecified,
	HangupCauseNormalCircuitCongestion,
	HangupCauseNetworkOutOfOrder,
	HangupCauseNormalTemporaryFailure,
	HangupCauseSwitchCongestion,
	HangupCauseAccessInfoDiscarded,
	HangupCauseRequestedChanUnavail,
	HangupCausePreEmpted,
	HangupCauseFacilityNotSubscribed,
	HangupCauseOutgoingCallBarred,
	HangupCauseIncomingCallBarred,
	HangupCauseBearercapabilityNotauth,
	HangupCauseBearercapabilityNotavail,
	HangupCauseServiceUnavailable,
	HangupCauseBearercapabilityNotimpl,
	HangupCauseChanNotImplemented,
	HangupCauseFacilityNotImplemented,
	HangupCauseServiceNotImplemented,
	HangupCauseInvalidCallReference,
	HangupCauseIncompatibleDestination,
	HangupCauseInvalidMsgUnspecified,
	HangupCauseMandatoryIeMissing,
	HangupCauseMessageTypeNonexist,
	HangupCauseWrongMessage,
	HangupCauseIeNonexist,
	HangupCauseInvalidIeContents,
	HangupCauseWrongCallState,
	HangupCauseRecoveryOnTimerExpire,
	HangupCauseMandatoryIeLengthError,
	HangupCauseProtocolError,
	HangupCauseInterworking,
}

// ExtendedHangupCauses lists the FreeSWITCH extensions, in contract order.
var ExtendedHangupCauses = []HangupCause{
	HangupCauseOriginatorCancel,
	HangupCauseLoseRace,
	HangupCauseBlindTransfer,
	HangupCauseAttendedTransfer,
	HangupCauseAllottedTimeout,
	HangupCauseUserChallenge,
	HangupCauseMediaTimeout,
	HangupCausePickedOff,
	HangupCauseUserNotRegistered,
	HangupCauseProgressTimeout,
	HangupCauseInvalidGateway,
	HangupCauseGatewayDown,
	HangupCauseInvalidUrl,
	HangupCauseInvalidProfile,
	HangupCauseNoPickup,
	HangupCauseSrtpReadError,
}

// HangupCauses lists every named cause, Q.850 first. Contract order, matching
// HANGUP_CAUSES in packages/telephony.
var HangupCauses = append(append([]HangupCause{}, Q850HangupCauses...), ExtendedHangupCauses...)

// HangupCauseCodes maps a cause name onto its numeric code.
var HangupCauseCodes = map[HangupCause]int{
	HangupCauseNone:                        HangupCodeNone,
	HangupCauseUnallocatedNumber:           HangupCodeUnallocatedNumber,
	HangupCauseNoRouteTransitNet:           HangupCodeNoRouteTransitNet,
	HangupCauseNoRouteDestination:          HangupCodeNoRouteDestination,
	HangupCauseChannelUnacceptable:         HangupCodeChannelUnacceptable,
	HangupCauseCallAwardedDelivered:        HangupCodeCallAwardedDelivered,
	HangupCauseNormalClearing:              HangupCodeNormalClearing,
	HangupCauseUserBusy:                    HangupCodeUserBusy,
	HangupCauseNoUserResponse:              HangupCodeNoUserResponse,
	HangupCauseNoAnswer:                    HangupCodeNoAnswer,
	HangupCauseSubscriberAbsent:            HangupCodeSubscriberAbsent,
	HangupCauseCallRejected:                HangupCodeCallRejected,
	HangupCauseNumberChanged:               HangupCodeNumberChanged,
	HangupCauseRedirectionToNewDestination: HangupCodeRedirectionToNewDestination,
	HangupCauseExchangeRoutingError:        HangupCodeExchangeRoutingError,
	HangupCauseDestinationOutOfOrder:       HangupCodeDestinationOutOfOrder,
	HangupCauseInvalidNumberFormat:         HangupCodeInvalidNumberFormat,
	HangupCauseFacilityRejected:            HangupCodeFacilityRejected,
	HangupCauseResponseToStatusEnquiry:     HangupCodeResponseToStatusEnquiry,
	HangupCauseNormalUnspecified:           HangupCodeNormalUnspecified,
	HangupCauseNormalCircuitCongestion:     HangupCodeNormalCircuitCongestion,
	HangupCauseNetworkOutOfOrder:           HangupCodeNetworkOutOfOrder,
	HangupCauseNormalTemporaryFailure:      HangupCodeNormalTemporaryFailure,
	HangupCauseSwitchCongestion:            HangupCodeSwitchCongestion,
	HangupCauseAccessInfoDiscarded:         HangupCodeAccessInfoDiscarded,
	HangupCauseRequestedChanUnavail:        HangupCodeRequestedChanUnavail,
	HangupCausePreEmpted:                   HangupCodePreEmpted,
	HangupCauseFacilityNotSubscribed:       HangupCodeFacilityNotSubscribed,
	HangupCauseOutgoingCallBarred:          HangupCodeOutgoingCallBarred,
	HangupCauseIncomingCallBarred:          HangupCodeIncomingCallBarred,
	HangupCauseBearercapabilityNotauth:     HangupCodeBearercapabilityNotauth,
	HangupCauseBearercapabilityNotavail:    HangupCodeBearercapabilityNotavail,
	HangupCauseServiceUnavailable:          HangupCodeServiceUnavailable,
	HangupCauseBearercapabilityNotimpl:     HangupCodeBearercapabilityNotimpl,
	HangupCauseChanNotImplemented:          HangupCodeChanNotImplemented,
	HangupCauseFacilityNotImplemented:      HangupCodeFacilityNotImplemented,
	HangupCauseServiceNotImplemented:       HangupCodeServiceNotImplemented,
	HangupCauseInvalidCallReference:        HangupCodeInvalidCallReference,
	HangupCauseIncompatibleDestination:     HangupCodeIncompatibleDestination,
	HangupCauseInvalidMsgUnspecified:       HangupCodeInvalidMsgUnspecified,
	HangupCauseMandatoryIeMissing:          HangupCodeMandatoryIeMissing,
	HangupCauseMessageTypeNonexist:         HangupCodeMessageTypeNonexist,
	HangupCauseWrongMessage:                HangupCodeWrongMessage,
	HangupCauseIeNonexist:                  HangupCodeIeNonexist,
	HangupCauseInvalidIeContents:           HangupCodeInvalidIeContents,
	HangupCauseWrongCallState:              HangupCodeWrongCallState,
	HangupCauseRecoveryOnTimerExpire:       HangupCodeRecoveryOnTimerExpire,
	HangupCauseMandatoryIeLengthError:      HangupCodeMandatoryIeLengthError,
	HangupCauseProtocolError:               HangupCodeProtocolError,
	HangupCauseInterworking:                HangupCodeInterworking,
	HangupCauseOriginatorCancel:            HangupCodeOriginatorCancel,
	HangupCauseLoseRace:                    HangupCodeLoseRace,
	HangupCauseBlindTransfer:               HangupCodeBlindTransfer,
	HangupCauseAttendedTransfer:            HangupCodeAttendedTransfer,
	HangupCauseAllottedTimeout:             HangupCodeAllottedTimeout,
	HangupCauseUserChallenge:               HangupCodeUserChallenge,
	HangupCauseMediaTimeout:                HangupCodeMediaTimeout,
	HangupCausePickedOff:                   HangupCodePickedOff,
	HangupCauseUserNotRegistered:           HangupCodeUserNotRegistered,
	HangupCauseProgressTimeout:             HangupCodeProgressTimeout,
	HangupCauseInvalidGateway:              HangupCodeInvalidGateway,
	HangupCauseGatewayDown:                 HangupCodeGatewayDown,
	HangupCauseInvalidUrl:                  HangupCodeInvalidUrl,
	HangupCauseInvalidProfile:              HangupCodeInvalidProfile,
	HangupCauseNoPickup:                    HangupCodeNoPickup,
	HangupCauseSrtpReadError:               HangupCodeSrtpReadError,
}

// HangupCauseNames maps a numeric code back onto its name.
//
// Built from the same generated pairs as HangupCauseCodes, so the two cannot diverge — the
// property HANGUP_CAUSE_NAMES gets in TypeScript by construction.
var HangupCauseNames = func() map[int]HangupCause {
	names := make(map[int]HangupCause, len(HangupCauseCodes))
	for cause, code := range HangupCauseCodes {
		names[code] = cause
	}
	return names
}()

// HangupCauseCodeOf returns the numeric code for a cause name, and whether it is a name this
// contract knows. An unknown name yields 0, which is NONE — the "no cause recorded" sentinel
// and never a real outcome, so a caller that ignores the boolean cannot bill from it.
func HangupCauseCodeOf(cause HangupCause) (int, bool) {
	code, found := HangupCauseCodes[cause]
	return code, found
}

// HangupCauseFromCode returns the name for a numeric code.
//
// Only the ~65 points a softswitch actually emits are named; anything else a carrier sends is
// stored as its raw code with NORMAL_UNSPECIFIED, which is why this reports absence rather
// than inventing a name.
func HangupCauseFromCode(code int) (HangupCause, bool) {
	cause, found := HangupCauseNames[code]
	return cause, found
}

// IsHangupCause reports whether a string arriving from the wire is a name this contract knows.
func IsHangupCause(value string) bool {
	_, found := HangupCauseCodes[HangupCause(value)]
	return found
}
