// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// KV bucket VALUE contracts from schemas/live-state.ts.
//
// The keys are built by subjects.go; these are what the buckets hold. A Go reader that
// hand-writes one of these structs is a drift the parity golden cannot see, which is how
// the sip-acl reader ended up expecting `organizationId` for a writer emitting `orgId`.

package events

import "encoding/json"

// TrunkDirectoryEntry is the API projection stored in the trunks KV bucket.
type TrunkDirectoryEntry struct {
	TrunkID                string                  `json:"trunkId"`
	OrgID                  string                  `json:"orgId"`
	Name                   string                  `json:"name"`
	Kind                   TrunkDirectoryEntryKind `json:"kind"`
	SIPDomain              string                  `json:"sipDomain"`
	SIPProxy               string                  `json:"sipProxy"`
	OutboundProxy          *string                 `json:"outboundProxy,omitempty"`
	AuthUser               *string                 `json:"authUser,omitempty"`
	SecretRef              *string                 `json:"secretRef,omitempty"`
	Transport              SIPTransport            `json:"transport"`
	RegisterExpiresSeconds int                     `json:"registerExpiresSeconds"`
	MaxChannels            *int                    `json:"maxChannels,omitempty"`
	CallerIDNumberOverride *string                 `json:"callerIdNumberOverride,omitempty"`
	Enabled                bool                    `json:"enabled"`
	UpdatedAt              float64                 `json:"updatedAt"`

	// Extra carries every key outside the pinned contract, verbatim. The TS schema is a
	// z.looseObject (see cdr-events.ts) precisely so a producer running ahead of the
	// consumer is not silently truncated; dropping these on the Go side would reintroduce
	// the loss the loose schema exists to prevent.
	Extra map[string]json.RawMessage `json:"-"`
}

// MarshalJSON merges Extra back into the object, pinned fields winning on conflict.
func (v TrunkDirectoryEntry) MarshalJSON() ([]byte, error) {
	type alias TrunkDirectoryEntry
	return marshalWithExtras(alias(v), v.Extra)
}

// UnmarshalJSON captures unknown keys into Extra instead of discarding them.
func (v *TrunkDirectoryEntry) UnmarshalJSON(data []byte) error {
	type alias TrunkDirectoryEntry
	var inner alias
	extra, err := unmarshalWithExtras(data, &inner, knownKeysTrunkDirectoryEntry)
	if err != nil {
		return err
	}
	*v = TrunkDirectoryEntry(inner)
	v.Extra = extra
	return nil
}

var knownKeysTrunkDirectoryEntry = map[string]struct{}{
	"trunkId":                {},
	"orgId":                  {},
	"name":                   {},
	"kind":                   {},
	"sipDomain":              {},
	"sipProxy":               {},
	"outboundProxy":          {},
	"authUser":               {},
	"secretRef":              {},
	"transport":              {},
	"registerExpiresSeconds": {},
	"maxChannels":            {},
	"callerIdNumberOverride": {},
	"enabled":                {},
	"updatedAt":              {},
}

// TrunkDirectoryEntryKind is the closed vocabulary of TrunkDirectoryEntry.kind.
type TrunkDirectoryEntryKind string

const (
	TrunkDirectoryEntryKindRegister TrunkDirectoryEntryKind = "register"
	TrunkDirectoryEntryKindIPAuth   TrunkDirectoryEntryKind = "ip-auth"
)

// TrunkDirectoryEntryKindValues lists every member of the vocabulary, in contract order.
var TrunkDirectoryEntryKindValues = []TrunkDirectoryEntryKind{
	TrunkDirectoryEntryKindRegister,
	TrunkDirectoryEntryKindIPAuth,
}

// Valid reports whether v is a member of the TrunkDirectoryEntryKind vocabulary.
func (v TrunkDirectoryEntryKind) Valid() bool {
	for _, candidate := range TrunkDirectoryEntryKindValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v TrunkDirectoryEntryKind) String() string { return string(v) }

// SIPACLEntry is one rule in the sip-acl KV bucket: the edge's admission boundary.
type SIPACLEntry struct {
	Network   string            `json:"network"`
	OrgID     string            `json:"orgId"`
	Action    SIPACLEntryAction `json:"action"`
	Scope     SIPACLEntryScope  `json:"scope"`
	Priority  int               `json:"priority"`
	TrunkID   *string           `json:"trunkId,omitempty"`
	Name      *string           `json:"name,omitempty"`
	Enabled   bool              `json:"enabled"`
	UpdatedAt float64           `json:"updatedAt"`

	// Extra carries every key outside the pinned contract, verbatim. The TS schema is a
	// z.looseObject (see cdr-events.ts) precisely so a producer running ahead of the
	// consumer is not silently truncated; dropping these on the Go side would reintroduce
	// the loss the loose schema exists to prevent.
	Extra map[string]json.RawMessage `json:"-"`
}

// MarshalJSON merges Extra back into the object, pinned fields winning on conflict.
func (v SIPACLEntry) MarshalJSON() ([]byte, error) {
	type alias SIPACLEntry
	return marshalWithExtras(alias(v), v.Extra)
}

// UnmarshalJSON captures unknown keys into Extra instead of discarding them.
func (v *SIPACLEntry) UnmarshalJSON(data []byte) error {
	type alias SIPACLEntry
	var inner alias
	extra, err := unmarshalWithExtras(data, &inner, knownKeysSIPACLEntry)
	if err != nil {
		return err
	}
	*v = SIPACLEntry(inner)
	v.Extra = extra
	return nil
}

var knownKeysSIPACLEntry = map[string]struct{}{
	"network":   {},
	"orgId":     {},
	"action":    {},
	"scope":     {},
	"priority":  {},
	"trunkId":   {},
	"name":      {},
	"enabled":   {},
	"updatedAt": {},
}

// SIPACLEntryAction is the closed vocabulary of SIPACLEntry.action.
type SIPACLEntryAction string

const (
	SIPACLEntryActionAllow SIPACLEntryAction = "allow"
	SIPACLEntryActionDeny  SIPACLEntryAction = "deny"
)

// SIPACLEntryActionValues lists every member of the vocabulary, in contract order.
var SIPACLEntryActionValues = []SIPACLEntryAction{
	SIPACLEntryActionAllow,
	SIPACLEntryActionDeny,
}

// Valid reports whether v is a member of the SIPACLEntryAction vocabulary.
func (v SIPACLEntryAction) Valid() bool {
	for _, candidate := range SIPACLEntryActionValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SIPACLEntryAction) String() string { return string(v) }

// SIPACLEntryScope is the closed vocabulary of SIPACLEntry.scope.
type SIPACLEntryScope string

const (
	SIPACLEntryScopeRegistration SIPACLEntryScope = "registration"
	SIPACLEntryScopeTrunk        SIPACLEntryScope = "trunk"
	SIPACLEntryScopeProvisioning SIPACLEntryScope = "provisioning"
	SIPACLEntryScopeAPI          SIPACLEntryScope = "api"
)

// SIPACLEntryScopeValues lists every member of the vocabulary, in contract order.
var SIPACLEntryScopeValues = []SIPACLEntryScope{
	SIPACLEntryScopeRegistration,
	SIPACLEntryScopeTrunk,
	SIPACLEntryScopeProvisioning,
	SIPACLEntryScopeAPI,
}

// Valid reports whether v is a member of the SIPACLEntryScope vocabulary.
func (v SIPACLEntryScope) Valid() bool {
	for _, candidate := range SIPACLEntryScopeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SIPACLEntryScope) String() string { return string(v) }

// SIPDialogClaim is the claim one sipd instance holds on a dialog, in the sip-dialogs KV bucket.
type SIPDialogClaim struct {
	LegID         string             `json:"legId"`
	InstanceID    string             `json:"instanceId"`
	OrgID         *string            `json:"orgId,omitempty"`
	CallID        *string            `json:"callId,omitempty"`
	Role          SIPDialogClaimRole `json:"role"`
	SIPCallID     string             `json:"sipCallId"`
	LocalTag      *string            `json:"localTag,omitempty"`
	RemoteTag     *string            `json:"remoteTag,omitempty"`
	State         string             `json:"state"`
	RemoteAddress *string            `json:"remoteAddress,omitempty"`
	Transport     *SIPTransport      `json:"transport,omitempty"`
	TrunkID       *string            `json:"trunkId,omitempty"`
	Profile       *string            `json:"profile,omitempty"`
	CreatedAt     float64            `json:"createdAt"`
	ExpiresAt     float64            `json:"expiresAt"`

	// Extra carries every key outside the pinned contract, verbatim. The TS schema is a
	// z.looseObject (see cdr-events.ts) precisely so a producer running ahead of the
	// consumer is not silently truncated; dropping these on the Go side would reintroduce
	// the loss the loose schema exists to prevent.
	Extra map[string]json.RawMessage `json:"-"`
}

// MarshalJSON merges Extra back into the object, pinned fields winning on conflict.
func (v SIPDialogClaim) MarshalJSON() ([]byte, error) {
	type alias SIPDialogClaim
	return marshalWithExtras(alias(v), v.Extra)
}

// UnmarshalJSON captures unknown keys into Extra instead of discarding them.
func (v *SIPDialogClaim) UnmarshalJSON(data []byte) error {
	type alias SIPDialogClaim
	var inner alias
	extra, err := unmarshalWithExtras(data, &inner, knownKeysSIPDialogClaim)
	if err != nil {
		return err
	}
	*v = SIPDialogClaim(inner)
	v.Extra = extra
	return nil
}

var knownKeysSIPDialogClaim = map[string]struct{}{
	"legId":         {},
	"instanceId":    {},
	"orgId":         {},
	"callId":        {},
	"role":          {},
	"sipCallId":     {},
	"localTag":      {},
	"remoteTag":     {},
	"state":         {},
	"remoteAddress": {},
	"transport":     {},
	"trunkId":       {},
	"profile":       {},
	"createdAt":     {},
	"expiresAt":     {},
}

// SIPDialogClaimRole is the closed vocabulary of SIPDialogClaim.role.
type SIPDialogClaimRole string

const (
	SIPDialogClaimRoleUas SIPDialogClaimRole = "uas"
	SIPDialogClaimRoleUac SIPDialogClaimRole = "uac"
)

// SIPDialogClaimRoleValues lists every member of the vocabulary, in contract order.
var SIPDialogClaimRoleValues = []SIPDialogClaimRole{
	SIPDialogClaimRoleUas,
	SIPDialogClaimRoleUac,
}

// Valid reports whether v is a member of the SIPDialogClaimRole vocabulary.
func (v SIPDialogClaimRole) Valid() bool {
	for _, candidate := range SIPDialogClaimRoleValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SIPDialogClaimRole) String() string { return string(v) }

// ExtensionPresenceValue is the value a busy-lamp key renders, in the presence KV bucket.
type ExtensionPresenceValue struct {
	OrgID           string                      `json:"orgId"`
	ExtensionNumber string                      `json:"extensionNumber"`
	State           ExtensionPresenceValueState `json:"state"`
	ChannelCount    int                         `json:"channelCount"`
	CallStates      []string                    `json:"callStates,omitempty"`
	WrittenBy       *string                     `json:"writtenBy,omitempty"`
	UpdatedAt       float64                     `json:"updatedAt"`

	// Extra carries every key outside the pinned contract, verbatim. The TS schema is a
	// z.looseObject (see cdr-events.ts) precisely so a producer running ahead of the
	// consumer is not silently truncated; dropping these on the Go side would reintroduce
	// the loss the loose schema exists to prevent.
	Extra map[string]json.RawMessage `json:"-"`
}

// MarshalJSON merges Extra back into the object, pinned fields winning on conflict.
func (v ExtensionPresenceValue) MarshalJSON() ([]byte, error) {
	type alias ExtensionPresenceValue
	return marshalWithExtras(alias(v), v.Extra)
}

// UnmarshalJSON captures unknown keys into Extra instead of discarding them.
func (v *ExtensionPresenceValue) UnmarshalJSON(data []byte) error {
	type alias ExtensionPresenceValue
	var inner alias
	extra, err := unmarshalWithExtras(data, &inner, knownKeysExtensionPresenceValue)
	if err != nil {
		return err
	}
	*v = ExtensionPresenceValue(inner)
	v.Extra = extra
	return nil
}

var knownKeysExtensionPresenceValue = map[string]struct{}{
	"orgId":           {},
	"extensionNumber": {},
	"state":           {},
	"channelCount":    {},
	"callStates":      {},
	"writtenBy":       {},
	"updatedAt":       {},
}

// ExtensionPresenceValueState is the closed vocabulary of ExtensionPresenceValue.state.
type ExtensionPresenceValueState string

const (
	ExtensionPresenceValueStateDown        ExtensionPresenceValueState = "down"
	ExtensionPresenceValueStateRinging     ExtensionPresenceValueState = "ringing"
	ExtensionPresenceValueStateActive      ExtensionPresenceValueState = "active"
	ExtensionPresenceValueStateActiveMulti ExtensionPresenceValueState = "active-multi"
	ExtensionPresenceValueStateHeld        ExtensionPresenceValueState = "held"
	ExtensionPresenceValueStateUnheld      ExtensionPresenceValueState = "unheld"
	ExtensionPresenceValueStateHangup      ExtensionPresenceValueState = "hangup"
)

// ExtensionPresenceValueStateValues lists every member of the vocabulary, in contract order.
var ExtensionPresenceValueStateValues = []ExtensionPresenceValueState{
	ExtensionPresenceValueStateDown,
	ExtensionPresenceValueStateRinging,
	ExtensionPresenceValueStateActive,
	ExtensionPresenceValueStateActiveMulti,
	ExtensionPresenceValueStateHeld,
	ExtensionPresenceValueStateUnheld,
	ExtensionPresenceValueStateHangup,
}

// Valid reports whether v is a member of the ExtensionPresenceValueState vocabulary.
func (v ExtensionPresenceValueState) Valid() bool {
	for _, candidate := range ExtensionPresenceValueStateValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v ExtensionPresenceValueState) String() string { return string(v) }

// MediaSessionDirectoryValue is the mediad session directory value, in the media-sessions KV bucket.
type MediaSessionDirectoryValue struct {
	SessionID   string  `json:"sessionId"`
	InstanceID  string  `json:"instanceId"`
	OrgID       string  `json:"orgId"`
	CallID      string  `json:"callId"`
	LegID       *string `json:"legId,omitempty"`
	Address     string  `json:"address"`
	RtpPort     int     `json:"rtpPort"`
	RtcpPort    int     `json:"rtcpPort"`
	Codec       *string `json:"codec,omitempty"`
	BridgeID    *string `json:"bridgeId,omitempty"`
	AllocatedAt float64 `json:"allocatedAt"`

	// Extra carries every key outside the pinned contract, verbatim. The TS schema is a
	// z.looseObject (see cdr-events.ts) precisely so a producer running ahead of the
	// consumer is not silently truncated; dropping these on the Go side would reintroduce
	// the loss the loose schema exists to prevent.
	Extra map[string]json.RawMessage `json:"-"`
}

// MarshalJSON merges Extra back into the object, pinned fields winning on conflict.
func (v MediaSessionDirectoryValue) MarshalJSON() ([]byte, error) {
	type alias MediaSessionDirectoryValue
	return marshalWithExtras(alias(v), v.Extra)
}

// UnmarshalJSON captures unknown keys into Extra instead of discarding them.
func (v *MediaSessionDirectoryValue) UnmarshalJSON(data []byte) error {
	type alias MediaSessionDirectoryValue
	var inner alias
	extra, err := unmarshalWithExtras(data, &inner, knownKeysMediaSessionDirectoryValue)
	if err != nil {
		return err
	}
	*v = MediaSessionDirectoryValue(inner)
	v.Extra = extra
	return nil
}

var knownKeysMediaSessionDirectoryValue = map[string]struct{}{
	"sessionId":   {},
	"instanceId":  {},
	"orgId":       {},
	"callId":      {},
	"legId":       {},
	"address":     {},
	"rtpPort":     {},
	"rtcpPort":    {},
	"codec":       {},
	"bridgeId":    {},
	"allocatedAt": {},
}
