// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Payloads for the media event family.

package events

// Event types carried on the media family's subjects. The value is the envelope's
// `type` discriminator, which is unique WITHIN the family only.
const (
	EventTypeMediaSessionEnded      = "session.ended"
	EventTypeMediaSessionRTPTimeout = "session.rtp-timeout"
	EventTypeMediaPlaybackFinished  = "playback.finished"
	EventTypeMediaRecordingFinished = "recording.finished"
	EventTypeMediaDtmfReceived      = "dtmf.received"
)

// MediaSessionEndedData is the payload of the "session.ended" event.
//
// Subject: media.evt.v1.<orgId>.<sessionId>.session.ended
// Envelope: Envelope[MediaSessionEndedData]
type MediaSessionEndedData struct {
	SessionID       string                    `json:"sessionId"`
	InstanceID      string                    `json:"instanceId"`
	CallID          *string                   `json:"callId,omitempty"`
	LegID           *string                   `json:"legId,omitempty"`
	RtpPort         int                       `json:"rtpPort"`
	PacketsReceived int                       `json:"packetsReceived"`
	PacketsSent     int                       `json:"packetsSent"`
	Reason          MediaSessionEndedReason   `json:"reason"`
	DurationMs      int                       `json:"durationMs"`
	Detail          *string                   `json:"detail,omitempty"`
	Quality         *MediaSessionEndedQuality `json:"quality,omitempty"`
}

// MediaSessionEndedReason is the closed vocabulary of MediaSessionEndedData.reason.
type MediaSessionEndedReason string

const (
	MediaSessionEndedReasonReleased   MediaSessionEndedReason = "released"
	MediaSessionEndedReasonRtpTimeout MediaSessionEndedReason = "rtp-timeout"
	MediaSessionEndedReasonIdleReaped MediaSessionEndedReason = "idle-reaped"
	MediaSessionEndedReasonDrained    MediaSessionEndedReason = "drained"
	MediaSessionEndedReasonError      MediaSessionEndedReason = "error"
)

// MediaSessionEndedReasonValues lists every member of the vocabulary, in contract order.
var MediaSessionEndedReasonValues = []MediaSessionEndedReason{
	MediaSessionEndedReasonReleased,
	MediaSessionEndedReasonRtpTimeout,
	MediaSessionEndedReasonIdleReaped,
	MediaSessionEndedReasonDrained,
	MediaSessionEndedReasonError,
}

// Valid reports whether v is a member of the MediaSessionEndedReason vocabulary.
func (v MediaSessionEndedReason) Valid() bool {
	for _, candidate := range MediaSessionEndedReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaSessionEndedReason) String() string { return string(v) }

// MediaSessionEndedQuality is a payload fragment of the contract.
type MediaSessionEndedQuality struct {
	InboundJitterMs      float64 `json:"inboundJitterMs"`
	ReportedLossFraction float64 `json:"reportedLossFraction"`
	ReportedLossTotal    int     `json:"reportedLossTotal"`
	ReportedJitterMs     float64 `json:"reportedJitterMs"`
	RoundTripMs          float64 `json:"roundTripMs"`
	ReportsReceived      int     `json:"reportsReceived"`
	ReportsSent          int     `json:"reportsSent"`
	Malformed            int     `json:"malformed"`
	LastReportUnixMs     int     `json:"lastReportUnixMs"`
}

// MediaSessionRTPTimeoutData is the payload of the "session.rtp-timeout" event.
//
// Subject: media.evt.v1.<orgId>.<sessionId>.session.rtp-timeout
// Envelope: Envelope[MediaSessionRTPTimeoutData]
type MediaSessionRTPTimeoutData struct {
	SessionID       string  `json:"sessionId"`
	InstanceID      string  `json:"instanceId"`
	CallID          *string `json:"callId,omitempty"`
	LegID           *string `json:"legId,omitempty"`
	RtpPort         int     `json:"rtpPort"`
	PacketsReceived int     `json:"packetsReceived"`
	PacketsSent     int     `json:"packetsSent"`
	SilentForMs     int     `json:"silentForMs"`
	RemoteAddress   *string `json:"remoteAddress,omitempty"`
}

// MediaPlaybackFinishedData is the payload of the "playback.finished" event.
//
// Subject: media.evt.v1.<orgId>.<sessionId>.playback.finished
// Envelope: Envelope[MediaPlaybackFinishedData]
type MediaPlaybackFinishedData struct {
	SessionID   string                      `json:"sessionId"`
	InstanceID  string                      `json:"instanceId"`
	CallID      *string                     `json:"callId,omitempty"`
	LegID       *string                     `json:"legId,omitempty"`
	PlaybackRef string                      `json:"playbackRef"`
	Reason      MediaPlaybackFinishedReason `json:"reason"`
	PlayedMs    int                         `json:"playedMs"`
	Detail      *string                     `json:"detail,omitempty"`
}

// MediaPlaybackFinishedReason is the closed vocabulary of MediaPlaybackFinishedData.reason.
type MediaPlaybackFinishedReason string

const (
	MediaPlaybackFinishedReasonCompleted MediaPlaybackFinishedReason = "completed"
	MediaPlaybackFinishedReasonStopped   MediaPlaybackFinishedReason = "stopped"
	MediaPlaybackFinishedReasonError     MediaPlaybackFinishedReason = "error"
)

// MediaPlaybackFinishedReasonValues lists every member of the vocabulary, in contract order.
var MediaPlaybackFinishedReasonValues = []MediaPlaybackFinishedReason{
	MediaPlaybackFinishedReasonCompleted,
	MediaPlaybackFinishedReasonStopped,
	MediaPlaybackFinishedReasonError,
}

// Valid reports whether v is a member of the MediaPlaybackFinishedReason vocabulary.
func (v MediaPlaybackFinishedReason) Valid() bool {
	for _, candidate := range MediaPlaybackFinishedReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaPlaybackFinishedReason) String() string { return string(v) }

// MediaRecordingFinishedData is the payload of the "recording.finished" event.
//
// Subject: media.evt.v1.<orgId>.<sessionId>.recording.finished
// Envelope: Envelope[MediaRecordingFinishedData]
type MediaRecordingFinishedData struct {
	SessionID    string                          `json:"sessionId"`
	InstanceID   string                          `json:"instanceId"`
	CallID       *string                         `json:"callId,omitempty"`
	LegID        *string                         `json:"legId,omitempty"`
	RecordingRef string                          `json:"recordingRef"`
	Reason       MediaRecordingFinishedReason    `json:"reason"`
	DurationMs   int                             `json:"durationMs"`
	Bytes        int                             `json:"bytes"`
	ObjectKey    string                          `json:"objectKey"`
	Direction    MediaRecordingFinishedDirection `json:"direction"`
	Detail       *string                         `json:"detail,omitempty"`
}

// MediaRecordingFinishedReason is the closed vocabulary of MediaRecordingFinishedData.reason.
type MediaRecordingFinishedReason string

const (
	MediaRecordingFinishedReasonStopped      MediaRecordingFinishedReason = "stopped"
	MediaRecordingFinishedReasonMaxDuration  MediaRecordingFinishedReason = "max-duration"
	MediaRecordingFinishedReasonMaxSilence   MediaRecordingFinishedReason = "max-silence"
	MediaRecordingFinishedReasonSessionEnded MediaRecordingFinishedReason = "session-ended"
	MediaRecordingFinishedReasonError        MediaRecordingFinishedReason = "error"
)

// MediaRecordingFinishedReasonValues lists every member of the vocabulary, in contract order.
var MediaRecordingFinishedReasonValues = []MediaRecordingFinishedReason{
	MediaRecordingFinishedReasonStopped,
	MediaRecordingFinishedReasonMaxDuration,
	MediaRecordingFinishedReasonMaxSilence,
	MediaRecordingFinishedReasonSessionEnded,
	MediaRecordingFinishedReasonError,
}

// Valid reports whether v is a member of the MediaRecordingFinishedReason vocabulary.
func (v MediaRecordingFinishedReason) Valid() bool {
	for _, candidate := range MediaRecordingFinishedReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaRecordingFinishedReason) String() string { return string(v) }

// MediaRecordingFinishedDirection is the closed vocabulary of MediaRecordingFinishedData.direction.
type MediaRecordingFinishedDirection string

const (
	MediaRecordingFinishedDirectionReceive MediaRecordingFinishedDirection = "receive"
	MediaRecordingFinishedDirectionBoth    MediaRecordingFinishedDirection = "both"
)

// MediaRecordingFinishedDirectionValues lists every member of the vocabulary, in contract order.
var MediaRecordingFinishedDirectionValues = []MediaRecordingFinishedDirection{
	MediaRecordingFinishedDirectionReceive,
	MediaRecordingFinishedDirectionBoth,
}

// Valid reports whether v is a member of the MediaRecordingFinishedDirection vocabulary.
func (v MediaRecordingFinishedDirection) Valid() bool {
	for _, candidate := range MediaRecordingFinishedDirectionValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaRecordingFinishedDirection) String() string { return string(v) }

// MediaDtmfReceivedData is the payload of the "dtmf.received" event.
//
// Subject: media.evt.v1.<orgId>.<sessionId>.dtmf.received
// Envelope: Envelope[MediaDtmfReceivedData]
type MediaDtmfReceivedData struct {
	SessionID  string  `json:"sessionId"`
	InstanceID string  `json:"instanceId"`
	CallID     *string `json:"callId,omitempty"`
	LegID      *string `json:"legId,omitempty"`
	Digit      string  `json:"digit"`
	DurationMs int     `json:"durationMs"`
}
