// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Payloads for the media event family.

package events

// Event types carried on the media family's subjects. The value is the envelope's
// `type` discriminator, which is unique WITHIN the family only.
const (
	EventTypeMediaSessionEnded      = "session.ended"
	EventTypeMediaSessionRTPTimeout = "session.rtp-timeout"
)

// MediaSessionEndedData is the payload of the "session.ended" event.
//
// Subject: media.evt.v1.<orgId>.<sessionId>.session.ended
// Envelope: Envelope[MediaSessionEndedData]
type MediaSessionEndedData struct {
	SessionID       string                  `json:"sessionId"`
	InstanceID      string                  `json:"instanceId"`
	CallID          *string                 `json:"callId,omitempty"`
	LegID           *string                 `json:"legId,omitempty"`
	RtpPort         int                     `json:"rtpPort"`
	PacketsReceived int                     `json:"packetsReceived"`
	PacketsSent     int                     `json:"packetsSent"`
	Reason          MediaSessionEndedReason `json:"reason"`
	DurationMs      int                     `json:"durationMs"`
	Detail          *string                 `json:"detail,omitempty"`
}

// MediaSessionEndedReason is the closed vocabulary of MediaSessionEndedData.reason.
type MediaSessionEndedReason string

const (
	MediaSessionEndedReasonReleased   MediaSessionEndedReason = "released"
	MediaSessionEndedReasonRtpTimeout MediaSessionEndedReason = "rtp-timeout"
	MediaSessionEndedReasonIdleReaped MediaSessionEndedReason = "idle-reaped"
	MediaSessionEndedReasonDrained    MediaSessionEndedReason = "drained"
	MediaSessionEndedReasonError      MediaSessionEndedReason = "error"
)

// MediaSessionEndedReasonValues lists every member of the vocabulary, in contract order.
var MediaSessionEndedReasonValues = []MediaSessionEndedReason{
	MediaSessionEndedReasonReleased,
	MediaSessionEndedReasonRtpTimeout,
	MediaSessionEndedReasonIdleReaped,
	MediaSessionEndedReasonDrained,
	MediaSessionEndedReasonError,
}

// Valid reports whether v is a member of the MediaSessionEndedReason vocabulary.
func (v MediaSessionEndedReason) Valid() bool {
	for _, candidate := range MediaSessionEndedReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaSessionEndedReason) String() string { return string(v) }

// MediaSessionRTPTimeoutData is the payload of the "session.rtp-timeout" event.
//
// Subject: media.evt.v1.<orgId>.<sessionId>.session.rtp-timeout
// Envelope: Envelope[MediaSessionRTPTimeoutData]
type MediaSessionRTPTimeoutData struct {
	SessionID       string  `json:"sessionId"`
	InstanceID      string  `json:"instanceId"`
	CallID          *string `json:"callId,omitempty"`
	LegID           *string `json:"legId,omitempty"`
	RtpPort         int     `json:"rtpPort"`
	PacketsReceived int     `json:"packetsReceived"`
	PacketsSent     int     `json:"packetsSent"`
	SilentForMs     int     `json:"silentForMs"`
	RemoteAddress   *string `json:"remoteAddress,omitempty"`
}
