// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
// Source: packages/events/src; regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Payloads for the provision event family.

package events

import "slices"

// Event types carried on the provision family's subjects. The value is the envelope's
// `type` discriminator, which is unique WITHIN the family only.
const (
	EventTypeProvisionDeviceRequested       = "device.requested"
	EventTypeProvisionDeviceRendered        = "device.rendered"
	EventTypeProvisionDeviceRejected        = "device.rejected"
	EventTypeProvisionCredentialInvalidated = "credential.invalidated"
)

// ProvisionDeviceRequestedData is the payload of the "device.requested" event.
//
// Subject: provision.evt.v1.<orgId>
// Envelope: Envelope[ProvisionDeviceRequestedData]
type ProvisionDeviceRequestedData struct {
	SourceAddress string  `json:"sourceAddress"`
	Path          *string `json:"path,omitempty"`
	UserAgent     *string `json:"userAgent,omitempty"`
	MACAddress    string  `json:"macAddress"`
	Vendor        *string `json:"vendor,omitempty"`
	Model         *string `json:"model,omitempty"`
}

// ProvisionDeviceRenderedData is the payload of the "device.rendered" event.
//
// Subject: provision.evt.v1.<orgId>
// Envelope: Envelope[ProvisionDeviceRenderedData]
type ProvisionDeviceRenderedData struct {
	SourceAddress   string  `json:"sourceAddress"`
	Path            *string `json:"path,omitempty"`
	UserAgent       *string `json:"userAgent,omitempty"`
	MACAddress      string  `json:"macAddress"`
	Vendor          string  `json:"vendor"`
	Model           string  `json:"model"`
	DeviceID        string  `json:"deviceId"`
	TemplateID      string  `json:"templateId"`
	DeviceProfileID *string `json:"deviceProfileId,omitempty"`
	Bytes           int     `json:"bytes"`
}

// ProvisionDeviceRejectedData is the payload of the "device.rejected" event.
//
// Subject: provision.evt.v1.<orgId>
// Envelope: Envelope[ProvisionDeviceRejectedData]
type ProvisionDeviceRejectedData struct {
	SourceAddress string                        `json:"sourceAddress"`
	Path          *string                       `json:"path,omitempty"`
	UserAgent     *string                       `json:"userAgent,omitempty"`
	MACAddress    *string                       `json:"macAddress,omitempty"`
	Reason        ProvisionDeviceRejectedReason `json:"reason"`
	Detail        *string                       `json:"detail,omitempty"`
}

// ProvisionDeviceRejectedReason is the closed vocabulary of ProvisionDeviceRejectedData.reason.
type ProvisionDeviceRejectedReason string

const (
	ProvisionDeviceRejectedReasonUnknownMAC      ProvisionDeviceRejectedReason = "unknown-mac"
	ProvisionDeviceRejectedReasonInvalidToken    ProvisionDeviceRejectedReason = "invalid-token"
	ProvisionDeviceRejectedReasonMissingToken    ProvisionDeviceRejectedReason = "missing-token"
	ProvisionDeviceRejectedReasonUnknownVendor   ProvisionDeviceRejectedReason = "unknown-vendor"
	ProvisionDeviceRejectedReasonTemplateMissing ProvisionDeviceRejectedReason = "template-missing"
	ProvisionDeviceRejectedReasonRateLimited     ProvisionDeviceRejectedReason = "rate-limited"
	ProvisionDeviceRejectedReasonDisabled        ProvisionDeviceRejectedReason = "disabled"
	ProvisionDeviceRejectedReasonIPNotAllowed    ProvisionDeviceRejectedReason = "ip-not-allowed"
	ProvisionDeviceRejectedReasonNotConfigured   ProvisionDeviceRejectedReason = "not-configured"
)

// ProvisionDeviceRejectedReasonValues lists every member of the vocabulary, in contract order.
var ProvisionDeviceRejectedReasonValues = []ProvisionDeviceRejectedReason{
	ProvisionDeviceRejectedReasonUnknownMAC,
	ProvisionDeviceRejectedReasonInvalidToken,
	ProvisionDeviceRejectedReasonMissingToken,
	ProvisionDeviceRejectedReasonUnknownVendor,
	ProvisionDeviceRejectedReasonTemplateMissing,
	ProvisionDeviceRejectedReasonRateLimited,
	ProvisionDeviceRejectedReasonDisabled,
	ProvisionDeviceRejectedReasonIPNotAllowed,
	ProvisionDeviceRejectedReasonNotConfigured,
}

// Valid reports whether v is a member of the ProvisionDeviceRejectedReason vocabulary.
func (v ProvisionDeviceRejectedReason) Valid() bool {
	return slices.Contains(ProvisionDeviceRejectedReasonValues, v)
}

func (v ProvisionDeviceRejectedReason) String() string { return string(v) }

// ProvisionCredentialInvalidatedData is the payload of the "credential.invalidated" event.
//
// Subject: provision.evt.v1.<orgId>
// Envelope: Envelope[ProvisionCredentialInvalidatedData]
type ProvisionCredentialInvalidatedData struct {
	Reason  string `json:"reason"`
	Dropped int    `json:"dropped"`
}
