// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
// Source: packages/events/src; regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Payloads for the queue event family.

package events

import "slices"

// Event types carried on the queue family's subjects. The value is the envelope's
// `type` discriminator, which is unique WITHIN the family only.
const (
	EventTypeQueueCallerJoined    = "caller.joined"
	EventTypeQueueCallerAnswered  = "caller.answered"
	EventTypeQueueCallerAbandoned = "caller.abandoned"
	EventTypeQueueAgentState      = "agent.state"
	EventTypeQueueCallbackPlaced  = "callback.placed"
	EventTypeQueueCallbackFailed  = "callback.failed"
)

// QueueCallerJoinedData is the payload of the "caller.joined" event.
//
// Subject: queue.evt.v1.<orgId>.<queueId>.caller.joined
// Envelope: Envelope[QueueCallerJoinedData]
type QueueCallerJoinedData struct {
	CallID       string  `json:"callId"`
	LegID        string  `json:"legId"`
	Position     int     `json:"position"`
	Priority     int     `json:"priority"`
	CallerNumber *string `json:"callerNumber,omitempty"`
	Resumed      *bool   `json:"resumed,omitempty"`
}

// QueueCallerAnsweredData is the payload of the "caller.answered" event.
//
// Subject: queue.evt.v1.<orgId>.<queueId>.caller.answered
// Envelope: Envelope[QueueCallerAnsweredData]
type QueueCallerAnsweredData struct {
	CallID   string                       `json:"callId"`
	LegID    string                       `json:"legId"`
	AgentID  string                       `json:"agentId"`
	WaitMs   int                          `json:"waitMs"`
	Strategy *QueueCallerAnsweredStrategy `json:"strategy,omitempty"`
}

// QueueCallerAnsweredStrategy is the closed vocabulary of QueueCallerAnsweredData.strategy.
type QueueCallerAnsweredStrategy string

const (
	QueueCallerAnsweredStrategyLongestIdle QueueCallerAnsweredStrategy = "longest-idle"
	QueueCallerAnsweredStrategyRingAll     QueueCallerAnsweredStrategy = "ring-all"
	QueueCallerAnsweredStrategyRoundRobin  QueueCallerAnsweredStrategy = "round-robin"
	QueueCallerAnsweredStrategyTopDown     QueueCallerAnsweredStrategy = "top-down"
	QueueCallerAnsweredStrategySequential  QueueCallerAnsweredStrategy = "sequential"
	QueueCallerAnsweredStrategyRandom      QueueCallerAnsweredStrategy = "random"
)

// QueueCallerAnsweredStrategyValues lists every member of the vocabulary, in contract order.
var QueueCallerAnsweredStrategyValues = []QueueCallerAnsweredStrategy{
	QueueCallerAnsweredStrategyLongestIdle,
	QueueCallerAnsweredStrategyRingAll,
	QueueCallerAnsweredStrategyRoundRobin,
	QueueCallerAnsweredStrategyTopDown,
	QueueCallerAnsweredStrategySequential,
	QueueCallerAnsweredStrategyRandom,
}

// Valid reports whether v is a member of the QueueCallerAnsweredStrategy vocabulary.
func (v QueueCallerAnsweredStrategy) Valid() bool {
	return slices.Contains(QueueCallerAnsweredStrategyValues, v)
}

func (v QueueCallerAnsweredStrategy) String() string { return string(v) }

// QueueCallerAbandonedData is the payload of the "caller.abandoned" event.
//
// Subject: queue.evt.v1.<orgId>.<queueId>.caller.abandoned
// Envelope: Envelope[QueueCallerAbandonedData]
type QueueCallerAbandonedData struct {
	CallID   string                      `json:"callId"`
	LegID    string                      `json:"legId"`
	WaitMs   int                         `json:"waitMs"`
	Position *int                        `json:"position,omitempty"`
	Reason   *QueueCallerAbandonedReason `json:"reason,omitempty"`
	ExitKey  *string                     `json:"exitKey,omitempty"`
}

// QueueCallerAbandonedReason is the closed vocabulary of QueueCallerAbandonedData.reason.
type QueueCallerAbandonedReason string

const (
	QueueCallerAbandonedReasonCallerHangup QueueCallerAbandonedReason = "caller-hangup"
	QueueCallerAbandonedReasonTimeout      QueueCallerAbandonedReason = "timeout"
	QueueCallerAbandonedReasonOverflow     QueueCallerAbandonedReason = "overflow"
	QueueCallerAbandonedReasonNoAgents     QueueCallerAbandonedReason = "no-agents"
	QueueCallerAbandonedReasonExitKey      QueueCallerAbandonedReason = "exit-key"
	QueueCallerAbandonedReasonCallback     QueueCallerAbandonedReason = "callback"
)

// QueueCallerAbandonedReasonValues lists every member of the vocabulary, in contract order.
var QueueCallerAbandonedReasonValues = []QueueCallerAbandonedReason{
	QueueCallerAbandonedReasonCallerHangup,
	QueueCallerAbandonedReasonTimeout,
	QueueCallerAbandonedReasonOverflow,
	QueueCallerAbandonedReasonNoAgents,
	QueueCallerAbandonedReasonExitKey,
	QueueCallerAbandonedReasonCallback,
}

// Valid reports whether v is a member of the QueueCallerAbandonedReason vocabulary.
func (v QueueCallerAbandonedReason) Valid() bool {
	return slices.Contains(QueueCallerAbandonedReasonValues, v)
}

func (v QueueCallerAbandonedReason) String() string { return string(v) }

// QueueAgentStateData is the payload of the "agent.state" event.
//
// Subject: queue.evt.v1.<orgId>.<queueId>.agent.state
// Envelope: Envelope[QueueAgentStateData]
type QueueAgentStateData struct {
	AgentID        string       `json:"agentId"`
	Status         AgentStatus  `json:"status"`
	PreviousStatus *AgentStatus `json:"previousStatus,omitempty"`
	QueueIDs       []string     `json:"queueIds,omitempty"`
	Reason         *string      `json:"reason,omitempty"`
}

// QueueCallbackPlacedData is the payload of the "callback.placed" event.
//
// Subject: queue.evt.v1.<orgId>.<queueId>.callback.placed
// Envelope: Envelope[QueueCallbackPlacedData]
type QueueCallbackPlacedData struct {
	CallID         string  `json:"callId"`
	OriginalCallID *string `json:"originalCallId,omitempty"`
	CallerNumber   string  `json:"callerNumber"`
	Attempts       int     `json:"attempts"`
	HeldMs         int     `json:"heldMs"`
}

// QueueCallbackFailedData is the payload of the "callback.failed" event.
//
// Subject: queue.evt.v1.<orgId>.<queueId>.callback.failed
// Envelope: Envelope[QueueCallbackFailedData]
type QueueCallbackFailedData struct {
	CallerNumber string  `json:"callerNumber"`
	Attempts     int     `json:"attempts"`
	Dropped      bool    `json:"dropped"`
	Reason       *string `json:"reason,omitempty"`
}
