// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
// Source: packages/events/src; regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// The contract's event-type registry: everything a generic consumer needs to route a message.

package events

// EventTypeInfo describes one event type in the contract.
type EventTypeInfo struct {
	// Family is the subject family the type belongs to.
	Family EventFamily
	// Type is the envelope's `type` discriminator.
	Type string
	// SubjectTemplate documents the subject shape, with <> placeholders.
	SubjectTemplate string
}

// EventTypes lists every event type in the contract, in declaration order.
var EventTypes = []EventTypeInfo{
	{Family: FamilyCall, Type: EventTypeChannelCreated, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.created"},
	{Family: FamilyCall, Type: EventTypeChannelRinging, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.ringing"},
	{Family: FamilyCall, Type: EventTypeChannelEarlyMedia, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.early-media"},
	{Family: FamilyCall, Type: EventTypeChannelAnswered, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.answered"},
	{Family: FamilyCall, Type: EventTypeChannelBridged, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.bridged"},
	{Family: FamilyCall, Type: EventTypeChannelUnbridged, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.unbridged"},
	{Family: FamilyCall, Type: EventTypeChannelHeld, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.held"},
	{Family: FamilyCall, Type: EventTypeChannelUnheld, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.unheld"},
	{Family: FamilyCall, Type: EventTypeChannelDTMF, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.dtmf"},
	{Family: FamilyCall, Type: EventTypeChannelRecordStarted, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.record.started"},
	{Family: FamilyCall, Type: EventTypeChannelRecordStopped, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.record.stopped"},
	{Family: FamilyCall, Type: EventTypeChannelHangup, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.hangup"},
	{Family: FamilyCall, Type: EventTypeChannelDestroyed, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.destroyed"},
	{Family: FamilyCall, Type: EventTypeConferenceJoined, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.conference.joined"},
	{Family: FamilyCall, Type: EventTypeConferenceLeft, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.conference.left"},
	{Family: FamilyCall, Type: EventTypeConferenceParticipantUpdated, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.conference.participant.updated"},
	{Family: FamilyCall, Type: EventTypeConferenceLocked, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.conference.locked"},
	{Family: FamilyCall, Type: EventTypeConferenceUnlocked, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.conference.unlocked"},
	{Family: FamilyCall, Type: EventTypeCallParked, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.parked"},
	{Family: FamilyCall, Type: EventTypeCallUnparked, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.unparked"},
	{Family: FamilyCall, Type: EventTypeCallTransferred, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.transferred"},
	{Family: FamilyCall, Type: EventTypeCallPickedUp, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.picked-up"},
	{Family: FamilyCall, Type: EventTypeCallEmergencyDialed, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.emergency.dialed"},
	{Family: FamilyCall, Type: EventTypeCallTapStarted, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.tap.started"},
	{Family: FamilyCall, Type: EventTypeCallTapEnded, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.tap.ended"},
	{Family: FamilyCall, Type: EventTypeCallPagingStarted, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.paging.started"},
	{Family: FamilyCall, Type: EventTypeCallPagingEnded, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.paging.ended"},
	{Family: FamilyRegistration, Type: EventTypeRegistrationRegistered, SubjectTemplate: "sip.reg.v1.<orgId>.<aorHash>.registered"},
	{Family: FamilyRegistration, Type: EventTypeRegistrationUnregistered, SubjectTemplate: "sip.reg.v1.<orgId>.<aorHash>.unregistered"},
	{Family: FamilyRegistration, Type: EventTypeRegistrationExpired, SubjectTemplate: "sip.reg.v1.<orgId>.<aorHash>.expired"},
	{Family: FamilyRegistration, Type: EventTypeRegistrationAuthFailed, SubjectTemplate: "sip.reg.v1.<orgId>.<aorHash>.auth-failed"},
	{Family: FamilySIPDialog, Type: EventTypeSIPDialogProgressed, SubjectTemplate: "sip.evt.v1.<orgId>.<legId>.dialog.progressed"},
	{Family: FamilySIPDialog, Type: EventTypeSIPDialogAnswered, SubjectTemplate: "sip.evt.v1.<orgId>.<legId>.dialog.answered"},
	{Family: FamilySIPDialog, Type: EventTypeSIPDialogHeld, SubjectTemplate: "sip.evt.v1.<orgId>.<legId>.dialog.held"},
	{Family: FamilySIPDialog, Type: EventTypeSIPDialogResumed, SubjectTemplate: "sip.evt.v1.<orgId>.<legId>.dialog.resumed"},
	{Family: FamilySIPDialog, Type: EventTypeSIPDialogTerminated, SubjectTemplate: "sip.evt.v1.<orgId>.<legId>.dialog.terminated"},
	{Family: FamilySIPDialog, Type: EventTypeSIPDialogDTMF, SubjectTemplate: "sip.evt.v1.<orgId>.<legId>.dialog.dtmf"},
	{Family: FamilyQueue, Type: EventTypeQueueCallerJoined, SubjectTemplate: "queue.evt.v1.<orgId>.<queueId>.caller.joined"},
	{Family: FamilyQueue, Type: EventTypeQueueCallerAnswered, SubjectTemplate: "queue.evt.v1.<orgId>.<queueId>.caller.answered"},
	{Family: FamilyQueue, Type: EventTypeQueueCallerAbandoned, SubjectTemplate: "queue.evt.v1.<orgId>.<queueId>.caller.abandoned"},
	{Family: FamilyQueue, Type: EventTypeQueueAgentState, SubjectTemplate: "queue.evt.v1.<orgId>.<queueId>.agent.state"},
	{Family: FamilyQueue, Type: EventTypeQueueCallbackPlaced, SubjectTemplate: "queue.evt.v1.<orgId>.<queueId>.callback.placed"},
	{Family: FamilyQueue, Type: EventTypeQueueCallbackFailed, SubjectTemplate: "queue.evt.v1.<orgId>.<queueId>.callback.failed"},
	{Family: FamilyVoicemail, Type: EventTypeVoicemailMessageLeft, SubjectTemplate: "voicemail.evt.v1.<orgId>.<mailboxId>.message.left"},
	{Family: FamilyVoicemail, Type: EventTypeVoicemailMWIUpdated, SubjectTemplate: "voicemail.evt.v1.<orgId>.<mailboxId>.mwi.updated"},
	{Family: FamilyMedia, Type: EventTypeMediaSessionEnded, SubjectTemplate: "media.evt.v1.<orgId>.<sessionId>.session.ended"},
	{Family: FamilyMedia, Type: EventTypeMediaSessionRTPTimeout, SubjectTemplate: "media.evt.v1.<orgId>.<sessionId>.session.rtp-timeout"},
	{Family: FamilyMedia, Type: EventTypeMediaPlaybackFinished, SubjectTemplate: "media.evt.v1.<orgId>.<sessionId>.playback.finished"},
	{Family: FamilyMedia, Type: EventTypeMediaRecordingFinished, SubjectTemplate: "media.evt.v1.<orgId>.<sessionId>.recording.finished"},
	{Family: FamilyMedia, Type: EventTypeMediaDtmfReceived, SubjectTemplate: "media.evt.v1.<orgId>.<sessionId>.dtmf.received"},
	{Family: FamilyTrunk, Type: EventTypeTrunkStatusChanged, SubjectTemplate: "trunk.evt.v1.<orgId>.<trunkId>.status.changed"},
	{Family: FamilySecurity, Type: EventTypeSecurityFraudSignal, SubjectTemplate: "security.evt.v1.<orgId>.<subjectRef>.fraud-signal"},
	{Family: FamilyCDR, Type: EventTypeCDRLegWrite, SubjectTemplate: "cdr.leg.v1.<orgId>"},
	{Family: FamilyAudit, Type: EventTypeAuditRecorded, SubjectTemplate: "audit.evt.v1.<orgId>"},
	{Family: FamilyProvision, Type: EventTypeProvisionDeviceRequested, SubjectTemplate: "provision.evt.v1.<orgId>"},
	{Family: FamilyProvision, Type: EventTypeProvisionDeviceRendered, SubjectTemplate: "provision.evt.v1.<orgId>"},
	{Family: FamilyProvision, Type: EventTypeProvisionDeviceRejected, SubjectTemplate: "provision.evt.v1.<orgId>"},
	{Family: FamilyProvision, Type: EventTypeProvisionCredentialInvalidated, SubjectTemplate: "provision.evt.v1.<orgId>"},
}

// NewDataFor returns a pointer to a zero payload struct for eventType, or nil when the
// type is not part of this contract version.
//
// A v1.n producer may emit a type a v1.0 consumer has never heard of (envelope.ts:
// additive-only evolution), so a nil result is a normal outcome, not an error.
func NewDataFor(eventType string) any {
	switch eventType {
	case EventTypeChannelCreated:
		return new(ChannelCreatedData)
	case EventTypeChannelRinging:
		return new(ChannelRingingData)
	case EventTypeChannelEarlyMedia:
		return new(ChannelEarlyMediaData)
	case EventTypeChannelAnswered:
		return new(ChannelAnsweredData)
	case EventTypeChannelBridged:
		return new(ChannelBridgedData)
	case EventTypeChannelUnbridged:
		return new(ChannelUnbridgedData)
	case EventTypeChannelHeld:
		return new(ChannelHeldData)
	case EventTypeChannelUnheld:
		return new(ChannelUnheldData)
	case EventTypeChannelDTMF:
		return new(ChannelDTMFData)
	case EventTypeChannelRecordStarted:
		return new(ChannelRecordStartedData)
	case EventTypeChannelRecordStopped:
		return new(ChannelRecordStoppedData)
	case EventTypeChannelHangup:
		return new(ChannelHangupData)
	case EventTypeChannelDestroyed:
		return new(ChannelDestroyedData)
	case EventTypeConferenceJoined:
		return new(ConferenceJoinedData)
	case EventTypeConferenceLeft:
		return new(ConferenceLeftData)
	case EventTypeConferenceParticipantUpdated:
		return new(ConferenceParticipantUpdatedData)
	case EventTypeConferenceLocked:
		return new(ConferenceLockedData)
	case EventTypeConferenceUnlocked:
		return new(ConferenceUnlockedData)
	case EventTypeCallParked:
		return new(CallParkedData)
	case EventTypeCallUnparked:
		return new(CallUnparkedData)
	case EventTypeCallTransferred:
		return new(CallTransferredData)
	case EventTypeCallPickedUp:
		return new(CallPickedUpData)
	case EventTypeCallEmergencyDialed:
		return new(CallEmergencyDialedData)
	case EventTypeCallTapStarted:
		return new(CallTapStartedData)
	case EventTypeCallTapEnded:
		return new(CallTapEndedData)
	case EventTypeCallPagingStarted:
		return new(CallPagingStartedData)
	case EventTypeCallPagingEnded:
		return new(CallPagingEndedData)
	case EventTypeRegistrationRegistered:
		return new(RegistrationRegisteredData)
	case EventTypeRegistrationUnregistered:
		return new(RegistrationUnregisteredData)
	case EventTypeRegistrationExpired:
		return new(RegistrationExpiredData)
	case EventTypeRegistrationAuthFailed:
		return new(RegistrationAuthFailedData)
	case EventTypeSIPDialogProgressed:
		return new(SIPDialogProgressedData)
	case EventTypeSIPDialogAnswered:
		return new(SIPDialogAnsweredData)
	case EventTypeSIPDialogHeld:
		return new(SIPDialogHeldData)
	case EventTypeSIPDialogResumed:
		return new(SIPDialogResumedData)
	case EventTypeSIPDialogTerminated:
		return new(SIPDialogTerminatedData)
	case EventTypeSIPDialogDTMF:
		return new(SIPDialogDTMFData)
	case EventTypeQueueCallerJoined:
		return new(QueueCallerJoinedData)
	case EventTypeQueueCallerAnswered:
		return new(QueueCallerAnsweredData)
	case EventTypeQueueCallerAbandoned:
		return new(QueueCallerAbandonedData)
	case EventTypeQueueAgentState:
		return new(QueueAgentStateData)
	case EventTypeQueueCallbackPlaced:
		return new(QueueCallbackPlacedData)
	case EventTypeQueueCallbackFailed:
		return new(QueueCallbackFailedData)
	case EventTypeVoicemailMessageLeft:
		return new(VoicemailMessageLeftData)
	case EventTypeVoicemailMWIUpdated:
		return new(VoicemailMWIUpdatedData)
	case EventTypeMediaSessionEnded:
		return new(MediaSessionEndedData)
	case EventTypeMediaSessionRTPTimeout:
		return new(MediaSessionRTPTimeoutData)
	case EventTypeMediaPlaybackFinished:
		return new(MediaPlaybackFinishedData)
	case EventTypeMediaRecordingFinished:
		return new(MediaRecordingFinishedData)
	case EventTypeMediaDtmfReceived:
		return new(MediaDtmfReceivedData)
	case EventTypeTrunkStatusChanged:
		return new(TrunkStatusChangedData)
	case EventTypeSecurityFraudSignal:
		return new(SecurityFraudSignalData)
	case EventTypeCDRLegWrite:
		return new(CDRLegWriteData)
	case EventTypeAuditRecorded:
		return new(AuditRecordedData)
	case EventTypeProvisionDeviceRequested:
		return new(ProvisionDeviceRequestedData)
	case EventTypeProvisionDeviceRendered:
		return new(ProvisionDeviceRenderedData)
	case EventTypeProvisionDeviceRejected:
		return new(ProvisionDeviceRejectedData)
	case EventTypeProvisionCredentialInvalidated:
		return new(ProvisionCredentialInvalidatedData)
	}
	return nil
}

// NewRPCRequestFor returns a pointer to a zero request struct for an rpc.* subject, or nil
// when the subject is not part of this contract version.
//
// Instance-addressed subjects carry a variable tail; pass the PREFIX (ParsedSubject.Method
// without Target), which is what RPC_SUBJECTS names.
func NewRPCRequestFor(subject string) any {
	switch subject {
	case SubjectRoutingResolveRPC:
		return new(RoutingResolveRequest)
	case SubjectAuthzCheckRPC:
		return new(AuthzCheckRequest)
	case SubjectVoicemailListRPC:
		return new(VoicemailListRequest)
	case SubjectAuthorizeOutboundRPC:
		return new(AuthorizeOutboundRequest)
	case SubjectExtensionFeatureRPC:
		return new(ExtensionFeatureRequest)
	case SubjectToggleFeatureRPC:
		return new(ToggleFeatureRequest)
	case SubjectHotDeskRPC:
		return new(HotDeskRequest)
	case SubjectLastCallerRPC:
		return new(LastCallerRequest)
	case SubjectFileGreetingRPC:
		return new(FileGreetingRequest)
	case SubjectQueueDispositionRPC:
		return new(QueueDispositionRequest)
	case SubjectQueueSurveyRPC:
		return new(QueueSurveyRequest)
	case SubjectSipCredentialRPC:
		return new(SipCredentialRequest)
	case SubjectSipTrunkCredentialRPC:
		return new(SipTrunkCredentialRequest)
	case SubjectSipTransferRPC:
		return new(SipTransferRequest)
	case SubjectSipInviteRPC:
		return new(SipInviteRequest)
	case SubjectSipRingRPC:
		return new(SipRingRequest)
	case SubjectSipAnswerRPC:
		return new(SipAnswerRequest)
	case SubjectSipHangupRPC:
		return new(SipHangupRequest)
	case SubjectSipReinviteRPC:
		return new(SipReinviteRequest)
	case SubjectSipOriginateRPC:
		return new(SipOriginateRequest)
	case SubjectSipResolveTargetRPC:
		return new(SipResolveTargetRequest)
	case SubjectEngineRenegotiateRPC:
		return new(EngineRenegotiateRequest)
	case SubjectMediaAllocateSessionRPC:
		return new(MediaAllocateSessionRequest)
	case SubjectMediaCreateOfferRPC:
		return new(MediaCreateOfferRequest)
	case SubjectMediaAcceptAnswerRPC:
		return new(MediaAcceptAnswerRequest)
	case SubjectMediaBridgeSessionsRPC:
		return new(MediaBridgeSessionsRequest)
	case SubjectMediaUnbridgeSessionsRPC:
		return new(MediaUnbridgeSessionsRequest)
	case SubjectMediaReleaseSessionRPC:
		return new(MediaReleaseSessionRequest)
	case SubjectMediaStartPlaybackRPC:
		return new(MediaStartPlaybackRequest)
	case SubjectMediaStopPlaybackRPC:
		return new(MediaStopPlaybackRequest)
	case SubjectMediaSendDtmfRPC:
		return new(MediaSendDtmfRequest)
	case SubjectMediaStartRecordingRPC:
		return new(MediaStartRecordingRequest)
	case SubjectMediaStopRecordingRPC:
		return new(MediaStopRecordingRequest)
	case SubjectMediaPauseRecordingRPC:
		return new(MediaPauseRecordingRequest)
	case SubjectMediaTapSessionRPC:
		return new(MediaTapSessionRequest)
	case SubjectMediaUntapSessionRPC:
		return new(MediaUntapSessionRequest)
	case SubjectMediaMuteSessionRPC:
		return new(MediaMuteSessionRequest)
	case SubjectMediaHoldSessionRPC:
		return new(MediaHoldSessionRequest)
	case SubjectOriginateRPC:
		return new(OriginateRequest)
	case SubjectQueueCallbackRPC:
		return new(QueueCallbackRequest)
	case SubjectParkHandoffRPC:
		return new(ParkHandoffRequest)
	case SubjectSessionVerbRPC:
		return new(SessionVerbRequest)
	case SubjectConferenceControlRPC:
		return new(ConferenceControlRequest)
	case SubjectCallControlRPC:
		return new(CallControlRequest)
	case SubjectSessionAnnounceRPC:
		return new(SessionAnnounceRequest)
	}
	return nil
}

// NewRPCResponseFor is NewRPCRequestFor for the reply body.
func NewRPCResponseFor(subject string) any {
	switch subject {
	case SubjectRoutingResolveRPC:
		return new(RoutingResolveResponse)
	case SubjectAuthzCheckRPC:
		return new(AuthzCheckResponse)
	case SubjectVoicemailListRPC:
		return new(VoicemailListResponse)
	case SubjectAuthorizeOutboundRPC:
		return new(AuthorizeOutboundResponse)
	case SubjectExtensionFeatureRPC:
		return new(ExtensionFeatureResponse)
	case SubjectToggleFeatureRPC:
		return new(ToggleFeatureResponse)
	case SubjectHotDeskRPC:
		return new(HotDeskResponse)
	case SubjectLastCallerRPC:
		return new(LastCallerResponse)
	case SubjectFileGreetingRPC:
		return new(FileGreetingResponse)
	case SubjectQueueDispositionRPC:
		return new(QueueDispositionResponse)
	case SubjectQueueSurveyRPC:
		return new(QueueSurveyResponse)
	case SubjectSipCredentialRPC:
		return new(SipCredentialResponse)
	case SubjectSipTrunkCredentialRPC:
		return new(SipTrunkCredentialResponse)
	case SubjectSipTransferRPC:
		return new(SipTransferResponse)
	case SubjectSipInviteRPC:
		return new(SipInviteResponse)
	case SubjectSipRingRPC:
		return new(SipRingResponse)
	case SubjectSipAnswerRPC:
		return new(SipAnswerResponse)
	case SubjectSipHangupRPC:
		return new(SipHangupResponse)
	case SubjectSipReinviteRPC:
		return new(SipReinviteResponse)
	case SubjectSipOriginateRPC:
		return new(SipOriginateResponse)
	case SubjectSipResolveTargetRPC:
		return new(SipResolveTargetResponse)
	case SubjectEngineRenegotiateRPC:
		return new(EngineRenegotiateResponse)
	case SubjectMediaAllocateSessionRPC:
		return new(MediaAllocateSessionResponse)
	case SubjectMediaCreateOfferRPC:
		return new(MediaCreateOfferResponse)
	case SubjectMediaAcceptAnswerRPC:
		return new(MediaAcceptAnswerResponse)
	case SubjectMediaBridgeSessionsRPC:
		return new(MediaBridgeSessionsResponse)
	case SubjectMediaUnbridgeSessionsRPC:
		return new(MediaUnbridgeSessionsResponse)
	case SubjectMediaReleaseSessionRPC:
		return new(MediaReleaseSessionResponse)
	case SubjectMediaStartPlaybackRPC:
		return new(MediaStartPlaybackResponse)
	case SubjectMediaStopPlaybackRPC:
		return new(MediaStopPlaybackResponse)
	case SubjectMediaSendDtmfRPC:
		return new(MediaSendDtmfResponse)
	case SubjectMediaStartRecordingRPC:
		return new(MediaStartRecordingResponse)
	case SubjectMediaStopRecordingRPC:
		return new(MediaStopRecordingResponse)
	case SubjectMediaPauseRecordingRPC:
		return new(MediaPauseRecordingResponse)
	case SubjectMediaTapSessionRPC:
		return new(MediaTapSessionResponse)
	case SubjectMediaUntapSessionRPC:
		return new(MediaUntapSessionResponse)
	case SubjectMediaMuteSessionRPC:
		return new(MediaMuteSessionResponse)
	case SubjectMediaHoldSessionRPC:
		return new(MediaHoldSessionResponse)
	case SubjectOriginateRPC:
		return new(OriginateResponse)
	case SubjectQueueCallbackRPC:
		return new(QueueCallbackResponse)
	case SubjectParkHandoffRPC:
		return new(ParkHandoffResponse)
	case SubjectSessionVerbRPC:
		return new(SessionVerbResponse)
	case SubjectConferenceControlRPC:
		return new(ConferenceControlResponse)
	case SubjectCallControlRPC:
		return new(CallControlResponse)
	case SubjectSessionAnnounceRPC:
		return new(SessionAnnounceResponse)
	}
	return nil
}
