// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// The contract's event-type registry: everything a generic consumer needs to route a message.

package events

// EventTypeInfo describes one event type in the contract.
type EventTypeInfo struct {
	// Family is the subject family the type belongs to.
	Family EventFamily
	// Type is the envelope's `type` discriminator.
	Type string
	// SubjectTemplate documents the subject shape, with <> placeholders.
	SubjectTemplate string
}

// EventTypes lists every event type in the contract, in declaration order.
var EventTypes = []EventTypeInfo{
	{Family: FamilyCall, Type: EventTypeChannelCreated, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.created"},
	{Family: FamilyCall, Type: EventTypeChannelRinging, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.ringing"},
	{Family: FamilyCall, Type: EventTypeChannelEarlyMedia, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.early-media"},
	{Family: FamilyCall, Type: EventTypeChannelAnswered, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.answered"},
	{Family: FamilyCall, Type: EventTypeChannelBridged, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.bridged"},
	{Family: FamilyCall, Type: EventTypeChannelUnbridged, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.unbridged"},
	{Family: FamilyCall, Type: EventTypeChannelHeld, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.held"},
	{Family: FamilyCall, Type: EventTypeChannelUnheld, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.unheld"},
	{Family: FamilyCall, Type: EventTypeChannelDTMF, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.dtmf"},
	{Family: FamilyCall, Type: EventTypeChannelRecordStarted, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.record.started"},
	{Family: FamilyCall, Type: EventTypeChannelRecordStopped, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.record.stopped"},
	{Family: FamilyCall, Type: EventTypeChannelHangup, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.hangup"},
	{Family: FamilyCall, Type: EventTypeChannelDestroyed, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.channel.destroyed"},
	{Family: FamilyCall, Type: EventTypeConferenceJoined, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.conference.joined"},
	{Family: FamilyCall, Type: EventTypeConferenceLeft, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.conference.left"},
	{Family: FamilyCall, Type: EventTypeConferenceParticipantUpdated, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.conference.participant.updated"},
	{Family: FamilyCall, Type: EventTypeConferenceLocked, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.conference.locked"},
	{Family: FamilyCall, Type: EventTypeConferenceUnlocked, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.conference.unlocked"},
	{Family: FamilyCall, Type: EventTypeCallParked, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.parked"},
	{Family: FamilyCall, Type: EventTypeCallUnparked, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.unparked"},
	{Family: FamilyCall, Type: EventTypeCallTransferred, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.transferred"},
	{Family: FamilyCall, Type: EventTypeCallPickedUp, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.picked-up"},
	{Family: FamilyCall, Type: EventTypeCallEmergencyDialed, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.emergency.dialed"},
	{Family: FamilyCall, Type: EventTypeCallTapStarted, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.tap.started"},
	{Family: FamilyCall, Type: EventTypeCallTapEnded, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.tap.ended"},
	{Family: FamilyCall, Type: EventTypeCallPagingStarted, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.paging.started"},
	{Family: FamilyCall, Type: EventTypeCallPagingEnded, SubjectTemplate: "calls.evt.v1.<orgId>.<callId>.call.paging.ended"},
	{Family: FamilyRegistration, Type: EventTypeRegistrationRegistered, SubjectTemplate: "sip.reg.v1.<orgId>.<aorHash>.registered"},
	{Family: FamilyRegistration, Type: EventTypeRegistrationUnregistered, SubjectTemplate: "sip.reg.v1.<orgId>.<aorHash>.unregistered"},
	{Family: FamilyRegistration, Type: EventTypeRegistrationExpired, SubjectTemplate: "sip.reg.v1.<orgId>.<aorHash>.expired"},
	{Family: FamilySIPDialog, Type: EventTypeSIPDialogProgressed, SubjectTemplate: "sip.evt.v1.<orgId>.<legId>.dialog.progressed"},
	{Family: FamilySIPDialog, Type: EventTypeSIPDialogAnswered, SubjectTemplate: "sip.evt.v1.<orgId>.<legId>.dialog.answered"},
	{Family: FamilySIPDialog, Type: EventTypeSIPDialogHeld, SubjectTemplate: "sip.evt.v1.<orgId>.<legId>.dialog.held"},
	{Family: FamilySIPDialog, Type: EventTypeSIPDialogResumed, SubjectTemplate: "sip.evt.v1.<orgId>.<legId>.dialog.resumed"},
	{Family: FamilySIPDialog, Type: EventTypeSIPDialogTerminated, SubjectTemplate: "sip.evt.v1.<orgId>.<legId>.dialog.terminated"},
	{Family: FamilySIPDialog, Type: EventTypeSIPDialogDTMF, SubjectTemplate: "sip.evt.v1.<orgId>.<legId>.dialog.dtmf"},
	{Family: FamilyQueue, Type: EventTypeQueueCallerJoined, SubjectTemplate: "queue.evt.v1.<orgId>.<queueId>.caller.joined"},
	{Family: FamilyQueue, Type: EventTypeQueueCallerAnswered, SubjectTemplate: "queue.evt.v1.<orgId>.<queueId>.caller.answered"},
	{Family: FamilyQueue, Type: EventTypeQueueCallerAbandoned, SubjectTemplate: "queue.evt.v1.<orgId>.<queueId>.caller.abandoned"},
	{Family: FamilyQueue, Type: EventTypeQueueAgentState, SubjectTemplate: "queue.evt.v1.<orgId>.<queueId>.agent.state"},
	{Family: FamilyVoicemail, Type: EventTypeVoicemailMessageLeft, SubjectTemplate: "voicemail.evt.v1.<orgId>.<mailboxId>.message.left"},
	{Family: FamilyVoicemail, Type: EventTypeVoicemailMWIUpdated, SubjectTemplate: "voicemail.evt.v1.<orgId>.<mailboxId>.mwi.updated"},
	{Family: FamilyMedia, Type: EventTypeMediaSessionEnded, SubjectTemplate: "media.evt.v1.<orgId>.<sessionId>.session.ended"},
	{Family: FamilyMedia, Type: EventTypeMediaSessionRTPTimeout, SubjectTemplate: "media.evt.v1.<orgId>.<sessionId>.session.rtp-timeout"},
	{Family: FamilyMedia, Type: EventTypeMediaPlaybackFinished, SubjectTemplate: "media.evt.v1.<orgId>.<sessionId>.playback.finished"},
	{Family: FamilyMedia, Type: EventTypeMediaRecordingFinished, SubjectTemplate: "media.evt.v1.<orgId>.<sessionId>.recording.finished"},
	{Family: FamilyMedia, Type: EventTypeMediaDtmfReceived, SubjectTemplate: "media.evt.v1.<orgId>.<sessionId>.dtmf.received"},
	{Family: FamilyTrunk, Type: EventTypeTrunkStatusChanged, SubjectTemplate: "trunk.evt.v1.<orgId>.<trunkId>.status.changed"},
	{Family: FamilyCDR, Type: EventTypeCDRLegWrite, SubjectTemplate: "cdr.leg.v1.<orgId>"},
	{Family: FamilyAudit, Type: EventTypeAuditRecorded, SubjectTemplate: "audit.evt.v1.<orgId>"},
	{Family: FamilyProvision, Type: EventTypeProvisionDeviceRequested, SubjectTemplate: "provision.evt.v1.<orgId>"},
	{Family: FamilyProvision, Type: EventTypeProvisionDeviceRendered, SubjectTemplate: "provision.evt.v1.<orgId>"},
	{Family: FamilyProvision, Type: EventTypeProvisionDeviceRejected, SubjectTemplate: "provision.evt.v1.<orgId>"},
}

// NewDataFor returns a pointer to a zero payload struct for eventType, or nil when the
// type is not part of this contract version.
//
// A v1.n producer may emit a type a v1.0 consumer has never heard of (envelope.ts:
// additive-only evolution), so a nil result is a normal outcome, not an error.
func NewDataFor(eventType string) any {
	switch eventType {
	case EventTypeChannelCreated:
		return new(ChannelCreatedData)
	case EventTypeChannelRinging:
		return new(ChannelRingingData)
	case EventTypeChannelEarlyMedia:
		return new(ChannelEarlyMediaData)
	case EventTypeChannelAnswered:
		return new(ChannelAnsweredData)
	case EventTypeChannelBridged:
		return new(ChannelBridgedData)
	case EventTypeChannelUnbridged:
		return new(ChannelUnbridgedData)
	case EventTypeChannelHeld:
		return new(ChannelHeldData)
	case EventTypeChannelUnheld:
		return new(ChannelUnheldData)
	case EventTypeChannelDTMF:
		return new(ChannelDTMFData)
	case EventTypeChannelRecordStarted:
		return new(ChannelRecordStartedData)
	case EventTypeChannelRecordStopped:
		return new(ChannelRecordStoppedData)
	case EventTypeChannelHangup:
		return new(ChannelHangupData)
	case EventTypeChannelDestroyed:
		return new(ChannelDestroyedData)
	case EventTypeConferenceJoined:
		return new(ConferenceJoinedData)
	case EventTypeConferenceLeft:
		return new(ConferenceLeftData)
	case EventTypeConferenceParticipantUpdated:
		return new(ConferenceParticipantUpdatedData)
	case EventTypeConferenceLocked:
		return new(ConferenceLockedData)
	case EventTypeConferenceUnlocked:
		return new(ConferenceUnlockedData)
	case EventTypeCallParked:
		return new(CallParkedData)
	case EventTypeCallUnparked:
		return new(CallUnparkedData)
	case EventTypeCallTransferred:
		return new(CallTransferredData)
	case EventTypeCallPickedUp:
		return new(CallPickedUpData)
	case EventTypeCallEmergencyDialed:
		return new(CallEmergencyDialedData)
	case EventTypeCallTapStarted:
		return new(CallTapStartedData)
	case EventTypeCallTapEnded:
		return new(CallTapEndedData)
	case EventTypeCallPagingStarted:
		return new(CallPagingStartedData)
	case EventTypeCallPagingEnded:
		return new(CallPagingEndedData)
	case EventTypeRegistrationRegistered:
		return new(RegistrationRegisteredData)
	case EventTypeRegistrationUnregistered:
		return new(RegistrationUnregisteredData)
	case EventTypeRegistrationExpired:
		return new(RegistrationExpiredData)
	case EventTypeSIPDialogProgressed:
		return new(SIPDialogProgressedData)
	case EventTypeSIPDialogAnswered:
		return new(SIPDialogAnsweredData)
	case EventTypeSIPDialogHeld:
		return new(SIPDialogHeldData)
	case EventTypeSIPDialogResumed:
		return new(SIPDialogResumedData)
	case EventTypeSIPDialogTerminated:
		return new(SIPDialogTerminatedData)
	case EventTypeSIPDialogDTMF:
		return new(SIPDialogDTMFData)
	case EventTypeQueueCallerJoined:
		return new(QueueCallerJoinedData)
	case EventTypeQueueCallerAnswered:
		return new(QueueCallerAnsweredData)
	case EventTypeQueueCallerAbandoned:
		return new(QueueCallerAbandonedData)
	case EventTypeQueueAgentState:
		return new(QueueAgentStateData)
	case EventTypeVoicemailMessageLeft:
		return new(VoicemailMessageLeftData)
	case EventTypeVoicemailMWIUpdated:
		return new(VoicemailMWIUpdatedData)
	case EventTypeMediaSessionEnded:
		return new(MediaSessionEndedData)
	case EventTypeMediaSessionRTPTimeout:
		return new(MediaSessionRTPTimeoutData)
	case EventTypeMediaPlaybackFinished:
		return new(MediaPlaybackFinishedData)
	case EventTypeMediaRecordingFinished:
		return new(MediaRecordingFinishedData)
	case EventTypeMediaDtmfReceived:
		return new(MediaDtmfReceivedData)
	case EventTypeTrunkStatusChanged:
		return new(TrunkStatusChangedData)
	case EventTypeCDRLegWrite:
		return new(CDRLegWriteData)
	case EventTypeAuditRecorded:
		return new(AuditRecordedData)
	case EventTypeProvisionDeviceRequested:
		return new(ProvisionDeviceRequestedData)
	case EventTypeProvisionDeviceRendered:
		return new(ProvisionDeviceRenderedData)
	case EventTypeProvisionDeviceRejected:
		return new(ProvisionDeviceRejectedData)
	}
	return nil
}
