// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Payloads for the registration event family.

package events

// Event types carried on the registration family's subjects. The value is the envelope's
// `type` discriminator, which is unique WITHIN the family only.
const (
	EventTypeRegistrationRegistered   = "registered"
	EventTypeRegistrationUnregistered = "unregistered"
	EventTypeRegistrationExpired      = "expired"
)

// RegistrationRegisteredData is the payload of the "registered" event.
//
// Subject: sip.reg.v1.<orgId>.<aorHash>.registered
// Envelope: Envelope[RegistrationRegisteredData]
type RegistrationRegisteredData struct {
	AOR              string       `json:"aor"`
	AORHash          string       `json:"aorHash"`
	Contact          string       `json:"contact"`
	Transport        SIPTransport `json:"transport"`
	UserAgent        *string      `json:"userAgent,omitempty"`
	SourceAddress    *string      `json:"sourceAddress,omitempty"`
	DeviceID         *string      `json:"deviceId,omitempty"`
	ExtensionID      *string      `json:"extensionId,omitempty"`
	ExpiresInSeconds int          `json:"expiresInSeconds"`
	Refreshed        *bool        `json:"refreshed,omitempty"`
}

// RegistrationUnregisteredData is the payload of the "unregistered" event.
//
// Subject: sip.reg.v1.<orgId>.<aorHash>.unregistered
// Envelope: Envelope[RegistrationUnregisteredData]
type RegistrationUnregisteredData struct {
	AOR           string                          `json:"aor"`
	AORHash       string                          `json:"aorHash"`
	Contact       string                          `json:"contact"`
	Transport     SIPTransport                    `json:"transport"`
	UserAgent     *string                         `json:"userAgent,omitempty"`
	SourceAddress *string                         `json:"sourceAddress,omitempty"`
	DeviceID      *string                         `json:"deviceId,omitempty"`
	ExtensionID   *string                         `json:"extensionId,omitempty"`
	Reason        *RegistrationUnregisteredReason `json:"reason,omitempty"`
}

// RegistrationUnregisteredReason is the closed vocabulary of RegistrationUnregisteredData.reason.
type RegistrationUnregisteredReason string

const (
	RegistrationUnregisteredReasonClient      RegistrationUnregisteredReason = "client"
	RegistrationUnregisteredReasonAdmin       RegistrationUnregisteredReason = "admin"
	RegistrationUnregisteredReasonReplaced    RegistrationUnregisteredReason = "replaced"
	RegistrationUnregisteredReasonGatewayDown RegistrationUnregisteredReason = "gateway-down"
)

// RegistrationUnregisteredReasonValues lists every member of the vocabulary, in contract order.
var RegistrationUnregisteredReasonValues = []RegistrationUnregisteredReason{
	RegistrationUnregisteredReasonClient,
	RegistrationUnregisteredReasonAdmin,
	RegistrationUnregisteredReasonReplaced,
	RegistrationUnregisteredReasonGatewayDown,
}

// Valid reports whether v is a member of the RegistrationUnregisteredReason vocabulary.
func (v RegistrationUnregisteredReason) Valid() bool {
	for _, candidate := range RegistrationUnregisteredReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v RegistrationUnregisteredReason) String() string { return string(v) }

// RegistrationExpiredData is the payload of the "expired" event.
//
// Subject: sip.reg.v1.<orgId>.<aorHash>.expired
// Envelope: Envelope[RegistrationExpiredData]
type RegistrationExpiredData struct {
	AOR                  string       `json:"aor"`
	AORHash              string       `json:"aorHash"`
	Contact              string       `json:"contact"`
	Transport            SIPTransport `json:"transport"`
	UserAgent            *string      `json:"userAgent,omitempty"`
	SourceAddress        *string      `json:"sourceAddress,omitempty"`
	DeviceID             *string      `json:"deviceId,omitempty"`
	ExtensionID          *string      `json:"extensionId,omitempty"`
	RegisteredForSeconds *int         `json:"registeredForSeconds,omitempty"`
}
