// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Request-reply contracts for the rpc.* subjects (plan §3.5).
//
// Contracts only: transport is the application's business. rpc.media.* arrives with
// apps/mediad and is deliberately absent until that service exists.

package events

import (
	"encoding/json"
	"time"
)

// Request-reply subjects and their suggested client deadlines. These are on the call path,
// so a slow reply is the same as a broken one.
const (
	SubjectRoutingResolveRPC = "rpc.routing.v1.resolve"
	SubjectAuthzCheckRPC     = "rpc.authz.v1.check"
)

const (
	TimeoutRoutingResolveRPC = 2000 * time.Millisecond
	TimeoutAuthzCheckRPC     = 1000 * time.Millisecond
)

// RoutingResolveRequest is the request body of rpc.routing.v1.resolve.
type RoutingResolveRequest struct {
	OrgID             string        `json:"orgId"`
	Direction         CallDirection `json:"direction"`
	DestinationNumber string        `json:"destinationNumber"`
	CallerNumber      *string       `json:"callerNumber,omitempty"`
	CallerName        *string       `json:"callerName,omitempty"`
	RoutingContext    string        `json:"routingContext"`
	CallID            *string       `json:"callId,omitempty"`
	At                *EventTime    `json:"at,omitempty"`
}

// RoutingResolveResponse is the reply body of rpc.routing.v1.resolve.
type RoutingResolveResponse struct {
	Matched         bool            `json:"matched"`
	DestinationType *string         `json:"destinationType,omitempty"`
	DestinationRef  *string         `json:"destinationRef,omitempty"`
	RoutingContext  *string         `json:"routingContext,omitempty"`
	Artifact        json.RawMessage `json:"artifact,omitempty"`
	CacheKey        *string         `json:"cacheKey,omitempty"`
	TTLMs           *int            `json:"ttlMs,omitempty"`
	Reason          *string         `json:"reason,omitempty"`
}

// AuthzCheckRequest is the request body of rpc.authz.v1.check.
type AuthzCheckRequest struct {
	OrgID       string                     `json:"orgId"`
	Subject     AuthzCheckRequestSubject   `json:"subject"`
	Permissions []string                   `json:"permissions"`
	Resource    *AuthzCheckRequestResource `json:"resource,omitempty"`
}

// AuthzCheckRequestSubject is a payload fragment of the contract.
type AuthzCheckRequestSubject struct {
	Type AuthzCheckRequestSubjectType `json:"type"`
	ID   string                       `json:"id"`
}

// AuthzCheckRequestSubjectType is the closed vocabulary of AuthzCheckRequestSubject.type.
type AuthzCheckRequestSubjectType string

const (
	AuthzCheckRequestSubjectTypeUser    AuthzCheckRequestSubjectType = "user"
	AuthzCheckRequestSubjectTypeAPIKey  AuthzCheckRequestSubjectType = "api-key"
	AuthzCheckRequestSubjectTypeService AuthzCheckRequestSubjectType = "service"
)

// AuthzCheckRequestSubjectTypeValues lists every member of the vocabulary, in contract order.
var AuthzCheckRequestSubjectTypeValues = []AuthzCheckRequestSubjectType{
	AuthzCheckRequestSubjectTypeUser,
	AuthzCheckRequestSubjectTypeAPIKey,
	AuthzCheckRequestSubjectTypeService,
}

// Valid reports whether v is a member of the AuthzCheckRequestSubjectType vocabulary.
func (v AuthzCheckRequestSubjectType) Valid() bool {
	for _, candidate := range AuthzCheckRequestSubjectTypeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v AuthzCheckRequestSubjectType) String() string { return string(v) }

// AuthzCheckRequestResource is a payload fragment of the contract.
type AuthzCheckRequestResource struct {
	Type string  `json:"type"`
	ID   *string `json:"id,omitempty"`
}

// AuthzCheckResponse is the reply body of rpc.authz.v1.check.
type AuthzCheckResponse struct {
	Allowed bool     `json:"allowed"`
	Granted []string `json:"granted"`
	Missing []string `json:"missing"`
	Reason  *string  `json:"reason,omitempty"`
}
