// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Request-reply contracts for the rpc.* subjects (plan §3.5).
//
// Contracts only: transport is the application's business.
//
// rpc.media.v1.* is the exception that proves the rule: apps/mediad is the RESPONDER for
// those four, so the request/response structs below are the wire, not documentation. Both
// ends must be raw NATS — a NestJS ClientProxy would wrap the payload in its own framing
// and mediad would reject it. See packages/events/src/schemas/rpc.ts.

package events

import (
	"encoding/json"
	"time"
)

// Request-reply subjects and their suggested client deadlines. These are on the call path,
// so a slow reply is the same as a broken one.
const (
	SubjectRoutingResolveRPC        = "rpc.routing.v1.resolve"
	SubjectAuthzCheckRPC            = "rpc.authz.v1.check"
	SubjectVoicemailListRPC         = "rpc.voicemail.v1.list"
	SubjectExtensionFeatureRPC      = "rpc.pbx.v1.extension-feature"
	SubjectLastCallerRPC            = "rpc.pbx.v1.last-caller"
	SubjectFileGreetingRPC          = "rpc.pbx.v1.file-greeting"
	SubjectSipCredentialRPC         = "rpc.sip.v1.credential"
	SubjectSipTransferRPC           = "rpc.sip.v1.transfer"
	SubjectMediaAllocateSessionRPC  = "rpc.media.v1.allocate-session"
	SubjectMediaBridgeSessionsRPC   = "rpc.media.v1.bridge-sessions"
	SubjectMediaUnbridgeSessionsRPC = "rpc.media.v1.unbridge-sessions"
	SubjectMediaReleaseSessionRPC   = "rpc.media.v1.release-session"
	SubjectMediaStartPlaybackRPC    = "rpc.media.v1.start-playback"
	SubjectMediaStopPlaybackRPC     = "rpc.media.v1.stop-playback"
	SubjectMediaSendDtmfRPC         = "rpc.media.v1.send-dtmf"
	SubjectMediaStartRecordingRPC   = "rpc.media.v1.start-recording"
	SubjectMediaStopRecordingRPC    = "rpc.media.v1.stop-recording"
	SubjectOriginateRPC             = "rpc.engine.v1.originate"
	SubjectParkHandoffRPC           = "rpc.engine.v1.park-handoff"
)

const (
	TimeoutRoutingResolveRPC        = 2000 * time.Millisecond
	TimeoutAuthzCheckRPC            = 1000 * time.Millisecond
	TimeoutVoicemailListRPC         = 3000 * time.Millisecond
	TimeoutExtensionFeatureRPC      = 5000 * time.Millisecond
	TimeoutLastCallerRPC            = 3000 * time.Millisecond
	TimeoutFileGreetingRPC          = 5000 * time.Millisecond
	TimeoutSipCredentialRPC         = 500 * time.Millisecond
	TimeoutSipTransferRPC           = 2000 * time.Millisecond
	TimeoutMediaAllocateSessionRPC  = 500 * time.Millisecond
	TimeoutMediaBridgeSessionsRPC   = 500 * time.Millisecond
	TimeoutMediaUnbridgeSessionsRPC = 500 * time.Millisecond
	TimeoutMediaReleaseSessionRPC   = 500 * time.Millisecond
	TimeoutMediaStartPlaybackRPC    = 1000 * time.Millisecond
	TimeoutMediaStopPlaybackRPC     = 500 * time.Millisecond
	TimeoutMediaSendDtmfRPC         = 500 * time.Millisecond
	TimeoutMediaStartRecordingRPC   = 1000 * time.Millisecond
	TimeoutMediaStopRecordingRPC    = 500 * time.Millisecond
	TimeoutOriginateRPC             = 5000 * time.Millisecond
	TimeoutParkHandoffRPC           = 3000 * time.Millisecond
)

// RoutingResolveRequest is the request body of rpc.routing.v1.resolve.
type RoutingResolveRequest struct {
	OrgID             string        `json:"orgId"`
	Direction         CallDirection `json:"direction"`
	DestinationNumber string        `json:"destinationNumber"`
	CallerNumber      *string       `json:"callerNumber,omitempty"`
	CallerName        *string       `json:"callerName,omitempty"`
	RoutingContext    string        `json:"routingContext"`
	CallID            *string       `json:"callId,omitempty"`
	At                *EventTime    `json:"at,omitempty"`
}

// RoutingResolveResponse is the reply body of rpc.routing.v1.resolve.
type RoutingResolveResponse struct {
	Matched         bool            `json:"matched"`
	DestinationType *string         `json:"destinationType,omitempty"`
	DestinationRef  *string         `json:"destinationRef,omitempty"`
	RoutingContext  *string         `json:"routingContext,omitempty"`
	Artifact        json.RawMessage `json:"artifact,omitempty"`
	CacheKey        *string         `json:"cacheKey,omitempty"`
	TTLMs           *int            `json:"ttlMs,omitempty"`
	Reason          *string         `json:"reason,omitempty"`
}

// AuthzCheckRequest is the request body of rpc.authz.v1.check.
type AuthzCheckRequest struct {
	OrgID       string                     `json:"orgId"`
	Subject     AuthzCheckRequestSubject   `json:"subject"`
	Permissions []string                   `json:"permissions"`
	Resource    *AuthzCheckRequestResource `json:"resource,omitempty"`
}

// AuthzCheckRequestSubject is a payload fragment of the contract.
type AuthzCheckRequestSubject struct {
	Type AuthzCheckRequestSubjectType `json:"type"`
	ID   string                       `json:"id"`
}

// AuthzCheckRequestSubjectType is the closed vocabulary of AuthzCheckRequestSubject.type.
type AuthzCheckRequestSubjectType string

const (
	AuthzCheckRequestSubjectTypeUser    AuthzCheckRequestSubjectType = "user"
	AuthzCheckRequestSubjectTypeAPIKey  AuthzCheckRequestSubjectType = "api-key"
	AuthzCheckRequestSubjectTypeService AuthzCheckRequestSubjectType = "service"
)

// AuthzCheckRequestSubjectTypeValues lists every member of the vocabulary, in contract order.
var AuthzCheckRequestSubjectTypeValues = []AuthzCheckRequestSubjectType{
	AuthzCheckRequestSubjectTypeUser,
	AuthzCheckRequestSubjectTypeAPIKey,
	AuthzCheckRequestSubjectTypeService,
}

// Valid reports whether v is a member of the AuthzCheckRequestSubjectType vocabulary.
func (v AuthzCheckRequestSubjectType) Valid() bool {
	for _, candidate := range AuthzCheckRequestSubjectTypeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v AuthzCheckRequestSubjectType) String() string { return string(v) }

// AuthzCheckRequestResource is a payload fragment of the contract.
type AuthzCheckRequestResource struct {
	Type string  `json:"type"`
	ID   *string `json:"id,omitempty"`
}

// AuthzCheckResponse is the reply body of rpc.authz.v1.check.
type AuthzCheckResponse struct {
	Allowed bool     `json:"allowed"`
	Granted []string `json:"granted"`
	Missing []string `json:"missing"`
	Reason  *string  `json:"reason,omitempty"`
}

// VoicemailListRequest is the request body of rpc.voicemail.v1.list.
type VoicemailListRequest struct {
	OrgID          string                     `json:"orgId"`
	VoicemailBoxID string                     `json:"voicemailBoxId"`
	MailboxNumber  string                     `json:"mailboxNumber"`
	Folder         VoicemailListRequestFolder `json:"folder"`
	Limit          int                        `json:"limit"`
	CallID         *string                    `json:"callId,omitempty"`
}

// VoicemailListRequestFolder is the closed vocabulary of VoicemailListRequest.folder.
type VoicemailListRequestFolder string

const (
	VoicemailListRequestFolderNew     VoicemailListRequestFolder = "new"
	VoicemailListRequestFolderSaved   VoicemailListRequestFolder = "saved"
	VoicemailListRequestFolderDeleted VoicemailListRequestFolder = "deleted"
)

// VoicemailListRequestFolderValues lists every member of the vocabulary, in contract order.
var VoicemailListRequestFolderValues = []VoicemailListRequestFolder{
	VoicemailListRequestFolderNew,
	VoicemailListRequestFolderSaved,
	VoicemailListRequestFolderDeleted,
}

// Valid reports whether v is a member of the VoicemailListRequestFolder vocabulary.
func (v VoicemailListRequestFolder) Valid() bool {
	for _, candidate := range VoicemailListRequestFolderValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v VoicemailListRequestFolder) String() string { return string(v) }

// VoicemailListResponse is the reply body of rpc.voicemail.v1.list.
type VoicemailListResponse struct {
	Found      bool                            `json:"found"`
	Messages   []VoicemailListResponseMessages `json:"messages"`
	Total      int                             `json:"total"`
	NewCount   int                             `json:"newCount"`
	SavedCount int                             `json:"savedCount"`
	Reason     *string                         `json:"reason,omitempty"`
}

// VoicemailListResponseMessages is a payload fragment of the contract.
type VoicemailListResponseMessages struct {
	MessageID      string                              `json:"messageId"`
	Folder         VoicemailListResponseMessagesFolder `json:"folder"`
	ObjectKey      string                              `json:"objectKey"`
	DurationMs     int                                 `json:"durationMs"`
	ReceivedAt     EventTime                           `json:"receivedAt"`
	CallerIDNumber *string                             `json:"callerIdNumber,omitempty"`
	CallerIDName   *string                             `json:"callerIdName,omitempty"`
}

// VoicemailListResponseMessagesFolder is the closed vocabulary of VoicemailListResponseMessages.folder.
type VoicemailListResponseMessagesFolder string

const (
	VoicemailListResponseMessagesFolderNew     VoicemailListResponseMessagesFolder = "new"
	VoicemailListResponseMessagesFolderSaved   VoicemailListResponseMessagesFolder = "saved"
	VoicemailListResponseMessagesFolderDeleted VoicemailListResponseMessagesFolder = "deleted"
)

// VoicemailListResponseMessagesFolderValues lists every member of the vocabulary, in contract order.
var VoicemailListResponseMessagesFolderValues = []VoicemailListResponseMessagesFolder{
	VoicemailListResponseMessagesFolderNew,
	VoicemailListResponseMessagesFolderSaved,
	VoicemailListResponseMessagesFolderDeleted,
}

// Valid reports whether v is a member of the VoicemailListResponseMessagesFolder vocabulary.
func (v VoicemailListResponseMessagesFolder) Valid() bool {
	for _, candidate := range VoicemailListResponseMessagesFolderValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v VoicemailListResponseMessagesFolder) String() string { return string(v) }

// ExtensionFeatureRequest is the request body of rpc.pbx.v1.extension-feature.
type ExtensionFeatureRequest struct {
	OrgID           string                         `json:"orgId"`
	ExtensionNumber string                         `json:"extensionNumber"`
	Feature         ExtensionFeatureRequestFeature `json:"feature"`
	Enabled         bool                           `json:"enabled"`
	Destination     *string                        `json:"destination,omitempty"`
	CallID          *string                        `json:"callId,omitempty"`
}

// ExtensionFeatureRequestFeature is the closed vocabulary of ExtensionFeatureRequest.feature.
type ExtensionFeatureRequestFeature string

const (
	ExtensionFeatureRequestFeatureForwardAll      ExtensionFeatureRequestFeature = "forward-all"
	ExtensionFeatureRequestFeatureForwardBusy     ExtensionFeatureRequestFeature = "forward-busy"
	ExtensionFeatureRequestFeatureForwardNoAnswer ExtensionFeatureRequestFeature = "forward-no-answer"
	ExtensionFeatureRequestFeatureDoNotDisturb    ExtensionFeatureRequestFeature = "do-not-disturb"
	ExtensionFeatureRequestFeatureFollowMe        ExtensionFeatureRequestFeature = "follow-me"
)

// ExtensionFeatureRequestFeatureValues lists every member of the vocabulary, in contract order.
var ExtensionFeatureRequestFeatureValues = []ExtensionFeatureRequestFeature{
	ExtensionFeatureRequestFeatureForwardAll,
	ExtensionFeatureRequestFeatureForwardBusy,
	ExtensionFeatureRequestFeatureForwardNoAnswer,
	ExtensionFeatureRequestFeatureDoNotDisturb,
	ExtensionFeatureRequestFeatureFollowMe,
}

// Valid reports whether v is a member of the ExtensionFeatureRequestFeature vocabulary.
func (v ExtensionFeatureRequestFeature) Valid() bool {
	for _, candidate := range ExtensionFeatureRequestFeatureValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v ExtensionFeatureRequestFeature) String() string { return string(v) }

// ExtensionFeatureResponse is the reply body of rpc.pbx.v1.extension-feature.
type ExtensionFeatureResponse struct {
	Applied     bool                            `json:"applied"`
	Feature     ExtensionFeatureResponseFeature `json:"feature"`
	Enabled     bool                            `json:"enabled"`
	Destination *string                         `json:"destination,omitempty"`
	Reason      *string                         `json:"reason,omitempty"`
}

// ExtensionFeatureResponseFeature is the closed vocabulary of ExtensionFeatureResponse.feature.
type ExtensionFeatureResponseFeature string

const (
	ExtensionFeatureResponseFeatureForwardAll      ExtensionFeatureResponseFeature = "forward-all"
	ExtensionFeatureResponseFeatureForwardBusy     ExtensionFeatureResponseFeature = "forward-busy"
	ExtensionFeatureResponseFeatureForwardNoAnswer ExtensionFeatureResponseFeature = "forward-no-answer"
	ExtensionFeatureResponseFeatureDoNotDisturb    ExtensionFeatureResponseFeature = "do-not-disturb"
	ExtensionFeatureResponseFeatureFollowMe        ExtensionFeatureResponseFeature = "follow-me"
)

// ExtensionFeatureResponseFeatureValues lists every member of the vocabulary, in contract order.
var ExtensionFeatureResponseFeatureValues = []ExtensionFeatureResponseFeature{
	ExtensionFeatureResponseFeatureForwardAll,
	ExtensionFeatureResponseFeatureForwardBusy,
	ExtensionFeatureResponseFeatureForwardNoAnswer,
	ExtensionFeatureResponseFeatureDoNotDisturb,
	ExtensionFeatureResponseFeatureFollowMe,
}

// Valid reports whether v is a member of the ExtensionFeatureResponseFeature vocabulary.
func (v ExtensionFeatureResponseFeature) Valid() bool {
	for _, candidate := range ExtensionFeatureResponseFeatureValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v ExtensionFeatureResponseFeature) String() string { return string(v) }

// LastCallerRequest is the request body of rpc.pbx.v1.last-caller.
type LastCallerRequest struct {
	OrgID           string  `json:"orgId"`
	ExtensionNumber string  `json:"extensionNumber"`
	WithinHours     int     `json:"withinHours"`
	CallID          *string `json:"callId,omitempty"`
}

// LastCallerResponse is the reply body of rpc.pbx.v1.last-caller.
type LastCallerResponse struct {
	Found        bool       `json:"found"`
	CallerNumber *string    `json:"callerNumber,omitempty"`
	CallerName   *string    `json:"callerName,omitempty"`
	At           *EventTime `json:"at,omitempty"`
	Reason       *string    `json:"reason,omitempty"`
}

// FileGreetingRequest is the request body of rpc.pbx.v1.file-greeting.
type FileGreetingRequest struct {
	OrgID          string                  `json:"orgId"`
	VoicemailBoxID string                  `json:"voicemailBoxId"`
	MailboxNumber  string                  `json:"mailboxNumber"`
	GreetingID     string                  `json:"greetingId"`
	Kind           FileGreetingRequestKind `json:"kind"`
	ObjectKey      string                  `json:"objectKey"`
	RecordingID    *string                 `json:"recordingId,omitempty"`
	DurationMs     int                     `json:"durationMs"`
	CallID         *string                 `json:"callId,omitempty"`
}

// FileGreetingRequestKind is the closed vocabulary of FileGreetingRequest.kind.
type FileGreetingRequestKind string

const (
	FileGreetingRequestKindUnavailable FileGreetingRequestKind = "unavailable"
	FileGreetingRequestKindBusy        FileGreetingRequestKind = "busy"
	FileGreetingRequestKindName        FileGreetingRequestKind = "name"
	FileGreetingRequestKindTemporary   FileGreetingRequestKind = "temporary"
)

// FileGreetingRequestKindValues lists every member of the vocabulary, in contract order.
var FileGreetingRequestKindValues = []FileGreetingRequestKind{
	FileGreetingRequestKindUnavailable,
	FileGreetingRequestKindBusy,
	FileGreetingRequestKindName,
	FileGreetingRequestKindTemporary,
}

// Valid reports whether v is a member of the FileGreetingRequestKind vocabulary.
func (v FileGreetingRequestKind) Valid() bool {
	for _, candidate := range FileGreetingRequestKindValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v FileGreetingRequestKind) String() string { return string(v) }

// FileGreetingResponse is the reply body of rpc.pbx.v1.file-greeting.
type FileGreetingResponse struct {
	Applied    bool                     `json:"applied"`
	Kind       FileGreetingResponseKind `json:"kind"`
	Active     bool                     `json:"active"`
	GreetingID *string                  `json:"greetingId,omitempty"`
	ObjectKey  *string                  `json:"objectKey,omitempty"`
	Reason     *string                  `json:"reason,omitempty"`
}

// FileGreetingResponseKind is the closed vocabulary of FileGreetingResponse.kind.
type FileGreetingResponseKind string

const (
	FileGreetingResponseKindUnavailable FileGreetingResponseKind = "unavailable"
	FileGreetingResponseKindBusy        FileGreetingResponseKind = "busy"
	FileGreetingResponseKindName        FileGreetingResponseKind = "name"
	FileGreetingResponseKindTemporary   FileGreetingResponseKind = "temporary"
)

// FileGreetingResponseKindValues lists every member of the vocabulary, in contract order.
var FileGreetingResponseKindValues = []FileGreetingResponseKind{
	FileGreetingResponseKindUnavailable,
	FileGreetingResponseKindBusy,
	FileGreetingResponseKindName,
	FileGreetingResponseKindTemporary,
}

// Valid reports whether v is a member of the FileGreetingResponseKind vocabulary.
func (v FileGreetingResponseKind) Valid() bool {
	for _, candidate := range FileGreetingResponseKindValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v FileGreetingResponseKind) String() string { return string(v) }

// SipCredentialRequest is the request body of rpc.sip.v1.credential.
type SipCredentialRequest struct {
	Realm         string        `json:"realm"`
	Username      string        `json:"username"`
	SourceAddress *string       `json:"sourceAddress,omitempty"`
	Transport     *SIPTransport `json:"transport,omitempty"`
}

// SipCredentialResponse is the reply body of rpc.sip.v1.credential.
type SipCredentialResponse struct {
	Found       bool    `json:"found"`
	Enabled     bool    `json:"enabled"`
	OrgID       *string `json:"orgId,omitempty"`
	Username    *string `json:"username,omitempty"`
	Realm       *string `json:"realm,omitempty"`
	Ha1         *string `json:"ha1,omitempty"`
	DeviceID    *string `json:"deviceId,omitempty"`
	ExtensionID *string `json:"extensionId,omitempty"`
	Reason      *string `json:"reason,omitempty"`
}

// SipTransferRequest is the request body of rpc.sip.v1.transfer.
type SipTransferRequest struct {
	OrgID         string                       `json:"orgId"`
	SIPCallID     string                       `json:"sipCallId"`
	FromTag       *string                      `json:"fromTag,omitempty"`
	ToTag         *string                      `json:"toTag,omitempty"`
	ReferredBy    SipTransferRequestReferredBy `json:"referredBy"`
	Target        SipTransferRequestTarget     `json:"target"`
	Kind          SipTransferRequestKind       `json:"kind"`
	Replaces      *SipTransferRequestReplaces  `json:"replaces,omitempty"`
	ReferCSeq     *int                         `json:"referCSeq,omitempty"`
	SourceAddress *string                      `json:"sourceAddress,omitempty"`
	Transport     *SIPTransport                `json:"transport,omitempty"`
}

// SipTransferRequestReferredBy is a payload fragment of the contract.
type SipTransferRequestReferredBy struct {
	AOR         string  `json:"aor"`
	Username    string  `json:"username"`
	ExtensionID *string `json:"extensionId,omitempty"`
	DeviceID    *string `json:"deviceId,omitempty"`
}

// SipTransferRequestTarget is a payload fragment of the contract.
type SipTransferRequestTarget struct {
	User string  `json:"user"`
	Host *string `json:"host,omitempty"`
	URI  *string `json:"uri,omitempty"`
}

// SipTransferRequestKind is the closed vocabulary of SipTransferRequest.kind.
type SipTransferRequestKind string

const (
	SipTransferRequestKindBlind    SipTransferRequestKind = "blind"
	SipTransferRequestKindAttended SipTransferRequestKind = "attended"
)

// SipTransferRequestKindValues lists every member of the vocabulary, in contract order.
var SipTransferRequestKindValues = []SipTransferRequestKind{
	SipTransferRequestKindBlind,
	SipTransferRequestKindAttended,
}

// Valid reports whether v is a member of the SipTransferRequestKind vocabulary.
func (v SipTransferRequestKind) Valid() bool {
	for _, candidate := range SipTransferRequestKindValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SipTransferRequestKind) String() string { return string(v) }

// SipTransferRequestReplaces is a payload fragment of the contract.
type SipTransferRequestReplaces struct {
	CallID    string `json:"callId"`
	ToTag     string `json:"toTag"`
	FromTag   string `json:"fromTag"`
	EarlyOnly bool   `json:"earlyOnly"`
}

// SipTransferResponse is the reply body of rpc.sip.v1.transfer.
type SipTransferResponse struct {
	Ok          bool                       `json:"ok"`
	SIPCallID   string                     `json:"sipCallId"`
	InstanceID  *string                    `json:"instanceId,omitempty"`
	LegID       *string                    `json:"legId,omitempty"`
	CallID      *string                    `json:"callId,omitempty"`
	Destination *string                    `json:"destination,omitempty"`
	Reason      *SipTransferResponseReason `json:"reason,omitempty"`
	Error       *string                    `json:"error,omitempty"`
}

// SipTransferResponseReason is the closed vocabulary of SipTransferResponse.reason.
type SipTransferResponseReason string

const (
	SipTransferResponseReasonBadRequest             SipTransferResponseReason = "bad_request"
	SipTransferResponseReasonUnknownDialog          SipTransferResponseReason = "unknown_dialog"
	SipTransferResponseReasonCorrelationUnavailable SipTransferResponseReason = "correlation_unavailable"
	SipTransferResponseReasonNotPermitted           SipTransferResponseReason = "not_permitted"
	SipTransferResponseReasonWrongInstance          SipTransferResponseReason = "wrong_instance"
	SipTransferResponseReasonUnknownTarget          SipTransferResponseReason = "unknown_target"
	SipTransferResponseReasonAttendedUnsupported    SipTransferResponseReason = "attended_unsupported"
	SipTransferResponseReasonChannelGone            SipTransferResponseReason = "channel_gone"
	SipTransferResponseReasonTransferFailed         SipTransferResponseReason = "transfer_failed"
	SipTransferResponseReasonShuttingDown           SipTransferResponseReason = "shutting_down"
	SipTransferResponseReasonInternal               SipTransferResponseReason = "internal"
)

// SipTransferResponseReasonValues lists every member of the vocabulary, in contract order.
var SipTransferResponseReasonValues = []SipTransferResponseReason{
	SipTransferResponseReasonBadRequest,
	SipTransferResponseReasonUnknownDialog,
	SipTransferResponseReasonCorrelationUnavailable,
	SipTransferResponseReasonNotPermitted,
	SipTransferResponseReasonWrongInstance,
	SipTransferResponseReasonUnknownTarget,
	SipTransferResponseReasonAttendedUnsupported,
	SipTransferResponseReasonChannelGone,
	SipTransferResponseReasonTransferFailed,
	SipTransferResponseReasonShuttingDown,
	SipTransferResponseReasonInternal,
}

// Valid reports whether v is a member of the SipTransferResponseReason vocabulary.
func (v SipTransferResponseReason) Valid() bool {
	for _, candidate := range SipTransferResponseReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SipTransferResponseReason) String() string { return string(v) }

// MediaAllocateSessionRequest is the request body of rpc.media.v1.allocate-session.
type MediaAllocateSessionRequest struct {
	SessionID string                               `json:"sessionId"`
	OrgID     string                               `json:"orgId"`
	CallID    string                               `json:"callId"`
	LegID     *string                              `json:"legId,omitempty"`
	SDPOffer  string                               `json:"sdpOffer"`
	Direction MediaAllocateSessionRequestDirection `json:"direction"`
}

// MediaAllocateSessionRequestDirection is the closed vocabulary of MediaAllocateSessionRequest.direction.
type MediaAllocateSessionRequestDirection string

const (
	MediaAllocateSessionRequestDirectionSendrecv MediaAllocateSessionRequestDirection = "sendrecv"
	MediaAllocateSessionRequestDirectionSendonly MediaAllocateSessionRequestDirection = "sendonly"
	MediaAllocateSessionRequestDirectionRecvonly MediaAllocateSessionRequestDirection = "recvonly"
	MediaAllocateSessionRequestDirectionInactive MediaAllocateSessionRequestDirection = "inactive"
)

// MediaAllocateSessionRequestDirectionValues lists every member of the vocabulary, in contract order.
var MediaAllocateSessionRequestDirectionValues = []MediaAllocateSessionRequestDirection{
	MediaAllocateSessionRequestDirectionSendrecv,
	MediaAllocateSessionRequestDirectionSendonly,
	MediaAllocateSessionRequestDirectionRecvonly,
	MediaAllocateSessionRequestDirectionInactive,
}

// Valid reports whether v is a member of the MediaAllocateSessionRequestDirection vocabulary.
func (v MediaAllocateSessionRequestDirection) Valid() bool {
	for _, candidate := range MediaAllocateSessionRequestDirectionValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaAllocateSessionRequestDirection) String() string { return string(v) }

// MediaAllocateSessionResponse is the reply body of rpc.media.v1.allocate-session.
type MediaAllocateSessionResponse struct {
	Ok                        bool                                `json:"ok"`
	SessionID                 string                              `json:"sessionId"`
	SDPAnswer                 *string                             `json:"sdpAnswer,omitempty"`
	InstanceID                *string                             `json:"instanceId,omitempty"`
	Address                   *string                             `json:"address,omitempty"`
	RtpPort                   *int                                `json:"rtpPort,omitempty"`
	RtcpPort                  *int                                `json:"rtcpPort,omitempty"`
	Ssrc                      *int                                `json:"ssrc,omitempty"`
	Codec                     *MediaAllocateSessionResponseCodec  `json:"codec,omitempty"`
	TelephoneEventPayloadType *int                                `json:"telephoneEventPayloadType,omitempty"`
	Reason                    *MediaAllocateSessionResponseReason `json:"reason,omitempty"`
	Error                     *string                             `json:"error,omitempty"`
}

// MediaAllocateSessionResponseCodec is the closed vocabulary of MediaAllocateSessionResponse.codec.
type MediaAllocateSessionResponseCodec string

const (
	MediaAllocateSessionResponseCodecPcmu MediaAllocateSessionResponseCodec = "PCMU"
	MediaAllocateSessionResponseCodecPcma MediaAllocateSessionResponseCodec = "PCMA"
)

// MediaAllocateSessionResponseCodecValues lists every member of the vocabulary, in contract order.
var MediaAllocateSessionResponseCodecValues = []MediaAllocateSessionResponseCodec{
	MediaAllocateSessionResponseCodecPcmu,
	MediaAllocateSessionResponseCodecPcma,
}

// Valid reports whether v is a member of the MediaAllocateSessionResponseCodec vocabulary.
func (v MediaAllocateSessionResponseCodec) Valid() bool {
	for _, candidate := range MediaAllocateSessionResponseCodecValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaAllocateSessionResponseCodec) String() string { return string(v) }

// MediaAllocateSessionResponseReason is the closed vocabulary of MediaAllocateSessionResponse.reason.
type MediaAllocateSessionResponseReason string

const (
	MediaAllocateSessionResponseReasonBadRequest     MediaAllocateSessionResponseReason = "bad_request"
	MediaAllocateSessionResponseReasonCapacity       MediaAllocateSessionResponseReason = "capacity"
	MediaAllocateSessionResponseReasonShuttingDown   MediaAllocateSessionResponseReason = "shutting_down"
	MediaAllocateSessionResponseReasonUnknownSession MediaAllocateSessionResponseReason = "unknown_session"
	MediaAllocateSessionResponseReasonWrongInstance  MediaAllocateSessionResponseReason = "wrong_instance"
	MediaAllocateSessionResponseReasonNotSupported   MediaAllocateSessionResponseReason = "not_supported"
	MediaAllocateSessionResponseReasonInternal       MediaAllocateSessionResponseReason = "internal"
)

// MediaAllocateSessionResponseReasonValues lists every member of the vocabulary, in contract order.
var MediaAllocateSessionResponseReasonValues = []MediaAllocateSessionResponseReason{
	MediaAllocateSessionResponseReasonBadRequest,
	MediaAllocateSessionResponseReasonCapacity,
	MediaAllocateSessionResponseReasonShuttingDown,
	MediaAllocateSessionResponseReasonUnknownSession,
	MediaAllocateSessionResponseReasonWrongInstance,
	MediaAllocateSessionResponseReasonNotSupported,
	MediaAllocateSessionResponseReasonInternal,
}

// Valid reports whether v is a member of the MediaAllocateSessionResponseReason vocabulary.
func (v MediaAllocateSessionResponseReason) Valid() bool {
	for _, candidate := range MediaAllocateSessionResponseReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaAllocateSessionResponseReason) String() string { return string(v) }

// MediaBridgeSessionsRequest is the request body of rpc.media.v1.bridge-sessions.
type MediaBridgeSessionsRequest struct {
	BridgeID   string   `json:"bridgeId"`
	SessionIDs []string `json:"sessionIds"`
}

// MediaBridgeSessionsResponse is the reply body of rpc.media.v1.bridge-sessions.
type MediaBridgeSessionsResponse struct {
	Ok         bool                               `json:"ok"`
	BridgeID   string                             `json:"bridgeId"`
	SessionIDs []string                           `json:"sessionIds"`
	InstanceID *string                            `json:"instanceId,omitempty"`
	Reason     *MediaBridgeSessionsResponseReason `json:"reason,omitempty"`
	Error      *string                            `json:"error,omitempty"`
}

// MediaBridgeSessionsResponseReason is the closed vocabulary of MediaBridgeSessionsResponse.reason.
type MediaBridgeSessionsResponseReason string

const (
	MediaBridgeSessionsResponseReasonBadRequest     MediaBridgeSessionsResponseReason = "bad_request"
	MediaBridgeSessionsResponseReasonCapacity       MediaBridgeSessionsResponseReason = "capacity"
	MediaBridgeSessionsResponseReasonShuttingDown   MediaBridgeSessionsResponseReason = "shutting_down"
	MediaBridgeSessionsResponseReasonUnknownSession MediaBridgeSessionsResponseReason = "unknown_session"
	MediaBridgeSessionsResponseReasonWrongInstance  MediaBridgeSessionsResponseReason = "wrong_instance"
	MediaBridgeSessionsResponseReasonNotSupported   MediaBridgeSessionsResponseReason = "not_supported"
	MediaBridgeSessionsResponseReasonInternal       MediaBridgeSessionsResponseReason = "internal"
)

// MediaBridgeSessionsResponseReasonValues lists every member of the vocabulary, in contract order.
var MediaBridgeSessionsResponseReasonValues = []MediaBridgeSessionsResponseReason{
	MediaBridgeSessionsResponseReasonBadRequest,
	MediaBridgeSessionsResponseReasonCapacity,
	MediaBridgeSessionsResponseReasonShuttingDown,
	MediaBridgeSessionsResponseReasonUnknownSession,
	MediaBridgeSessionsResponseReasonWrongInstance,
	MediaBridgeSessionsResponseReasonNotSupported,
	MediaBridgeSessionsResponseReasonInternal,
}

// Valid reports whether v is a member of the MediaBridgeSessionsResponseReason vocabulary.
func (v MediaBridgeSessionsResponseReason) Valid() bool {
	for _, candidate := range MediaBridgeSessionsResponseReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaBridgeSessionsResponseReason) String() string { return string(v) }

// MediaUnbridgeSessionsRequest is the request body of rpc.media.v1.unbridge-sessions.
type MediaUnbridgeSessionsRequest struct {
	BridgeID string `json:"bridgeId"`
}

// MediaUnbridgeSessionsResponse is the reply body of rpc.media.v1.unbridge-sessions.
type MediaUnbridgeSessionsResponse struct {
	Ok         bool                                 `json:"ok"`
	BridgeID   string                               `json:"bridgeId"`
	Unbridged  bool                                 `json:"unbridged"`
	SessionIDs []string                             `json:"sessionIds"`
	InstanceID *string                              `json:"instanceId,omitempty"`
	Reason     *MediaUnbridgeSessionsResponseReason `json:"reason,omitempty"`
	Error      *string                              `json:"error,omitempty"`
}

// MediaUnbridgeSessionsResponseReason is the closed vocabulary of MediaUnbridgeSessionsResponse.reason.
type MediaUnbridgeSessionsResponseReason string

const (
	MediaUnbridgeSessionsResponseReasonBadRequest     MediaUnbridgeSessionsResponseReason = "bad_request"
	MediaUnbridgeSessionsResponseReasonCapacity       MediaUnbridgeSessionsResponseReason = "capacity"
	MediaUnbridgeSessionsResponseReasonShuttingDown   MediaUnbridgeSessionsResponseReason = "shutting_down"
	MediaUnbridgeSessionsResponseReasonUnknownSession MediaUnbridgeSessionsResponseReason = "unknown_session"
	MediaUnbridgeSessionsResponseReasonWrongInstance  MediaUnbridgeSessionsResponseReason = "wrong_instance"
	MediaUnbridgeSessionsResponseReasonNotSupported   MediaUnbridgeSessionsResponseReason = "not_supported"
	MediaUnbridgeSessionsResponseReasonInternal       MediaUnbridgeSessionsResponseReason = "internal"
)

// MediaUnbridgeSessionsResponseReasonValues lists every member of the vocabulary, in contract order.
var MediaUnbridgeSessionsResponseReasonValues = []MediaUnbridgeSessionsResponseReason{
	MediaUnbridgeSessionsResponseReasonBadRequest,
	MediaUnbridgeSessionsResponseReasonCapacity,
	MediaUnbridgeSessionsResponseReasonShuttingDown,
	MediaUnbridgeSessionsResponseReasonUnknownSession,
	MediaUnbridgeSessionsResponseReasonWrongInstance,
	MediaUnbridgeSessionsResponseReasonNotSupported,
	MediaUnbridgeSessionsResponseReasonInternal,
}

// Valid reports whether v is a member of the MediaUnbridgeSessionsResponseReason vocabulary.
func (v MediaUnbridgeSessionsResponseReason) Valid() bool {
	for _, candidate := range MediaUnbridgeSessionsResponseReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaUnbridgeSessionsResponseReason) String() string { return string(v) }

// MediaReleaseSessionRequest is the request body of rpc.media.v1.release-session.
type MediaReleaseSessionRequest struct {
	SessionID string `json:"sessionId"`
}

// MediaReleaseSessionResponse is the reply body of rpc.media.v1.release-session.
type MediaReleaseSessionResponse struct {
	Ok         bool                               `json:"ok"`
	SessionID  string                             `json:"sessionId"`
	Released   bool                               `json:"released"`
	InstanceID *string                            `json:"instanceId,omitempty"`
	Reason     *MediaReleaseSessionResponseReason `json:"reason,omitempty"`
	Error      *string                            `json:"error,omitempty"`
}

// MediaReleaseSessionResponseReason is the closed vocabulary of MediaReleaseSessionResponse.reason.
type MediaReleaseSessionResponseReason string

const (
	MediaReleaseSessionResponseReasonBadRequest     MediaReleaseSessionResponseReason = "bad_request"
	MediaReleaseSessionResponseReasonCapacity       MediaReleaseSessionResponseReason = "capacity"
	MediaReleaseSessionResponseReasonShuttingDown   MediaReleaseSessionResponseReason = "shutting_down"
	MediaReleaseSessionResponseReasonUnknownSession MediaReleaseSessionResponseReason = "unknown_session"
	MediaReleaseSessionResponseReasonWrongInstance  MediaReleaseSessionResponseReason = "wrong_instance"
	MediaReleaseSessionResponseReasonNotSupported   MediaReleaseSessionResponseReason = "not_supported"
	MediaReleaseSessionResponseReasonInternal       MediaReleaseSessionResponseReason = "internal"
)

// MediaReleaseSessionResponseReasonValues lists every member of the vocabulary, in contract order.
var MediaReleaseSessionResponseReasonValues = []MediaReleaseSessionResponseReason{
	MediaReleaseSessionResponseReasonBadRequest,
	MediaReleaseSessionResponseReasonCapacity,
	MediaReleaseSessionResponseReasonShuttingDown,
	MediaReleaseSessionResponseReasonUnknownSession,
	MediaReleaseSessionResponseReasonWrongInstance,
	MediaReleaseSessionResponseReasonNotSupported,
	MediaReleaseSessionResponseReasonInternal,
}

// Valid reports whether v is a member of the MediaReleaseSessionResponseReason vocabulary.
func (v MediaReleaseSessionResponseReason) Valid() bool {
	for _, candidate := range MediaReleaseSessionResponseReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaReleaseSessionResponseReason) String() string { return string(v) }

// MediaStartPlaybackRequest is the request body of rpc.media.v1.start-playback.
type MediaStartPlaybackRequest struct {
	SessionID   string   `json:"sessionId"`
	PlaybackRef string   `json:"playbackRef"`
	Media       []string `json:"media"`
	Language    *string  `json:"language,omitempty"`
}

// MediaStartPlaybackResponse is the reply body of rpc.media.v1.start-playback.
type MediaStartPlaybackResponse struct {
	Ok          bool                              `json:"ok"`
	SessionID   string                            `json:"sessionId"`
	PlaybackRef string                            `json:"playbackRef"`
	InstanceID  *string                           `json:"instanceId,omitempty"`
	Reason      *MediaStartPlaybackResponseReason `json:"reason,omitempty"`
	Error       *string                           `json:"error,omitempty"`
}

// MediaStartPlaybackResponseReason is the closed vocabulary of MediaStartPlaybackResponse.reason.
type MediaStartPlaybackResponseReason string

const (
	MediaStartPlaybackResponseReasonBadRequest     MediaStartPlaybackResponseReason = "bad_request"
	MediaStartPlaybackResponseReasonCapacity       MediaStartPlaybackResponseReason = "capacity"
	MediaStartPlaybackResponseReasonShuttingDown   MediaStartPlaybackResponseReason = "shutting_down"
	MediaStartPlaybackResponseReasonUnknownSession MediaStartPlaybackResponseReason = "unknown_session"
	MediaStartPlaybackResponseReasonWrongInstance  MediaStartPlaybackResponseReason = "wrong_instance"
	MediaStartPlaybackResponseReasonNotSupported   MediaStartPlaybackResponseReason = "not_supported"
	MediaStartPlaybackResponseReasonInternal       MediaStartPlaybackResponseReason = "internal"
)

// MediaStartPlaybackResponseReasonValues lists every member of the vocabulary, in contract order.
var MediaStartPlaybackResponseReasonValues = []MediaStartPlaybackResponseReason{
	MediaStartPlaybackResponseReasonBadRequest,
	MediaStartPlaybackResponseReasonCapacity,
	MediaStartPlaybackResponseReasonShuttingDown,
	MediaStartPlaybackResponseReasonUnknownSession,
	MediaStartPlaybackResponseReasonWrongInstance,
	MediaStartPlaybackResponseReasonNotSupported,
	MediaStartPlaybackResponseReasonInternal,
}

// Valid reports whether v is a member of the MediaStartPlaybackResponseReason vocabulary.
func (v MediaStartPlaybackResponseReason) Valid() bool {
	for _, candidate := range MediaStartPlaybackResponseReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaStartPlaybackResponseReason) String() string { return string(v) }

// MediaStopPlaybackRequest is the request body of rpc.media.v1.stop-playback.
type MediaStopPlaybackRequest struct {
	PlaybackRef string `json:"playbackRef"`
}

// MediaStopPlaybackResponse is the reply body of rpc.media.v1.stop-playback.
type MediaStopPlaybackResponse struct {
	Ok          bool                             `json:"ok"`
	PlaybackRef string                           `json:"playbackRef"`
	Stopped     bool                             `json:"stopped"`
	SessionID   *string                          `json:"sessionId,omitempty"`
	InstanceID  *string                          `json:"instanceId,omitempty"`
	Reason      *MediaStopPlaybackResponseReason `json:"reason,omitempty"`
	Error       *string                          `json:"error,omitempty"`
}

// MediaStopPlaybackResponseReason is the closed vocabulary of MediaStopPlaybackResponse.reason.
type MediaStopPlaybackResponseReason string

const (
	MediaStopPlaybackResponseReasonBadRequest     MediaStopPlaybackResponseReason = "bad_request"
	MediaStopPlaybackResponseReasonCapacity       MediaStopPlaybackResponseReason = "capacity"
	MediaStopPlaybackResponseReasonShuttingDown   MediaStopPlaybackResponseReason = "shutting_down"
	MediaStopPlaybackResponseReasonUnknownSession MediaStopPlaybackResponseReason = "unknown_session"
	MediaStopPlaybackResponseReasonWrongInstance  MediaStopPlaybackResponseReason = "wrong_instance"
	MediaStopPlaybackResponseReasonNotSupported   MediaStopPlaybackResponseReason = "not_supported"
	MediaStopPlaybackResponseReasonInternal       MediaStopPlaybackResponseReason = "internal"
)

// MediaStopPlaybackResponseReasonValues lists every member of the vocabulary, in contract order.
var MediaStopPlaybackResponseReasonValues = []MediaStopPlaybackResponseReason{
	MediaStopPlaybackResponseReasonBadRequest,
	MediaStopPlaybackResponseReasonCapacity,
	MediaStopPlaybackResponseReasonShuttingDown,
	MediaStopPlaybackResponseReasonUnknownSession,
	MediaStopPlaybackResponseReasonWrongInstance,
	MediaStopPlaybackResponseReasonNotSupported,
	MediaStopPlaybackResponseReasonInternal,
}

// Valid reports whether v is a member of the MediaStopPlaybackResponseReason vocabulary.
func (v MediaStopPlaybackResponseReason) Valid() bool {
	for _, candidate := range MediaStopPlaybackResponseReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaStopPlaybackResponseReason) String() string { return string(v) }

// MediaSendDtmfRequest is the request body of rpc.media.v1.send-dtmf.
type MediaSendDtmfRequest struct {
	SessionID      string `json:"sessionId"`
	Digits         string `json:"digits"`
	ToneDurationMs *int   `json:"toneDurationMs,omitempty"`
	GapMs          *int   `json:"gapMs,omitempty"`
}

// MediaSendDtmfResponse is the reply body of rpc.media.v1.send-dtmf.
type MediaSendDtmfResponse struct {
	Ok                        bool                         `json:"ok"`
	SessionID                 string                       `json:"sessionId"`
	Digits                    string                       `json:"digits"`
	QueuedMs                  *int                         `json:"queuedMs,omitempty"`
	TelephoneEventPayloadType *int                         `json:"telephoneEventPayloadType,omitempty"`
	InstanceID                *string                      `json:"instanceId,omitempty"`
	Reason                    *MediaSendDtmfResponseReason `json:"reason,omitempty"`
	Error                     *string                      `json:"error,omitempty"`
}

// MediaSendDtmfResponseReason is the closed vocabulary of MediaSendDtmfResponse.reason.
type MediaSendDtmfResponseReason string

const (
	MediaSendDtmfResponseReasonBadRequest     MediaSendDtmfResponseReason = "bad_request"
	MediaSendDtmfResponseReasonCapacity       MediaSendDtmfResponseReason = "capacity"
	MediaSendDtmfResponseReasonShuttingDown   MediaSendDtmfResponseReason = "shutting_down"
	MediaSendDtmfResponseReasonUnknownSession MediaSendDtmfResponseReason = "unknown_session"
	MediaSendDtmfResponseReasonWrongInstance  MediaSendDtmfResponseReason = "wrong_instance"
	MediaSendDtmfResponseReasonNotSupported   MediaSendDtmfResponseReason = "not_supported"
	MediaSendDtmfResponseReasonInternal       MediaSendDtmfResponseReason = "internal"
)

// MediaSendDtmfResponseReasonValues lists every member of the vocabulary, in contract order.
var MediaSendDtmfResponseReasonValues = []MediaSendDtmfResponseReason{
	MediaSendDtmfResponseReasonBadRequest,
	MediaSendDtmfResponseReasonCapacity,
	MediaSendDtmfResponseReasonShuttingDown,
	MediaSendDtmfResponseReasonUnknownSession,
	MediaSendDtmfResponseReasonWrongInstance,
	MediaSendDtmfResponseReasonNotSupported,
	MediaSendDtmfResponseReasonInternal,
}

// Valid reports whether v is a member of the MediaSendDtmfResponseReason vocabulary.
func (v MediaSendDtmfResponseReason) Valid() bool {
	for _, candidate := range MediaSendDtmfResponseReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaSendDtmfResponseReason) String() string { return string(v) }

// MediaStartRecordingRequest is the request body of rpc.media.v1.start-recording.
type MediaStartRecordingRequest struct {
	SessionID     string                              `json:"sessionId"`
	RecordingRef  string                              `json:"recordingRef"`
	Direction     MediaStartRecordingRequestDirection `json:"direction"`
	Format        MediaStartRecordingRequestFormat    `json:"format"`
	MaxDurationMs *int                                `json:"maxDurationMs,omitempty"`
	MaxSilenceMs  *int                                `json:"maxSilenceMs,omitempty"`
	Beep          *bool                               `json:"beep,omitempty"`
	TerminateOn   *string                             `json:"terminateOn,omitempty"`
}

// MediaStartRecordingRequestDirection is the closed vocabulary of MediaStartRecordingRequest.direction.
type MediaStartRecordingRequestDirection string

const (
	MediaStartRecordingRequestDirectionReceive MediaStartRecordingRequestDirection = "receive"
	MediaStartRecordingRequestDirectionBoth    MediaStartRecordingRequestDirection = "both"
)

// MediaStartRecordingRequestDirectionValues lists every member of the vocabulary, in contract order.
var MediaStartRecordingRequestDirectionValues = []MediaStartRecordingRequestDirection{
	MediaStartRecordingRequestDirectionReceive,
	MediaStartRecordingRequestDirectionBoth,
}

// Valid reports whether v is a member of the MediaStartRecordingRequestDirection vocabulary.
func (v MediaStartRecordingRequestDirection) Valid() bool {
	for _, candidate := range MediaStartRecordingRequestDirectionValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaStartRecordingRequestDirection) String() string { return string(v) }

// MediaStartRecordingRequestFormat is the closed vocabulary of MediaStartRecordingRequest.format.
type MediaStartRecordingRequestFormat string

const (
	MediaStartRecordingRequestFormatWav MediaStartRecordingRequestFormat = "wav"
)

// MediaStartRecordingRequestFormatValues lists every member of the vocabulary, in contract order.
var MediaStartRecordingRequestFormatValues = []MediaStartRecordingRequestFormat{
	MediaStartRecordingRequestFormatWav,
}

// Valid reports whether v is a member of the MediaStartRecordingRequestFormat vocabulary.
func (v MediaStartRecordingRequestFormat) Valid() bool {
	for _, candidate := range MediaStartRecordingRequestFormatValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaStartRecordingRequestFormat) String() string { return string(v) }

// MediaStartRecordingResponse is the reply body of rpc.media.v1.start-recording.
type MediaStartRecordingResponse struct {
	Ok           bool                               `json:"ok"`
	SessionID    string                             `json:"sessionId"`
	RecordingRef string                             `json:"recordingRef"`
	ObjectKey    *string                            `json:"objectKey,omitempty"`
	InstanceID   *string                            `json:"instanceId,omitempty"`
	Reason       *MediaStartRecordingResponseReason `json:"reason,omitempty"`
	Error        *string                            `json:"error,omitempty"`
}

// MediaStartRecordingResponseReason is the closed vocabulary of MediaStartRecordingResponse.reason.
type MediaStartRecordingResponseReason string

const (
	MediaStartRecordingResponseReasonBadRequest     MediaStartRecordingResponseReason = "bad_request"
	MediaStartRecordingResponseReasonCapacity       MediaStartRecordingResponseReason = "capacity"
	MediaStartRecordingResponseReasonShuttingDown   MediaStartRecordingResponseReason = "shutting_down"
	MediaStartRecordingResponseReasonUnknownSession MediaStartRecordingResponseReason = "unknown_session"
	MediaStartRecordingResponseReasonWrongInstance  MediaStartRecordingResponseReason = "wrong_instance"
	MediaStartRecordingResponseReasonNotSupported   MediaStartRecordingResponseReason = "not_supported"
	MediaStartRecordingResponseReasonInternal       MediaStartRecordingResponseReason = "internal"
)

// MediaStartRecordingResponseReasonValues lists every member of the vocabulary, in contract order.
var MediaStartRecordingResponseReasonValues = []MediaStartRecordingResponseReason{
	MediaStartRecordingResponseReasonBadRequest,
	MediaStartRecordingResponseReasonCapacity,
	MediaStartRecordingResponseReasonShuttingDown,
	MediaStartRecordingResponseReasonUnknownSession,
	MediaStartRecordingResponseReasonWrongInstance,
	MediaStartRecordingResponseReasonNotSupported,
	MediaStartRecordingResponseReasonInternal,
}

// Valid reports whether v is a member of the MediaStartRecordingResponseReason vocabulary.
func (v MediaStartRecordingResponseReason) Valid() bool {
	for _, candidate := range MediaStartRecordingResponseReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaStartRecordingResponseReason) String() string { return string(v) }

// MediaStopRecordingRequest is the request body of rpc.media.v1.stop-recording.
type MediaStopRecordingRequest struct {
	RecordingRef string `json:"recordingRef"`
}

// MediaStopRecordingResponse is the reply body of rpc.media.v1.stop-recording.
type MediaStopRecordingResponse struct {
	Ok           bool                              `json:"ok"`
	RecordingRef string                            `json:"recordingRef"`
	Stopped      bool                              `json:"stopped"`
	SessionID    *string                           `json:"sessionId,omitempty"`
	InstanceID   *string                           `json:"instanceId,omitempty"`
	Reason       *MediaStopRecordingResponseReason `json:"reason,omitempty"`
	Error        *string                           `json:"error,omitempty"`
}

// MediaStopRecordingResponseReason is the closed vocabulary of MediaStopRecordingResponse.reason.
type MediaStopRecordingResponseReason string

const (
	MediaStopRecordingResponseReasonBadRequest     MediaStopRecordingResponseReason = "bad_request"
	MediaStopRecordingResponseReasonCapacity       MediaStopRecordingResponseReason = "capacity"
	MediaStopRecordingResponseReasonShuttingDown   MediaStopRecordingResponseReason = "shutting_down"
	MediaStopRecordingResponseReasonUnknownSession MediaStopRecordingResponseReason = "unknown_session"
	MediaStopRecordingResponseReasonWrongInstance  MediaStopRecordingResponseReason = "wrong_instance"
	MediaStopRecordingResponseReasonNotSupported   MediaStopRecordingResponseReason = "not_supported"
	MediaStopRecordingResponseReasonInternal       MediaStopRecordingResponseReason = "internal"
)

// MediaStopRecordingResponseReasonValues lists every member of the vocabulary, in contract order.
var MediaStopRecordingResponseReasonValues = []MediaStopRecordingResponseReason{
	MediaStopRecordingResponseReasonBadRequest,
	MediaStopRecordingResponseReasonCapacity,
	MediaStopRecordingResponseReasonShuttingDown,
	MediaStopRecordingResponseReasonUnknownSession,
	MediaStopRecordingResponseReasonWrongInstance,
	MediaStopRecordingResponseReasonNotSupported,
	MediaStopRecordingResponseReasonInternal,
}

// Valid reports whether v is a member of the MediaStopRecordingResponseReason vocabulary.
func (v MediaStopRecordingResponseReason) Valid() bool {
	for _, candidate := range MediaStopRecordingResponseReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v MediaStopRecordingResponseReason) String() string { return string(v) }

// OriginateRequest is the request body of rpc.engine.v1.originate.
type OriginateRequest struct {
	OrgID              string  `json:"orgId"`
	OriginateID        string  `json:"originateId"`
	FromExtension      string  `json:"fromExtension"`
	To                 string  `json:"to"`
	RingTimeoutSeconds *int    `json:"ringTimeoutSeconds,omitempty"`
	CallerIDNumber     *string `json:"callerIdNumber,omitempty"`
	CallerIDName       *string `json:"callerIdName,omitempty"`
	RequestedBy        *string `json:"requestedBy,omitempty"`
}

// OriginateResponse is the reply body of rpc.engine.v1.originate.
type OriginateResponse struct {
	Ok          bool                     `json:"ok"`
	OriginateID string                   `json:"originateId"`
	InstanceID  *string                  `json:"instanceId,omitempty"`
	CallID      *string                  `json:"callId,omitempty"`
	LegID       *string                  `json:"legId,omitempty"`
	Endpoint    *string                  `json:"endpoint,omitempty"`
	Destination *string                  `json:"destination,omitempty"`
	Reason      *OriginateResponseReason `json:"reason,omitempty"`
	Error       *string                  `json:"error,omitempty"`
}

// OriginateResponseReason is the closed vocabulary of OriginateResponse.reason.
type OriginateResponseReason string

const (
	OriginateResponseReasonBadRequest       OriginateResponseReason = "bad_request"
	OriginateResponseReasonUnknownExtension OriginateResponseReason = "unknown_extension"
	OriginateResponseReasonExtensionOffline OriginateResponseReason = "extension_offline"
	OriginateResponseReasonInvalidTarget    OriginateResponseReason = "invalid_target"
	OriginateResponseReasonCapacity         OriginateResponseReason = "capacity"
	OriginateResponseReasonNotSupported     OriginateResponseReason = "not_supported"
	OriginateResponseReasonShuttingDown     OriginateResponseReason = "shutting_down"
	OriginateResponseReasonInternal         OriginateResponseReason = "internal"
)

// OriginateResponseReasonValues lists every member of the vocabulary, in contract order.
var OriginateResponseReasonValues = []OriginateResponseReason{
	OriginateResponseReasonBadRequest,
	OriginateResponseReasonUnknownExtension,
	OriginateResponseReasonExtensionOffline,
	OriginateResponseReasonInvalidTarget,
	OriginateResponseReasonCapacity,
	OriginateResponseReasonNotSupported,
	OriginateResponseReasonShuttingDown,
	OriginateResponseReasonInternal,
}

// Valid reports whether v is a member of the OriginateResponseReason vocabulary.
func (v OriginateResponseReason) Valid() bool {
	for _, candidate := range OriginateResponseReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v OriginateResponseReason) String() string { return string(v) }

// ParkHandoffRequest is the request body of rpc.engine.v1.park-handoff.
type ParkHandoffRequest struct {
	OrgID                   string `json:"orgId"`
	ParkLotID               string `json:"parkLotId"`
	Slot                    int    `json:"slot"`
	MediaChannelID          string `json:"mediaChannelId"`
	RetrieverInstanceID     string `json:"retrieverInstanceId"`
	RetrieverMediaChannelID string `json:"retrieverMediaChannelId"`
	RetrieverLegID          string `json:"retrieverLegId"`
	BridgeID                string `json:"bridgeId"`
}

// ParkHandoffResponse is the reply body of rpc.engine.v1.park-handoff.
type ParkHandoffResponse struct {
	Ok         bool                       `json:"ok"`
	ParkLotID  string                     `json:"parkLotId"`
	Slot       int                        `json:"slot"`
	InstanceID string                     `json:"instanceId"`
	BridgeID   *string                    `json:"bridgeId,omitempty"`
	LegID      *string                    `json:"legId,omitempty"`
	CallID     *string                    `json:"callId,omitempty"`
	ParkedAtMs *int                       `json:"parkedAtMs,omitempty"`
	Reason     *ParkHandoffResponseReason `json:"reason,omitempty"`
	Error      *string                    `json:"error,omitempty"`
}

// ParkHandoffResponseReason is the closed vocabulary of ParkHandoffResponse.reason.
type ParkHandoffResponseReason string

const (
	ParkHandoffResponseReasonBadRequest         ParkHandoffResponseReason = "bad_request"
	ParkHandoffResponseReasonNotParked          ParkHandoffResponseReason = "not_parked"
	ParkHandoffResponseReasonClaimSuperseded    ParkHandoffResponseReason = "claim_superseded"
	ParkHandoffResponseReasonChannelGone        ParkHandoffResponseReason = "channel_gone"
	ParkHandoffResponseReasonUnreachableChannel ParkHandoffResponseReason = "unreachable_channel"
	ParkHandoffResponseReasonMediaFailed        ParkHandoffResponseReason = "media_failed"
	ParkHandoffResponseReasonShuttingDown       ParkHandoffResponseReason = "shutting_down"
	ParkHandoffResponseReasonInternal           ParkHandoffResponseReason = "internal"
)

// ParkHandoffResponseReasonValues lists every member of the vocabulary, in contract order.
var ParkHandoffResponseReasonValues = []ParkHandoffResponseReason{
	ParkHandoffResponseReasonBadRequest,
	ParkHandoffResponseReasonNotParked,
	ParkHandoffResponseReasonClaimSuperseded,
	ParkHandoffResponseReasonChannelGone,
	ParkHandoffResponseReasonUnreachableChannel,
	ParkHandoffResponseReasonMediaFailed,
	ParkHandoffResponseReasonShuttingDown,
	ParkHandoffResponseReasonInternal,
}

// Valid reports whether v is a member of the ParkHandoffResponseReason vocabulary.
func (v ParkHandoffResponseReason) Valid() bool {
	for _, candidate := range ParkHandoffResponseReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v ParkHandoffResponseReason) String() string { return string(v) }
