// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
// Source: packages/events/src; regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Payloads for the security event family.

package events

import "slices"

// Event types carried on the security family's subjects. The value is the envelope's
// `type` discriminator, which is unique WITHIN the family only.
const (
	EventTypeSecurityFraudSignal = "fraud-signal"
)

// SecurityFraudSignalData is the payload of the "fraud-signal" event.
//
// Subject: security.evt.v1.<orgId>.<subjectRef>.fraud-signal
// Envelope: Envelope[SecurityFraudSignalData]
type SecurityFraudSignalData struct {
	Kind               SecurityFraudSignalKind     `json:"kind"`
	Severity           SecurityFraudSignalSeverity `json:"severity"`
	Action             SecurityFraudSignalAction   `json:"action"`
	ExtensionID        *string                     `json:"extensionId,omitempty"`
	ExtensionNumber    *string                     `json:"extensionNumber,omitempty"`
	Destination        *string                     `json:"destination,omitempty"`
	DestinationCountry *string                     `json:"destinationCountry,omitempty"`
	Observed           *float64                    `json:"observed,omitempty"`
	Threshold          *float64                    `json:"threshold,omitempty"`
	WindowSeconds      *int                        `json:"windowSeconds,omitempty"`
	Summary            string                      `json:"summary"`
}

// SecurityFraudSignalKind is the closed vocabulary of SecurityFraudSignalData.kind.
type SecurityFraudSignalKind string

const (
	SecurityFraudSignalKindInternationalMinutesSpike        SecurityFraudSignalKind = "international-minutes-spike"
	SecurityFraudSignalKindHighRiskPrefix                   SecurityFraudSignalKind = "high-risk-prefix"
	SecurityFraudSignalKindShortCallBurst                   SecurityFraudSignalKind = "short-call-burst"
	SecurityFraudSignalKindRegistrationSourceSpread         SecurityFraudSignalKind = "registration-source-spread"
	SecurityFraudSignalKindInternationalConcurrencyExceeded SecurityFraudSignalKind = "international-concurrency-exceeded"
	SecurityFraudSignalKindInternationalMinutesExceeded     SecurityFraudSignalKind = "international-minutes-exceeded"
	SecurityFraudSignalKindDestinationCountryBlocked        SecurityFraudSignalKind = "destination-country-blocked"
	SecurityFraudSignalKindNewCountryHold                   SecurityFraudSignalKind = "new-country-hold"
	SecurityFraudSignalKindOffHoursInternationalLock        SecurityFraudSignalKind = "off-hours-international-lock"
)

// SecurityFraudSignalKindValues lists every member of the vocabulary, in contract order.
var SecurityFraudSignalKindValues = []SecurityFraudSignalKind{
	SecurityFraudSignalKindInternationalMinutesSpike,
	SecurityFraudSignalKindHighRiskPrefix,
	SecurityFraudSignalKindShortCallBurst,
	SecurityFraudSignalKindRegistrationSourceSpread,
	SecurityFraudSignalKindInternationalConcurrencyExceeded,
	SecurityFraudSignalKindInternationalMinutesExceeded,
	SecurityFraudSignalKindDestinationCountryBlocked,
	SecurityFraudSignalKindNewCountryHold,
	SecurityFraudSignalKindOffHoursInternationalLock,
}

// Valid reports whether v is a member of the SecurityFraudSignalKind vocabulary.
func (v SecurityFraudSignalKind) Valid() bool {
	return slices.Contains(SecurityFraudSignalKindValues, v)
}

func (v SecurityFraudSignalKind) String() string { return string(v) }

// SecurityFraudSignalSeverity is the closed vocabulary of SecurityFraudSignalData.severity.
type SecurityFraudSignalSeverity string

const (
	SecurityFraudSignalSeverityInfo     SecurityFraudSignalSeverity = "info"
	SecurityFraudSignalSeverityWarning  SecurityFraudSignalSeverity = "warning"
	SecurityFraudSignalSeverityCritical SecurityFraudSignalSeverity = "critical"
)

// SecurityFraudSignalSeverityValues lists every member of the vocabulary, in contract order.
var SecurityFraudSignalSeverityValues = []SecurityFraudSignalSeverity{
	SecurityFraudSignalSeverityInfo,
	SecurityFraudSignalSeverityWarning,
	SecurityFraudSignalSeverityCritical,
}

// Valid reports whether v is a member of the SecurityFraudSignalSeverity vocabulary.
func (v SecurityFraudSignalSeverity) Valid() bool {
	return slices.Contains(SecurityFraudSignalSeverityValues, v)
}

func (v SecurityFraudSignalSeverity) String() string { return string(v) }

// SecurityFraudSignalAction is the closed vocabulary of SecurityFraudSignalData.action.
type SecurityFraudSignalAction string

const (
	SecurityFraudSignalActionNone               SecurityFraudSignalAction = "none"
	SecurityFraudSignalActionCallRefused        SecurityFraudSignalAction = "call-refused"
	SecurityFraudSignalActionExtensionSuspended SecurityFraudSignalAction = "extension-suspended"
)

// SecurityFraudSignalActionValues lists every member of the vocabulary, in contract order.
var SecurityFraudSignalActionValues = []SecurityFraudSignalAction{
	SecurityFraudSignalActionNone,
	SecurityFraudSignalActionCallRefused,
	SecurityFraudSignalActionExtensionSuspended,
}

// Valid reports whether v is a member of the SecurityFraudSignalAction vocabulary.
func (v SecurityFraudSignalAction) Valid() bool {
	return slices.Contains(SecurityFraudSignalActionValues, v)
}

func (v SecurityFraudSignalAction) String() string { return string(v) }
