// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Payloads for the sipDialog event family.

package events

// Event types carried on the sipDialog family's subjects. The value is the envelope's
// `type` discriminator, which is unique WITHIN the family only.
const (
	EventTypeSIPDialogProgressed = "dialog.progressed"
	EventTypeSIPDialogAnswered   = "dialog.answered"
	EventTypeSIPDialogHeld       = "dialog.held"
	EventTypeSIPDialogResumed    = "dialog.resumed"
	EventTypeSIPDialogTerminated = "dialog.terminated"
	EventTypeSIPDialogDTMF       = "dialog.dtmf"
)

// SIPDialogProgressedData is the payload of the "dialog.progressed" event.
//
// Subject: sip.evt.v1.<orgId>.<legId>.dialog.progressed
// Envelope: Envelope[SIPDialogProgressedData]
type SIPDialogProgressedData struct {
	LegID         string                      `json:"legId"`
	CallID        string                      `json:"callId"`
	InstanceID    string                      `json:"instanceId"`
	Role          SIPDialogProgressedRole     `json:"role"`
	Identity      SIPDialogProgressedIdentity `json:"identity"`
	Status        int                         `json:"status"`
	HasEarlyMedia bool                        `json:"hasEarlyMedia"`
	SDPAnswer     *string                     `json:"sdpAnswer,omitempty"`
}

// SIPDialogProgressedRole is the closed vocabulary of SIPDialogProgressedData.role.
type SIPDialogProgressedRole string

const (
	SIPDialogProgressedRoleUas SIPDialogProgressedRole = "uas"
	SIPDialogProgressedRoleUac SIPDialogProgressedRole = "uac"
)

// SIPDialogProgressedRoleValues lists every member of the vocabulary, in contract order.
var SIPDialogProgressedRoleValues = []SIPDialogProgressedRole{
	SIPDialogProgressedRoleUas,
	SIPDialogProgressedRoleUac,
}

// Valid reports whether v is a member of the SIPDialogProgressedRole vocabulary.
func (v SIPDialogProgressedRole) Valid() bool {
	for _, candidate := range SIPDialogProgressedRoleValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SIPDialogProgressedRole) String() string { return string(v) }

// SIPDialogProgressedIdentity is a payload fragment of the contract.
type SIPDialogProgressedIdentity struct {
	SIPCallID string  `json:"sipCallId"`
	LocalTag  *string `json:"localTag,omitempty"`
	RemoteTag *string `json:"remoteTag,omitempty"`
}

// SIPDialogAnsweredData is the payload of the "dialog.answered" event.
//
// Subject: sip.evt.v1.<orgId>.<legId>.dialog.answered
// Envelope: Envelope[SIPDialogAnsweredData]
type SIPDialogAnsweredData struct {
	LegID      string                    `json:"legId"`
	CallID     string                    `json:"callId"`
	InstanceID string                    `json:"instanceId"`
	Role       SIPDialogAnsweredRole     `json:"role"`
	Identity   SIPDialogAnsweredIdentity `json:"identity"`
	SDPAnswer  *string                   `json:"sdpAnswer,omitempty"`
	SetupMs    *int                      `json:"setupMs,omitempty"`
}

// SIPDialogAnsweredRole is the closed vocabulary of SIPDialogAnsweredData.role.
type SIPDialogAnsweredRole string

const (
	SIPDialogAnsweredRoleUas SIPDialogAnsweredRole = "uas"
	SIPDialogAnsweredRoleUac SIPDialogAnsweredRole = "uac"
)

// SIPDialogAnsweredRoleValues lists every member of the vocabulary, in contract order.
var SIPDialogAnsweredRoleValues = []SIPDialogAnsweredRole{
	SIPDialogAnsweredRoleUas,
	SIPDialogAnsweredRoleUac,
}

// Valid reports whether v is a member of the SIPDialogAnsweredRole vocabulary.
func (v SIPDialogAnsweredRole) Valid() bool {
	for _, candidate := range SIPDialogAnsweredRoleValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SIPDialogAnsweredRole) String() string { return string(v) }

// SIPDialogAnsweredIdentity is a payload fragment of the contract.
type SIPDialogAnsweredIdentity struct {
	SIPCallID string  `json:"sipCallId"`
	LocalTag  *string `json:"localTag,omitempty"`
	RemoteTag *string `json:"remoteTag,omitempty"`
}

// SIPDialogHeldData is the payload of the "dialog.held" event.
//
// Subject: sip.evt.v1.<orgId>.<legId>.dialog.held
// Envelope: Envelope[SIPDialogHeldData]
type SIPDialogHeldData struct {
	LegID      string                 `json:"legId"`
	CallID     string                 `json:"callId"`
	InstanceID string                 `json:"instanceId"`
	Role       SIPDialogHeldRole      `json:"role"`
	Identity   SIPDialogHeldIdentity  `json:"identity"`
	Direction  SIPDialogHeldDirection `json:"direction"`
}

// SIPDialogHeldRole is the closed vocabulary of SIPDialogHeldData.role.
type SIPDialogHeldRole string

const (
	SIPDialogHeldRoleUas SIPDialogHeldRole = "uas"
	SIPDialogHeldRoleUac SIPDialogHeldRole = "uac"
)

// SIPDialogHeldRoleValues lists every member of the vocabulary, in contract order.
var SIPDialogHeldRoleValues = []SIPDialogHeldRole{
	SIPDialogHeldRoleUas,
	SIPDialogHeldRoleUac,
}

// Valid reports whether v is a member of the SIPDialogHeldRole vocabulary.
func (v SIPDialogHeldRole) Valid() bool {
	for _, candidate := range SIPDialogHeldRoleValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SIPDialogHeldRole) String() string { return string(v) }

// SIPDialogHeldIdentity is a payload fragment of the contract.
type SIPDialogHeldIdentity struct {
	SIPCallID string  `json:"sipCallId"`
	LocalTag  *string `json:"localTag,omitempty"`
	RemoteTag *string `json:"remoteTag,omitempty"`
}

// SIPDialogHeldDirection is the closed vocabulary of SIPDialogHeldData.direction.
type SIPDialogHeldDirection string

const (
	SIPDialogHeldDirectionSendonly SIPDialogHeldDirection = "sendonly"
	SIPDialogHeldDirectionInactive SIPDialogHeldDirection = "inactive"
)

// SIPDialogHeldDirectionValues lists every member of the vocabulary, in contract order.
var SIPDialogHeldDirectionValues = []SIPDialogHeldDirection{
	SIPDialogHeldDirectionSendonly,
	SIPDialogHeldDirectionInactive,
}

// Valid reports whether v is a member of the SIPDialogHeldDirection vocabulary.
func (v SIPDialogHeldDirection) Valid() bool {
	for _, candidate := range SIPDialogHeldDirectionValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SIPDialogHeldDirection) String() string { return string(v) }

// SIPDialogResumedData is the payload of the "dialog.resumed" event.
//
// Subject: sip.evt.v1.<orgId>.<legId>.dialog.resumed
// Envelope: Envelope[SIPDialogResumedData]
type SIPDialogResumedData struct {
	LegID      string                    `json:"legId"`
	CallID     string                    `json:"callId"`
	InstanceID string                    `json:"instanceId"`
	Role       SIPDialogResumedRole      `json:"role"`
	Identity   SIPDialogResumedIdentity  `json:"identity"`
	Direction  SIPDialogResumedDirection `json:"direction"`
}

// SIPDialogResumedRole is the closed vocabulary of SIPDialogResumedData.role.
type SIPDialogResumedRole string

const (
	SIPDialogResumedRoleUas SIPDialogResumedRole = "uas"
	SIPDialogResumedRoleUac SIPDialogResumedRole = "uac"
)

// SIPDialogResumedRoleValues lists every member of the vocabulary, in contract order.
var SIPDialogResumedRoleValues = []SIPDialogResumedRole{
	SIPDialogResumedRoleUas,
	SIPDialogResumedRoleUac,
}

// Valid reports whether v is a member of the SIPDialogResumedRole vocabulary.
func (v SIPDialogResumedRole) Valid() bool {
	for _, candidate := range SIPDialogResumedRoleValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SIPDialogResumedRole) String() string { return string(v) }

// SIPDialogResumedIdentity is a payload fragment of the contract.
type SIPDialogResumedIdentity struct {
	SIPCallID string  `json:"sipCallId"`
	LocalTag  *string `json:"localTag,omitempty"`
	RemoteTag *string `json:"remoteTag,omitempty"`
}

// SIPDialogResumedDirection is the closed vocabulary of SIPDialogResumedData.direction.
type SIPDialogResumedDirection string

const (
	SIPDialogResumedDirectionSendrecv SIPDialogResumedDirection = "sendrecv"
	SIPDialogResumedDirectionRecvonly SIPDialogResumedDirection = "recvonly"
)

// SIPDialogResumedDirectionValues lists every member of the vocabulary, in contract order.
var SIPDialogResumedDirectionValues = []SIPDialogResumedDirection{
	SIPDialogResumedDirectionSendrecv,
	SIPDialogResumedDirectionRecvonly,
}

// Valid reports whether v is a member of the SIPDialogResumedDirection vocabulary.
func (v SIPDialogResumedDirection) Valid() bool {
	for _, candidate := range SIPDialogResumedDirectionValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SIPDialogResumedDirection) String() string { return string(v) }

// SIPDialogTerminatedData is the payload of the "dialog.terminated" event.
//
// Subject: sip.evt.v1.<orgId>.<legId>.dialog.terminated
// Envelope: Envelope[SIPDialogTerminatedData]
type SIPDialogTerminatedData struct {
	LegID                 string                       `json:"legId"`
	CallID                string                       `json:"callId"`
	InstanceID            string                       `json:"instanceId"`
	Role                  SIPDialogTerminatedRole      `json:"role"`
	Identity              SIPDialogTerminatedIdentity  `json:"identity"`
	Reason                SIPDialogTerminatedReason    `json:"reason"`
	Cause                 int                          `json:"cause"`
	Status                *int                         `json:"status,omitempty"`
	CauseFromReasonHeader bool                         `json:"causeFromReasonHeader"`
	Initiator             SIPDialogTerminatedInitiator `json:"initiator"`
	AnsweredForSeconds    *int                         `json:"answeredForSeconds,omitempty"`
}

// SIPDialogTerminatedRole is the closed vocabulary of SIPDialogTerminatedData.role.
type SIPDialogTerminatedRole string

const (
	SIPDialogTerminatedRoleUas SIPDialogTerminatedRole = "uas"
	SIPDialogTerminatedRoleUac SIPDialogTerminatedRole = "uac"
)

// SIPDialogTerminatedRoleValues lists every member of the vocabulary, in contract order.
var SIPDialogTerminatedRoleValues = []SIPDialogTerminatedRole{
	SIPDialogTerminatedRoleUas,
	SIPDialogTerminatedRoleUac,
}

// Valid reports whether v is a member of the SIPDialogTerminatedRole vocabulary.
func (v SIPDialogTerminatedRole) Valid() bool {
	for _, candidate := range SIPDialogTerminatedRoleValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SIPDialogTerminatedRole) String() string { return string(v) }

// SIPDialogTerminatedIdentity is a payload fragment of the contract.
type SIPDialogTerminatedIdentity struct {
	SIPCallID string  `json:"sipCallId"`
	LocalTag  *string `json:"localTag,omitempty"`
	RemoteTag *string `json:"remoteTag,omitempty"`
}

// SIPDialogTerminatedReason is the closed vocabulary of SIPDialogTerminatedData.reason.
type SIPDialogTerminatedReason string

const (
	SIPDialogTerminatedReasonBye          SIPDialogTerminatedReason = "bye"
	SIPDialogTerminatedReasonCancelled    SIPDialogTerminatedReason = "cancelled"
	SIPDialogTerminatedReasonRejected     SIPDialogTerminatedReason = "rejected"
	SIPDialogTerminatedReasonTimeout      SIPDialogTerminatedReason = "timeout"
	SIPDialogTerminatedReasonReplaced     SIPDialogTerminatedReason = "replaced"
	SIPDialogTerminatedReasonInstanceLost SIPDialogTerminatedReason = "instance-lost"
	SIPDialogTerminatedReasonShuttingDown SIPDialogTerminatedReason = "shutting-down"
)

// SIPDialogTerminatedReasonValues lists every member of the vocabulary, in contract order.
var SIPDialogTerminatedReasonValues = []SIPDialogTerminatedReason{
	SIPDialogTerminatedReasonBye,
	SIPDialogTerminatedReasonCancelled,
	SIPDialogTerminatedReasonRejected,
	SIPDialogTerminatedReasonTimeout,
	SIPDialogTerminatedReasonReplaced,
	SIPDialogTerminatedReasonInstanceLost,
	SIPDialogTerminatedReasonShuttingDown,
}

// Valid reports whether v is a member of the SIPDialogTerminatedReason vocabulary.
func (v SIPDialogTerminatedReason) Valid() bool {
	for _, candidate := range SIPDialogTerminatedReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SIPDialogTerminatedReason) String() string { return string(v) }

// SIPDialogTerminatedInitiator is the closed vocabulary of SIPDialogTerminatedData.initiator.
type SIPDialogTerminatedInitiator string

const (
	SIPDialogTerminatedInitiatorLocal  SIPDialogTerminatedInitiator = "local"
	SIPDialogTerminatedInitiatorRemote SIPDialogTerminatedInitiator = "remote"
	SIPDialogTerminatedInitiatorTimer  SIPDialogTerminatedInitiator = "timer"
)

// SIPDialogTerminatedInitiatorValues lists every member of the vocabulary, in contract order.
var SIPDialogTerminatedInitiatorValues = []SIPDialogTerminatedInitiator{
	SIPDialogTerminatedInitiatorLocal,
	SIPDialogTerminatedInitiatorRemote,
	SIPDialogTerminatedInitiatorTimer,
}

// Valid reports whether v is a member of the SIPDialogTerminatedInitiator vocabulary.
func (v SIPDialogTerminatedInitiator) Valid() bool {
	for _, candidate := range SIPDialogTerminatedInitiatorValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SIPDialogTerminatedInitiator) String() string { return string(v) }

// SIPDialogDTMFData is the payload of the "dialog.dtmf" event.
//
// Subject: sip.evt.v1.<orgId>.<legId>.dialog.dtmf
// Envelope: Envelope[SIPDialogDTMFData]
type SIPDialogDTMFData struct {
	LegID      string                `json:"legId"`
	CallID     string                `json:"callId"`
	InstanceID string                `json:"instanceId"`
	Role       SIPDialogDTMFRole     `json:"role"`
	Identity   SIPDialogDTMFIdentity `json:"identity"`
	Digit      string                `json:"digit"`
	DurationMs *int                  `json:"durationMs,omitempty"`
}

// SIPDialogDTMFRole is the closed vocabulary of SIPDialogDTMFData.role.
type SIPDialogDTMFRole string

const (
	SIPDialogDTMFRoleUas SIPDialogDTMFRole = "uas"
	SIPDialogDTMFRoleUac SIPDialogDTMFRole = "uac"
)

// SIPDialogDTMFRoleValues lists every member of the vocabulary, in contract order.
var SIPDialogDTMFRoleValues = []SIPDialogDTMFRole{
	SIPDialogDTMFRoleUas,
	SIPDialogDTMFRoleUac,
}

// Valid reports whether v is a member of the SIPDialogDTMFRole vocabulary.
func (v SIPDialogDTMFRole) Valid() bool {
	for _, candidate := range SIPDialogDTMFRoleValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SIPDialogDTMFRole) String() string { return string(v) }

// SIPDialogDTMFIdentity is a payload fragment of the contract.
type SIPDialogDTMFIdentity struct {
	SIPCallID string  `json:"sipCallId"`
	LocalTag  *string `json:"localTag,omitempty"`
	RemoteTag *string `json:"remoteTag,omitempty"`
}
