// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Closed telephony vocabularies shared by every event family.
//
// Authority: packages/events/src/schemas/telephony.ts. Large, still-growing domains
// (hangup causes, destination types, dispositions) are deliberately plain strings there
// and here — see that file's header for why.

package events

// LegSide — A-leg is the originating/inbound side; B-leg is every leg the engine originated for it.
//
// Source: packages/events/src/schemas/telephony.ts LEG_SIDES.
type LegSide string

const (
	LegSideA LegSide = "a"
	LegSideB LegSide = "b"
)

// LegSideValues lists every member of the vocabulary, in contract order.
var LegSideValues = []LegSide{
	LegSideA,
	LegSideB,
}

// Valid reports whether v is a member of the LegSide vocabulary.
func (v LegSide) Valid() bool {
	for _, candidate := range LegSideValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v LegSide) String() string { return string(v) }

// CallDirection — Direction as the organization sees it, not as the switch sees it.
//
// Source: packages/events/src/schemas/telephony.ts CALL_DIRECTIONS.
type CallDirection string

const (
	CallDirectionInbound  CallDirection = "inbound"
	CallDirectionOutbound CallDirection = "outbound"
	CallDirectionInternal CallDirection = "internal"
)

// CallDirectionValues lists every member of the vocabulary, in contract order.
var CallDirectionValues = []CallDirection{
	CallDirectionInbound,
	CallDirectionOutbound,
	CallDirectionInternal,
}

// Valid reports whether v is a member of the CallDirection vocabulary.
func (v CallDirection) Valid() bool {
	for _, candidate := range CallDirectionValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v CallDirection) String() string { return string(v) }

// HangupSide — Which side tore the call down; system covers engine/media timeouts and admin hangups.
//
// Source: packages/events/src/schemas/telephony.ts HANGUP_SIDES.
type HangupSide string

const (
	HangupSideCaller HangupSide = "caller"
	HangupSideCallee HangupSide = "callee"
	HangupSideSystem HangupSide = "system"
)

// HangupSideValues lists every member of the vocabulary, in contract order.
var HangupSideValues = []HangupSide{
	HangupSideCaller,
	HangupSideCallee,
	HangupSideSystem,
}

// Valid reports whether v is a member of the HangupSide vocabulary.
func (v HangupSide) Valid() bool {
	for _, candidate := range HangupSideValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v HangupSide) String() string { return string(v) }

// BridgeMode — Bridge modes, from plans/reference/freeswitch-capabilities.md §1.
//
// Source: packages/events/src/schemas/telephony.ts BRIDGE_MODES.
type BridgeMode string

const (
	BridgeModeMedia      BridgeMode = "media"
	BridgeModeProxyMedia BridgeMode = "proxy-media"
	BridgeModeSignalOnly BridgeMode = "signal-only"
	BridgeModeBypass     BridgeMode = "bypass"
)

// BridgeModeValues lists every member of the vocabulary, in contract order.
var BridgeModeValues = []BridgeMode{
	BridgeModeMedia,
	BridgeModeProxyMedia,
	BridgeModeSignalOnly,
	BridgeModeBypass,
}

// Valid reports whether v is a member of the BridgeMode vocabulary.
func (v BridgeMode) Valid() bool {
	for _, candidate := range BridgeModeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v BridgeMode) String() string { return string(v) }

// DTMFSource — DTMF transports, from the frozen reference §4.
//
// Source: packages/events/src/schemas/telephony.ts DTMF_SOURCES.
type DTMFSource string

const (
	DTMFSourceRFC2833     DTMFSource = "rfc2833"
	DTMFSourceInfo        DTMFSource = "info"
	DTMFSourceInband      DTMFSource = "inband"
	DTMFSourceApplication DTMFSource = "application"
)

// DTMFSourceValues lists every member of the vocabulary, in contract order.
var DTMFSourceValues = []DTMFSource{
	DTMFSourceRFC2833,
	DTMFSourceInfo,
	DTMFSourceInband,
	DTMFSourceApplication,
}

// Valid reports whether v is a member of the DTMFSource vocabulary.
func (v DTMFSource) Valid() bool {
	for _, candidate := range DTMFSourceValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v DTMFSource) String() string { return string(v) }

// RecordingKind — What produced a stored media object.
//
// Source: packages/events/src/schemas/telephony.ts RECORDING_KINDS.
type RecordingKind string

const (
	RecordingKindCall       RecordingKind = "call"
	RecordingKindVoicemail  RecordingKind = "voicemail"
	RecordingKindConference RecordingKind = "conference"
)

// RecordingKindValues lists every member of the vocabulary, in contract order.
var RecordingKindValues = []RecordingKind{
	RecordingKindCall,
	RecordingKindVoicemail,
	RecordingKindConference,
}

// Valid reports whether v is a member of the RecordingKind vocabulary.
func (v RecordingKind) Valid() bool {
	for _, candidate := range RecordingKindValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v RecordingKind) String() string { return string(v) }

// RecordingStopReason — How a recording ended.
//
// Source: packages/events/src/schemas/telephony.ts RECORDING_STOP_REASONS.
type RecordingStopReason string

const (
	RecordingStopReasonCompleted RecordingStopReason = "completed"
	RecordingStopReasonCancelled RecordingStopReason = "cancelled"
	RecordingStopReasonFailed    RecordingStopReason = "failed"
)

// RecordingStopReasonValues lists every member of the vocabulary, in contract order.
var RecordingStopReasonValues = []RecordingStopReason{
	RecordingStopReasonCompleted,
	RecordingStopReasonCancelled,
	RecordingStopReasonFailed,
}

// Valid reports whether v is a member of the RecordingStopReason vocabulary.
func (v RecordingStopReason) Valid() bool {
	for _, candidate := range RecordingStopReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v RecordingStopReason) String() string { return string(v) }

// SIPTransport — SIP transports the edge accepts.
//
// Source: packages/events/src/schemas/telephony.ts SIP_TRANSPORTS.
type SIPTransport string

const (
	SIPTransportUDP SIPTransport = "udp"
	SIPTransportTCP SIPTransport = "tcp"
	SIPTransportTLS SIPTransport = "tls"
	SIPTransportWS  SIPTransport = "ws"
	SIPTransportWSS SIPTransport = "wss"
)

// SIPTransportValues lists every member of the vocabulary, in contract order.
var SIPTransportValues = []SIPTransport{
	SIPTransportUDP,
	SIPTransportTCP,
	SIPTransportTLS,
	SIPTransportWS,
	SIPTransportWSS,
}

// Valid reports whether v is a member of the SIPTransport vocabulary.
func (v SIPTransport) Valid() bool {
	for _, candidate := range SIPTransportValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v SIPTransport) String() string { return string(v) }

// AgentStatus — ACD agent status. Drives queue distribution and the wallboard.
//
// Source: packages/events/src/schemas/telephony.ts AGENT_STATUSES.
type AgentStatus string

const (
	AgentStatusLoggedOut   AgentStatus = "logged-out"
	AgentStatusAvailable   AgentStatus = "available"
	AgentStatusRinging     AgentStatus = "ringing"
	AgentStatusOnCall      AgentStatus = "on-call"
	AgentStatusWrapUp      AgentStatus = "wrap-up"
	AgentStatusOnBreak     AgentStatus = "on-break"
	AgentStatusUnavailable AgentStatus = "unavailable"
)

// AgentStatusValues lists every member of the vocabulary, in contract order.
var AgentStatusValues = []AgentStatus{
	AgentStatusLoggedOut,
	AgentStatusAvailable,
	AgentStatusRinging,
	AgentStatusOnCall,
	AgentStatusWrapUp,
	AgentStatusOnBreak,
	AgentStatusUnavailable,
}

// Valid reports whether v is a member of the AgentStatus vocabulary.
func (v AgentStatus) Valid() bool {
	for _, candidate := range AgentStatusValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v AgentStatus) String() string { return string(v) }

// TapMode — What a supervisor is doing to a call they did not place: eavesdrop, whisper or barge.
//
// Source: packages/events/src/schemas/telephony.ts TAP_MODES.
type TapMode string

const (
	TapModeEavesdrop TapMode = "eavesdrop"
	TapModeWhisper   TapMode = "whisper"
	TapModeBarge     TapMode = "barge"
)

// TapModeValues lists every member of the vocabulary, in contract order.
var TapModeValues = []TapMode{
	TapModeEavesdrop,
	TapModeWhisper,
	TapModeBarge,
}

// Valid reports whether v is a member of the TapMode vocabulary.
func (v TapMode) Valid() bool {
	for _, candidate := range TapModeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v TapMode) String() string { return string(v) }

// TapEndReason — How a supervisor's tap ended. Distinguishes the monitored call ending from the supervisor leaving.
//
// Source: packages/events/src/schemas/telephony.ts TAP_END_REASONS.
type TapEndReason string

const (
	TapEndReasonSupervisorEnded TapEndReason = "supervisor-ended"
	TapEndReasonTargetEnded     TapEndReason = "target-ended"
	TapEndReasonEscalated       TapEndReason = "escalated"
	TapEndReasonFailed          TapEndReason = "failed"
)

// TapEndReasonValues lists every member of the vocabulary, in contract order.
var TapEndReasonValues = []TapEndReason{
	TapEndReasonSupervisorEnded,
	TapEndReasonTargetEnded,
	TapEndReasonEscalated,
	TapEndReasonFailed,
}

// Valid reports whether v is a member of the TapEndReason vocabulary.
func (v TapEndReason) Valid() bool {
	for _, candidate := range TapEndReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v TapEndReason) String() string { return string(v) }
