// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Payloads for the trunk event family.

package events

// Event types carried on the trunk family's subjects. The value is the envelope's
// `type` discriminator, which is unique WITHIN the family only.
const (
	EventTypeTrunkStatusChanged = "status.changed"
)

// TrunkStatusChangedData is the payload of the "status.changed" event.
//
// Subject: trunk.evt.v1.<orgId>.<trunkId>.status.changed
// Envelope: Envelope[TrunkStatusChangedData]
type TrunkStatusChangedData struct {
	Status    TrunkStatusChangedStatus `json:"status"`
	Reason    *string                  `json:"reason,omitempty"`
	LatencyMs *int                     `json:"latencyMs,omitempty"`
	Endpoint  *string                  `json:"endpoint,omitempty"`
}

// TrunkStatusChangedStatus is the closed vocabulary of TrunkStatusChangedData.status.
type TrunkStatusChangedStatus string

const (
	TrunkStatusChangedStatusUnknown  TrunkStatusChangedStatus = "unknown"
	TrunkStatusChangedStatusUp       TrunkStatusChangedStatus = "up"
	TrunkStatusChangedStatusDown     TrunkStatusChangedStatus = "down"
	TrunkStatusChangedStatusDegraded TrunkStatusChangedStatus = "degraded"
	TrunkStatusChangedStatusDisabled TrunkStatusChangedStatus = "disabled"
)

// TrunkStatusChangedStatusValues lists every member of the vocabulary, in contract order.
var TrunkStatusChangedStatusValues = []TrunkStatusChangedStatus{
	TrunkStatusChangedStatusUnknown,
	TrunkStatusChangedStatusUp,
	TrunkStatusChangedStatusDown,
	TrunkStatusChangedStatusDegraded,
	TrunkStatusChangedStatusDisabled,
}

// Valid reports whether v is a member of the TrunkStatusChangedStatus vocabulary.
func (v TrunkStatusChangedStatus) Valid() bool {
	for _, candidate := range TrunkStatusChangedStatusValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v TrunkStatusChangedStatus) String() string { return string(v) }
