// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Trunk directory contract from schemas/live-state.ts.

package events

import "encoding/json"

// TrunkDirectoryEntry is the API projection stored in the trunks KV bucket.
type TrunkDirectoryEntry struct {
	TrunkID                string                  `json:"trunkId"`
	OrgID                  string                  `json:"orgId"`
	Name                   string                  `json:"name"`
	Kind                   TrunkDirectoryEntryKind `json:"kind"`
	SIPDomain              string                  `json:"sipDomain"`
	SIPProxy               string                  `json:"sipProxy"`
	OutboundProxy          *string                 `json:"outboundProxy,omitempty"`
	AuthUser               *string                 `json:"authUser,omitempty"`
	SecretRef              *string                 `json:"secretRef,omitempty"`
	Transport              SIPTransport            `json:"transport"`
	RegisterExpiresSeconds int                     `json:"registerExpiresSeconds"`
	MaxChannels            *int                    `json:"maxChannels,omitempty"`
	CallerIDNumberOverride *string                 `json:"callerIdNumberOverride,omitempty"`
	Enabled                bool                    `json:"enabled"`
	UpdatedAt              float64                 `json:"updatedAt"`

	// Extra carries every key outside the pinned contract, verbatim. The TS schema is a
	// z.looseObject (see cdr-events.ts) precisely so a producer running ahead of the
	// consumer is not silently truncated; dropping these on the Go side would reintroduce
	// the loss the loose schema exists to prevent.
	Extra map[string]json.RawMessage `json:"-"`
}

// MarshalJSON merges Extra back into the object, pinned fields winning on conflict.
func (v TrunkDirectoryEntry) MarshalJSON() ([]byte, error) {
	type alias TrunkDirectoryEntry
	return marshalWithExtras(alias(v), v.Extra)
}

// UnmarshalJSON captures unknown keys into Extra instead of discarding them.
func (v *TrunkDirectoryEntry) UnmarshalJSON(data []byte) error {
	type alias TrunkDirectoryEntry
	var inner alias
	extra, err := unmarshalWithExtras(data, &inner, knownKeysTrunkDirectoryEntry)
	if err != nil {
		return err
	}
	*v = TrunkDirectoryEntry(inner)
	v.Extra = extra
	return nil
}

var knownKeysTrunkDirectoryEntry = map[string]struct{}{
	"trunkId":                {},
	"orgId":                  {},
	"name":                   {},
	"kind":                   {},
	"sipDomain":              {},
	"sipProxy":               {},
	"outboundProxy":          {},
	"authUser":               {},
	"secretRef":              {},
	"transport":              {},
	"registerExpiresSeconds": {},
	"maxChannels":            {},
	"callerIdNumberOverride": {},
	"enabled":                {},
	"updatedAt":              {},
}

// TrunkDirectoryEntryKind is the closed vocabulary of TrunkDirectoryEntry.kind.
type TrunkDirectoryEntryKind string

const (
	TrunkDirectoryEntryKindRegister TrunkDirectoryEntryKind = "register"
	TrunkDirectoryEntryKindIPAuth   TrunkDirectoryEntryKind = "ip-auth"
)

// TrunkDirectoryEntryKindValues lists every member of the vocabulary, in contract order.
var TrunkDirectoryEntryKindValues = []TrunkDirectoryEntryKind{
	TrunkDirectoryEntryKindRegister,
	TrunkDirectoryEntryKindIPAuth,
}

// Valid reports whether v is a member of the TrunkDirectoryEntryKind vocabulary.
func (v TrunkDirectoryEntryKind) Valid() bool {
	for _, candidate := range TrunkDirectoryEntryKindValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v TrunkDirectoryEntryKind) String() string { return string(v) }
