// Code generated by packages/events/scripts/generate-go.ts. DO NOT EDIT.
//
// Source of truth: packages/events/src (Zod) -> packages/events/schema (JSON Schema) -> here.
// Regenerate with `pnpm --filter @optimiq-voice/events codegen`.

// Payloads for the voicemail event family.

package events

// Event types carried on the voicemail family's subjects. The value is the envelope's
// `type` discriminator, which is unique WITHIN the family only.
const (
	EventTypeVoicemailMessageLeft = "message.left"
	EventTypeVoicemailMWIUpdated  = "mwi.updated"
)

// VoicemailMessageLeftData is the payload of the "message.left" event.
//
// Subject: voicemail.evt.v1.<orgId>.<mailboxId>.message.left
// Envelope: Envelope[VoicemailMessageLeftData]
type VoicemailMessageLeftData struct {
	MessageID              string    `json:"messageId"`
	MailboxNumber          string    `json:"mailboxNumber"`
	CallID                 string    `json:"callId"`
	LegID                  string    `json:"legId"`
	RecordingID            string    `json:"recordingId"`
	ObjectKey              string    `json:"objectKey"`
	DurationMs             int       `json:"durationMs"`
	SizeBytes              *int      `json:"sizeBytes,omitempty"`
	CallerIDNumber         *string   `json:"callerIdNumber,omitempty"`
	CallerIDName           *string   `json:"callerIdName,omitempty"`
	ReceivedAt             EventTime `json:"receivedAt"`
	TranscriptionRequested *bool     `json:"transcriptionRequested,omitempty"`
}

// VoicemailMWIUpdatedData is the payload of the "mwi.updated" event.
//
// Subject: voicemail.evt.v1.<orgId>.<mailboxId>.mwi.updated
// Envelope: Envelope[VoicemailMWIUpdatedData]
type VoicemailMWIUpdatedData struct {
	MailboxNumber   string                     `json:"mailboxNumber"`
	ExtensionNumber *string                    `json:"extensionNumber,omitempty"`
	NewCount        int                        `json:"newCount"`
	SavedCount      int                        `json:"savedCount"`
	Reason          *VoicemailMWIUpdatedReason `json:"reason,omitempty"`
}

// VoicemailMWIUpdatedReason is the closed vocabulary of VoicemailMWIUpdatedData.reason.
type VoicemailMWIUpdatedReason string

const (
	VoicemailMWIUpdatedReasonMessageLeft    VoicemailMWIUpdatedReason = "message-left"
	VoicemailMWIUpdatedReasonMessageRead    VoicemailMWIUpdatedReason = "message-read"
	VoicemailMWIUpdatedReasonMessageDeleted VoicemailMWIUpdatedReason = "message-deleted"
	VoicemailMWIUpdatedReasonResync         VoicemailMWIUpdatedReason = "resync"
)

// VoicemailMWIUpdatedReasonValues lists every member of the vocabulary, in contract order.
var VoicemailMWIUpdatedReasonValues = []VoicemailMWIUpdatedReason{
	VoicemailMWIUpdatedReasonMessageLeft,
	VoicemailMWIUpdatedReasonMessageRead,
	VoicemailMWIUpdatedReasonMessageDeleted,
	VoicemailMWIUpdatedReasonResync,
}

// Valid reports whether v is a member of the VoicemailMWIUpdatedReason vocabulary.
func (v VoicemailMWIUpdatedReason) Valid() bool {
	for _, candidate := range VoicemailMWIUpdatedReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

func (v VoicemailMWIUpdatedReason) String() string { return string(v) }
