CREATE TABLE "paging_group" (
	"id" uuid PRIMARY KEY,
	"organization_id" uuid NOT NULL,
	"name" text NOT NULL,
	"extension_number" text,
	"duplex" boolean DEFAULT false NOT NULL,
	"timeout_seconds" integer DEFAULT 30 NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "paging_group" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "paging_group_member" (
	"id" uuid PRIMARY KEY,
	"organization_id" uuid NOT NULL,
	"paging_group_id" uuid NOT NULL,
	"extension_id" uuid NOT NULL,
	"ordinal" integer NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "paging_group_member" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "extension" ADD COLUMN "call_screening" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "queue" ADD COLUMN "agent_whisper_prompt_id" uuid;--> statement-breakpoint
CREATE UNIQUE INDEX "paging_group_organization_name_key" ON "paging_group" ("organization_id","name");--> statement-breakpoint
CREATE UNIQUE INDEX "paging_group_organization_extension_number_key" ON "paging_group" ("organization_id","extension_number") WHERE extension_number is not null;--> statement-breakpoint
CREATE INDEX "paging_group_organization_enabled_idx" ON "paging_group" ("organization_id","enabled");--> statement-breakpoint
CREATE UNIQUE INDEX "paging_group_member_group_extension_key" ON "paging_group_member" ("organization_id","paging_group_id","extension_id");--> statement-breakpoint
CREATE UNIQUE INDEX "paging_group_member_group_ordinal_key" ON "paging_group_member" ("organization_id","paging_group_id","ordinal");--> statement-breakpoint
CREATE INDEX "paging_group_member_organization_group_idx" ON "paging_group_member" ("organization_id","paging_group_id");--> statement-breakpoint
ALTER TABLE "paging_group_member" ADD CONSTRAINT "paging_group_member_paging_group_id_paging_group_id_fkey" FOREIGN KEY ("paging_group_id") REFERENCES "paging_group"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "paging_group_member" ADD CONSTRAINT "paging_group_member_extension_id_extension_id_fkey" FOREIGN KEY ("extension_id") REFERENCES "extension"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "queue" ADD CONSTRAINT "queue_agent_whisper_prompt_id_prompt_id_fkey" FOREIGN KEY ("agent_whisper_prompt_id") REFERENCES "prompt"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "park_lot" DROP CONSTRAINT "park_lot_timeout_destination_shape_check", ADD CONSTRAINT "park_lot_timeout_destination_shape_check" CHECK ((timeout_destination_type is null and timeout_destination_ref is null and timeout_destination_data is null) or (timeout_destination_type in ('extension', 'ivr', 'ring-group', 'queue', 'voicemail', 'conference', 'park', 'paging-group', 'time-condition') and timeout_destination_ref is not null) or (timeout_destination_type in ('external', 'application') and timeout_destination_ref is null and timeout_destination_data is not null) or (timeout_destination_type = 'hangup' and timeout_destination_ref is null));--> statement-breakpoint
ALTER TABLE "ivr_menu" DROP CONSTRAINT "ivr_menu_timeout_destination_shape_check", ADD CONSTRAINT "ivr_menu_timeout_destination_shape_check" CHECK ((timeout_destination_type is null and timeout_destination_ref is null and timeout_destination_data is null) or (timeout_destination_type in ('extension', 'ivr', 'ring-group', 'queue', 'voicemail', 'conference', 'park', 'paging-group', 'time-condition') and timeout_destination_ref is not null) or (timeout_destination_type in ('external', 'application') and timeout_destination_ref is null and timeout_destination_data is not null) or (timeout_destination_type = 'hangup' and timeout_destination_ref is null));--> statement-breakpoint
ALTER TABLE "ivr_menu" DROP CONSTRAINT "ivr_menu_invalid_destination_shape_check", ADD CONSTRAINT "ivr_menu_invalid_destination_shape_check" CHECK ((invalid_destination_type is null and invalid_destination_ref is null and invalid_destination_data is null) or (invalid_destination_type in ('extension', 'ivr', 'ring-group', 'queue', 'voicemail', 'conference', 'park', 'paging-group', 'time-condition') and invalid_destination_ref is not null) or (invalid_destination_type in ('external', 'application') and invalid_destination_ref is null and invalid_destination_data is not null) or (invalid_destination_type = 'hangup' and invalid_destination_ref is null));--> statement-breakpoint
ALTER TABLE "ivr_menu_option" DROP CONSTRAINT "ivr_menu_option_destination_shape_check", ADD CONSTRAINT "ivr_menu_option_destination_shape_check" CHECK ((destination_type in ('extension', 'ivr', 'ring-group', 'queue', 'voicemail', 'conference', 'park', 'paging-group', 'time-condition') and destination_ref is not null) or (destination_type in ('external', 'application') and destination_ref is null and destination_data is not null) or (destination_type = 'hangup' and destination_ref is null));--> statement-breakpoint
ALTER TABLE "phone_number" DROP CONSTRAINT "phone_number_destination_shape_check", ADD CONSTRAINT "phone_number_destination_shape_check" CHECK ((destination_type in ('extension', 'ivr', 'ring-group', 'queue', 'voicemail', 'conference', 'park', 'paging-group', 'time-condition') and destination_ref is not null) or (destination_type in ('external', 'application') and destination_ref is null and destination_data is not null) or (destination_type = 'hangup' and destination_ref is null));--> statement-breakpoint
ALTER TABLE "queue" DROP CONSTRAINT "queue_timeout_destination_shape_check", ADD CONSTRAINT "queue_timeout_destination_shape_check" CHECK ((timeout_destination_type is null and timeout_destination_ref is null and timeout_destination_data is null) or (timeout_destination_type in ('extension', 'ivr', 'ring-group', 'queue', 'voicemail', 'conference', 'park', 'paging-group', 'time-condition') and timeout_destination_ref is not null) or (timeout_destination_type in ('external', 'application') and timeout_destination_ref is null and timeout_destination_data is not null) or (timeout_destination_type = 'hangup' and timeout_destination_ref is null));--> statement-breakpoint
ALTER TABLE "ring_group" DROP CONSTRAINT "ring_group_timeout_destination_shape_check", ADD CONSTRAINT "ring_group_timeout_destination_shape_check" CHECK ((timeout_destination_type is null and timeout_destination_ref is null and timeout_destination_data is null) or (timeout_destination_type in ('extension', 'ivr', 'ring-group', 'queue', 'voicemail', 'conference', 'park', 'paging-group', 'time-condition') and timeout_destination_ref is not null) or (timeout_destination_type in ('external', 'application') and timeout_destination_ref is null and timeout_destination_data is not null) or (timeout_destination_type = 'hangup' and timeout_destination_ref is null));--> statement-breakpoint
ALTER TABLE "ring_group_destination" DROP CONSTRAINT "ring_group_destination_destination_shape_check", ADD CONSTRAINT "ring_group_destination_destination_shape_check" CHECK ((destination_type in ('extension', 'ivr', 'ring-group', 'queue', 'voicemail', 'conference', 'park', 'paging-group', 'time-condition') and destination_ref is not null) or (destination_type in ('external', 'application') and destination_ref is null and destination_data is not null) or (destination_type = 'hangup' and destination_ref is null));--> statement-breakpoint
ALTER TABLE "inbound_route" DROP CONSTRAINT "inbound_route_destination_shape_check", ADD CONSTRAINT "inbound_route_destination_shape_check" CHECK ((destination_type in ('extension', 'ivr', 'ring-group', 'queue', 'voicemail', 'conference', 'park', 'paging-group', 'time-condition') and destination_ref is not null) or (destination_type in ('external', 'application') and destination_ref is null and destination_data is not null) or (destination_type = 'hangup' and destination_ref is null));--> statement-breakpoint
ALTER TABLE "inbound_route" DROP CONSTRAINT "inbound_route_failover_destination_shape_check", ADD CONSTRAINT "inbound_route_failover_destination_shape_check" CHECK ((failover_destination_type is null and failover_destination_ref is null and failover_destination_data is null) or (failover_destination_type in ('extension', 'ivr', 'ring-group', 'queue', 'voicemail', 'conference', 'park', 'paging-group', 'time-condition') and failover_destination_ref is not null) or (failover_destination_type in ('external', 'application') and failover_destination_ref is null and failover_destination_data is not null) or (failover_destination_type = 'hangup' and failover_destination_ref is null));--> statement-breakpoint
ALTER TABLE "outbound_route" DROP CONSTRAINT "outbound_route_failover_destination_shape_check", ADD CONSTRAINT "outbound_route_failover_destination_shape_check" CHECK ((failover_destination_type is null and failover_destination_ref is null and failover_destination_data is null) or (failover_destination_type in ('extension', 'ivr', 'ring-group', 'queue', 'voicemail', 'conference', 'park', 'paging-group', 'time-condition') and failover_destination_ref is not null) or (failover_destination_type in ('external', 'application') and failover_destination_ref is null and failover_destination_data is not null) or (failover_destination_type = 'hangup' and failover_destination_ref is null));--> statement-breakpoint
ALTER TABLE "time_condition" DROP CONSTRAINT "time_condition_destination_shape_check", ADD CONSTRAINT "time_condition_destination_shape_check" CHECK ((destination_type in ('extension', 'ivr', 'ring-group', 'queue', 'voicemail', 'conference', 'park', 'paging-group', 'time-condition') and destination_ref is not null) or (destination_type in ('external', 'application') and destination_ref is null and destination_data is not null) or (destination_type = 'hangup' and destination_ref is null));--> statement-breakpoint
ALTER TABLE "time_condition" DROP CONSTRAINT "time_condition_nomatch_destination_shape_check", ADD CONSTRAINT "time_condition_nomatch_destination_shape_check" CHECK ((nomatch_destination_type is null and nomatch_destination_ref is null and nomatch_destination_data is null) or (nomatch_destination_type in ('extension', 'ivr', 'ring-group', 'queue', 'voicemail', 'conference', 'park', 'paging-group', 'time-condition') and nomatch_destination_ref is not null) or (nomatch_destination_type in ('external', 'application') and nomatch_destination_ref is null and nomatch_destination_data is not null) or (nomatch_destination_type = 'hangup' and nomatch_destination_ref is null));--> statement-breakpoint
ALTER TABLE "voicemail_option" DROP CONSTRAINT "voicemail_option_destination_shape_check", ADD CONSTRAINT "voicemail_option_destination_shape_check" CHECK ((destination_type in ('extension', 'ivr', 'ring-group', 'queue', 'voicemail', 'conference', 'park', 'paging-group', 'time-condition') and destination_ref is not null) or (destination_type in ('external', 'application') and destination_ref is null and destination_data is not null) or (destination_type = 'hangup' and destination_ref is null));--> statement-breakpoint
CREATE POLICY "paging_group_tenant_isolation" ON "paging_group" AS PERMISSIVE FOR ALL TO "pbx_tenant_tls" USING (organization_id = nullif(current_setting('pbx_tenant_tls.organization_id', true), '')::uuid) WITH CHECK (organization_id = nullif(current_setting('pbx_tenant_tls.organization_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "paging_group_member_tenant_isolation" ON "paging_group_member" AS PERMISSIVE FOR ALL TO "pbx_tenant_tls" USING (organization_id = nullif(current_setting('pbx_tenant_tls.organization_id', true), '')::uuid) WITH CHECK (organization_id = nullif(current_setting('pbx_tenant_tls.organization_id', true), '')::uuid);