/**
 * DTMF — digits, sources, and the outcome vocabulary for digit collection.
 *
 * Frozen source of truth: `plans/reference/freeswitch-capabilities.md` §4 ("Sources: RFC 2833
 * telephone-event (PT 101), SIP INFO, inband detect, app-generated. Per-channel queue. Collection:
 * play_and_get_digits w/ regex validation + retries; inter-digit timeouts").
 *
 * The engine keeps one ordered queue per channel and drains it into whatever is collecting. The
 * types here are what both ends of that queue agree on; the queue itself is engine state.
 */

/**
 * The 16 DTMF symbols. `A`-`D` are rare on handsets but arrive from PRI gateways and are used by
 * some auto-attendants, so they are accepted rather than silently dropped.
 */
export const DTMF_DIGITS = [
	"0",
	"1",
	"2",
	"3",
	"4",
	"5",
	"6",
	"7",
	"8",
	"9",
	"*",
	"#",
	"A",
	"B",
	"C",
	"D",
] as const;

export type DtmfDigit = (typeof DTMF_DIGITS)[number];

/**
 * How a digit reached us.
 *
 * - `rfc2833` — RTP telephone-event payload (the default; payload type 101 by convention).
 * - `info` — SIP INFO body; signaling-path only, so it survives a bypassed media path.
 * - `inband` — detected from decoded audio. Requires a decoding media path (see
 *   `bridgeModeDecodesMedia`) and is the least reliable source.
 * - `application` — generated by us (feature codes, confirmation prompts, injected digits).
 */
export const DTMF_SOURCES = ["rfc2833", "info", "inband", "application"] as const;

export type DtmfSource = (typeof DTMF_SOURCES)[number];

/** Nominal duration of a generated digit when a verb does not specify one. */
export const DEFAULT_DTMF_DURATION_MS = 100;

/** A single digit as it leaves the per-channel queue. */
export type DtmfEvent = {
	readonly digit: DtmfDigit;
	/** How long the tone lasted, in milliseconds. */
	readonly durationMs: number;
	readonly source: DtmfSource;
};

/**
 * Why a digit collection stopped. Every collection ends with exactly one of these, which is what
 * lets an IVR distinguish "the caller pressed nothing" from "the caller pressed # immediately".
 *
 * - `max-digits` — the requested digit count was reached.
 * - `terminator` — a terminator key was pressed. The terminator is not part of the digits.
 * - `timeout` — the overall timeout elapsed before the first digit.
 * - `inter-digit-timeout` — the caller stopped part-way through.
 * - `pattern` — the accumulated digits matched the supplied regex, ending collection early.
 * - `cancelled` — the engine abandoned the collection (transfer, new verb, drain).
 * - `hangup` — the channel went away mid-collection.
 */
export const DTMF_COLLECTION_END_REASONS = [
	"max-digits",
	"terminator",
	"timeout",
	"inter-digit-timeout",
	"pattern",
	"cancelled",
	"hangup",
] as const;

export type DtmfCollectionEndReason = (typeof DTMF_COLLECTION_END_REASONS)[number];

/** The result of one digit collection. `digits` never contains the terminator that ended it. */
export type DtmfCollection = {
	readonly digits: readonly DtmfDigit[];
	readonly endReason: DtmfCollectionEndReason;
	/** The terminator that ended the collection, when `endReason` is `terminator`. */
	readonly terminator?: DtmfDigit;
};

const DTMF_DIGIT_SET = new Set<string>(DTMF_DIGITS);

/** Type guard for a single character arriving from a media adapter, a webhook or an API payload. */
export function isDtmfDigit(value: string): value is DtmfDigit {
	return DTMF_DIGIT_SET.has(value);
}

/**
 * Splits a digit string (`"*98#"`) into typed digits.
 *
 * Lower-case `a`-`d` are normalised up, since that is how they arrive from several gateways.
 * Returns `undefined` for any string containing a character that is not a DTMF symbol — callers
 * treat that as invalid input rather than silently collecting a partial sequence.
 */
export function parseDtmfDigits(value: string): readonly DtmfDigit[] | undefined {
	const digits: DtmfDigit[] = [];

	for (const character of value) {
		const normalised = character.toUpperCase();
		if (!isDtmfDigit(normalised)) {
			return undefined;
		}
		digits.push(normalised);
	}

	return digits;
}

/** Renders typed digits back to the compact wire/log form (`["*", "9", "8"]` → `"*98"`). */
export function formatDtmfDigits(digits: readonly DtmfDigit[]): string {
	return digits.join("");
}
