/**
 * `@optimiq-voice/telephony` — the pure call domain.
 *
 * Zero runtime dependencies, by design. Nothing here imports a database, a broker, NestJS or
 * Effect: these are the invariants of a phone call, and they must be usable from the engine, the
 * control plane, the CDR writer, the routing compiler and a test with equal ease.
 *
 * The behaviours are derived from `plans/reference/freeswitch-capabilities.md` §1-§8 and
 * `plans/optimiq-voice-master-plan.md` §4.2; no FreeSWITCH code or naming is reproduced.
 */

export {
	assertBridgeTransition,
	BRIDGE_MODES,
	BRIDGE_STATES,
	bridgeModeDecodesMedia,
	bridgeModeRelaysMedia,
	bridgeTransitionsFrom,
	DEFAULT_BRIDGE_MODE,
	INITIAL_BRIDGE_STATE,
	isBridgeMode,
	isBridgeState,
	isLegRole,
	isTerminalBridgeState,
	isValidBridgeTransition,
	LEG_ROLES,
	oppositeLegRole,
	requiresRenegotiation,
	supportsMediaBug,
	supportsRecording,
	UNBRIDGE_REASONS,
	VALID_BRIDGE_TRANSITIONS,
	type Bridge,
	type BridgeLeg,
	type BridgeMode,
	type BridgeModeChange,
	type BridgeState,
	type LegRole,
	type UnbridgeReason,
} from "./bridge";
export {
	aggregateDeviceState,
	ALERTING_CALL_STATES,
	assertCallStateTransition,
	CALL_STATES,
	callStateTransitionsFrom,
	DEVICE_STATES,
	INITIAL_CALL_STATE,
	isAlertingCallState,
	isAnsweredCallState,
	isCallState,
	isDeviceState,
	isTerminalCallState,
	isValidCallStateTransition,
	ON_CALL_CALL_STATES,
	VALID_CALL_STATE_TRANSITIONS,
	type CallState,
	type DeviceState,
} from "./call-state";
export {
	CHANNEL_DIRECTIONS,
	CHANNEL_FLAGS,
	hasChannelFlag,
	hasMediaPath,
	isChannelDirection,
	isChannelFlag,
	isVariableScope,
	VARIABLE_SCOPES,
	type CallerProfile,
	type ChannelDirection,
	type ChannelFlag,
	type ChannelSnapshot,
	type VariableScope,
} from "./channel";
export {
	assertChannelTransition,
	CHANNEL_STATES,
	CHANNEL_TEARDOWN_STATES,
	channelTransitionsFrom,
	INITIAL_CHANNEL_STATE,
	isChannelState,
	isLiveChannelState,
	isTeardownChannelState,
	isTerminalChannelState,
	isValidChannelTransition,
	VALID_CHANNEL_TRANSITIONS,
	type ChannelState,
} from "./channel-state";
export {
	DEFAULT_DTMF_DURATION_MS,
	DTMF_COLLECTION_END_REASONS,
	DTMF_DIGITS,
	DTMF_SOURCES,
	formatDtmfDigits,
	isDtmfDigit,
	parseDtmfDigits,
	type DtmfCollection,
	type DtmfCollectionEndReason,
	type DtmfDigit,
	type DtmfEvent,
	type DtmfSource,
} from "./dtmf";
export {
	InvalidBridgeTransitionError,
	InvalidCallStateTransitionError,
	InvalidChannelTransitionError,
	TelephonyError,
} from "./errors";
export {
	CALL_EVENT_NAMES,
	CALL_STATE_MILESTONE_EVENTS,
	CHANNEL_STATE_MILESTONE_EVENTS,
	isCallEventName,
	type BridgeBridgedEvent,
	type BridgeCreatedEvent,
	type BridgeUnbridgedEvent,
	type CallEvent,
	type CallEventBase,
	type CallEventName,
	type CallEventOf,
	type CallHeldEvent,
	type CallParkedEvent,
	type CallTransferCompletedEvent,
	type CallTransferFailedEvent,
	type CallTransferStartedEvent,
	type CallUnheldEvent,
	type CallUnparkedEvent,
	type ChannelAnsweredEvent,
	type ChannelCallStateChangedEvent,
	type ChannelCreatedEvent,
	type ChannelDestroyedEvent,
	type ChannelDtmfEvent,
	type ChannelEarlyMediaEvent,
	type ChannelHangupEvent,
	type ChannelOriginatedEvent,
	type ChannelProgressEvent,
	type ChannelRoutingEvent,
	type ChannelStateChangedEvent,
	type ChannelVerbCompletedEvent,
	type ChannelVerbStartedEvent,
	type DeviceStateChangedEvent,
	type PlaybackStartedEvent,
	type PlaybackStoppedEvent,
	type RecordStartedEvent,
	type RecordStoppedEvent,
} from "./events";
export {
	ANSWERED_HANGUP_CAUSES,
	EXTENDED_HANGUP_CAUSES,
	HANGUP_CAUSE_CODES,
	HANGUP_CAUSE_NAMES,
	HANGUP_CAUSES,
	hangupCauseCode,
	hangupCauseFromCode,
	isAnsweredCause,
	isHangupCause,
	isRetryableCause,
	Q850_HANGUP_CAUSES,
	RETRYABLE_HANGUP_CAUSES,
	type ExtendedHangupCause,
	type HangupCause,
	type Q850HangupCause,
} from "./hangup-causes";
export {
	DIAL_STRATEGIES,
	DIAL_TARGET_KINDS,
	GATHER_SOURCES,
	isProgressVerb,
	isTerminalVerb,
	isVerbName,
	MEDIA_PATH_VERBS,
	MUTE_DIRECTIONS,
	PLAYBACK_ACTIONS,
	PROGRESS_SIP_CODES,
	PROGRESS_VERBS,
	RECORD_FORMATS,
	TERMINAL_VERBS,
	TRANSFER_KINDS,
	VERB_END_REASONS,
	VERB_NAMES,
	verbRequiresMediaPath,
	type AcknowledgedResult,
	type AnswerVerb,
	type BridgeVerb,
	type CallerIdOverride,
	type DialConfirm,
	type DialResult,
	type DialStrategy,
	type DialTarget,
	type DialTargetKind,
	type DialVerb,
	type EarlyMediaVerb,
	type GatherResult,
	type GatherSource,
	type GatherVerb,
	type HangupVerb,
	type HoldVerb,
	type MediaRef,
	type MuteDirection,
	type MuteVerb,
	type ParkVerb,
	type PlaybackAction,
	type PlaybackControlVerb,
	type PlaybackResult,
	type PlayDtmfVerb,
	type PlayVerb,
	type RecordFormat,
	type RecordResult,
	type RecordVerb,
	type RingingVerb,
	type SayVerb,
	type SetVariableVerb,
	type SleepVerb,
	type StopPlayVerb,
	type StopSayVerb,
	type StopStreamGatherVerb,
	type StopStreamVerb,
	type StreamGatherVerb,
	type StreamVerb,
	type TransferDestination,
	type TransferKind,
	type TransferVerb,
	type UnbridgeVerb,
	type UnholdVerb,
	type UnmuteVerb,
	type UnparkVerb,
	type Verb,
	type VerbEndReason,
	type VerbName,
	type VerbOf,
	type VerbResult,
} from "./verbs";
