import { assertEnvsAreSet } from "@optimiq-voice/common";

assertEnvsAreSet([
	"MCP_WORKSPACE_ACCESS_KEY_ID",
	"MCP_APIKEY_ACCESS_KEY_ID",
	"MCP_APIKEY_ACCESS_KEY_SECRET",
]);

const WORKSPACE_ACCESS_KEY_ID = process.env.MCP_WORKSPACE_ACCESS_KEY_ID;
const ACCESS_KEY_ID = process.env.MCP_APIKEY_ACCESS_KEY_ID;
const ACCESS_KEY_SECRET = process.env.MCP_APIKEY_ACCESS_KEY_SECRET;
const ENDPOINT = process.env.MCP_ENDPOINT;
const ALLOW_INSECURE = process.env.MCP_ALLOW_INSECURE === "true";

export { WORKSPACE_ACCESS_KEY_ID, ACCESS_KEY_ID, ACCESS_KEY_SECRET, ENDPOINT, ALLOW_INSECURE };
